import type { DashboardSurface } from "./types";

export const GUIDE_STAGE_CODES = ["tax_guide", "loan_guide"] as const;

export const SURFACE_HREFS: Record<DashboardSurface, string> = {
  home: "/",
  current: "/current",
  roadmap: "/roadmap",
  guides: "/guides",
  franchise: "/franchise",
  profile: "/profile",
  analytics: "/analytics",
  marketing: "/marketing",
  reports: "/reports",
  team: "/team",
  tax: "/tax"
};
export const VENDOR_URL_MAP: Record<string, string> = {
  "홈택스(Hometax)": "https://hometax.go.kr/websquare/websquare.html?w2xPath=/ui/pp/index_pp.xml&menuCd=index3",
  "비즈플레이(Bizplay)": "https://www.bizplay.co.kr",
  "캐시노트(CashNote)": "https://cashnote.kr",
  "마켓컬리 비즈(Kurly Biz)": "https://biz.kurly.com",
  "쿠팡 비즈니스": "https://biz.coupang.com",
  "aT 한국농수산식품유통공사": "https://www.at.or.kr",
  "커피빈코리아 B2B": "https://www.coffeebeankorea.com",
  "빈브라더스": "https://beanbrothers.co.kr",
  "테라로사": "https://www.terarosa.com",
  "모닌(Monin)": "https://www.monin.com/kr",
  "1883 루아(Routin)": "https://www.routin1883.com",
  "토라니(Torani)": "https://torani.com",
  "서울우유 업소용": "https://www.seoulmilk.co.kr",
  "매일유업 바리스타": "https://www.maeil.com",
  "오틀리(Oatly)": "https://www.oatly.com/kr",
  "하나팩": "https://www.hanapack.co.kr",
  "현진팩": "https://www.hjpack.co.kr",
  "페이퍼갱": "https://www.papergang.co.kr",
  "아성다이소 기업구매": "https://b2b.daiso.co.kr",
  "유한킴벌리 B2B": "https://www.yuhan-kimberly.co.kr",
  "3M 업소용": "https://www.3mkorea.co.kr",
  "CJ프레시웨이": "https://www.cjfreshway.com",
  "마켓컬리 비즈": "https://biz.kurly.com",
  "아워홈 식자재": "https://www.ourhome.co.kr",
  "대상 청정원 업소용": "https://www.chungjungone.com",
  "샘표 기업용": "https://www.sempio.com",
  "오뚜기 업소용": "https://www.ottogi.co.kr",
  "대한제분(곰표)": "https://www.dhflour.co.kr",
  "농협 직거래": "https://www.nonghyup.com",
  "CJ제일제당 B2B": "https://www.cj.co.kr",
  "원팩(Wonpak)": "https://www.wonpak.co.kr",
  "유한킴벌리 업소용": "https://www.yuhan-kimberly.co.kr",
  "유한양행 업소용": "https://www.yuhan.co.kr",
  "아모레퍼시픽 프로(에이모스)": "https://www.amorepacificpro.co.kr",
  "로레알 프로(케라스타즈·레드켄)": "https://www.loreal-professionnel.com/ko-kr",
  "웰라 코리아(Wella)": "https://www.wella.com/ko-KR",
  "파나소닉 업소용": "https://panasonic.net/cns/sav/kr",
  "다이슨 프로(Dyson Pro)": "https://www.dyson.co.kr",
  "GHD 코리아": "https://www.ghdhair.com/ko-kr",
  "지에이치 전문부자재": "https://www.ghpro.co.kr",
  "코스모프로페셔널": "https://www.cosmoprofessional.co.kr",
  "보령헬스케어": "https://www.boreonghc.co.kr",
  "라이프피트니스(Life Fitness)": "https://www.lifefitness.com/ko-kr",
  "테크노짐(Technogym)": "https://www.technogym.com",
  "오딘피트니스": "https://www.odinfitness.com",
  "발렉스(Valeo)": "https://www.valeofit.com",
  "리복 프로(Reebok Pro)": "https://www.reebok.co.kr",
  "마이단백질(MyProtein) B2B": "https://www.myprotein.com/sports-nutrition",
  "쿠팡 비즈": "https://biz.coupang.com",
  "천재교육 B2B": "https://www.chunjae.co.kr",
  "비상교육": "https://www.visang.com",
  "메가스터디 교육": "https://www.megastudy.net",
  "퍼시스(Persis)": "https://www.fursys.com",
  "리바트(Livart) 에듀": "https://www.livart.co.kr",
  "코아스(Koas)": "https://www.koas.co.kr",
  "모나미 B2B": "https://www.monami.com",
  "교보문고 교육자료": "https://www.kyobobook.co.kr",
  "로얄캐닌(Royal Canin) B2B": "https://www.royalcanin.com/ko",
  "힐스(Hill's) 코리아": "https://www.hillspet.co.kr",
  "퓨리나(Purina) B2B": "https://www.purina.co.kr",
  "크리스탈 펫": "https://www.crystalpet.co.kr",
  "바이오그룸(Biogroom)": "https://www.biogroom.com",
  "아이러브펫": "https://www.ilovepet.co.kr",
  "리치펫(Richpet)": "https://www.richpet.co.kr",
  "슈가버블": "https://www.sugarbubble.co.kr",
  "쿠팡 펫 비즈": "https://biz.coupang.com",
  "비오킬(Biokil) 코리아": "https://www.biokil.co.kr",
  "온채널(OnChannel)": "https://www.onch3.co.kr",
  "동대문 패션타운": "https://www.ddmt.co.kr",
  "무역협회(KITA) B2B": "https://www.kita.net",
  "KIS정보통신": "https://www.kisvan.co.kr",
  "토스페이먼츠": "https://www.tosspayments.com",
  "스마트로(Smartro)": "https://www.smartro.co.kr",
  "한국포장(KPK)": "https://www.kpk.co.kr",
  "KIS정보통신 소모품": "https://www.kisvan.co.kr",
  "LG전자 클로이 B2B": "https://www.lge.co.kr/b2b",
  "삼성전자 업소용": "https://www.samsung.com/sec/b2b",
  "일렉트로룩스(Electrolux)": "https://www.electrolux.co.kr",
  "P&G 업소용(타이드·다우니)": "https://www.pg.co.kr",
  "애경 B2B(퍼실)": "https://www.aekyung.co.kr",
  "에코버(Ecover) 코리아": "https://www.ecover.com",
  "KIS정보통신 POS": "https://www.kisvan.co.kr",
  "워드빌(Wordville)": "https://www.wordville.co.kr",
  "나이스페이(Nicepay)": "https://www.nicepay.co.kr",
  "시디즈(Sidiz)": "https://www.sidiz.com",
  "타임키퍼(TimeKeeper)": "https://www.timekeeper.co.kr",
  "스마트인": "https://www.smartin.co.kr",
  "스터디유(StudyU)": "https://www.studyu.co.kr",
  "롯데네슬레 자판기": "https://www.lottene.com",
  "동서식품 B2B": "https://www.dongsuh.com",
  "네스프레소 프로": "https://www.nespresso.com/pro/kr",
};

