//
//  FinancialBenchmarkRegistry.swift — 세부업종 월 비용 벤치마크 (웹 SSOT 자동 생성 미러)
//
//  ⚠️ 웹 SSOT: apps/web/app/lib/components/stages/shared-tail/FinancialReviewStage.tsx
//             → SUB_INDUSTRY_BENCHMARKS. 스크립트로 파싱·생성 (수동 편집 금지, 재생성 권장).
//  primeMaxPct = min(재료상한 + 인건비상한, 95) 로 도출 (웹은 카테고리 폴백에만 존재).
//

import Foundation

public enum FinancialBenchmarkRegistry {
    /// 세부업종(specialty) ID → 월 비용 벤치마크. 없으면 nil → 호출부에서 cluster.costBenchmark 폴백.
    public static func benchmark(forSpecialty id: String) -> IndustryCluster.CostBenchmark? {
        sub[id]
    }

    private static let sub: [String: IndustryCluster.CostBenchmark] = [
        "icecream-bingsu": .init(materialsPctRange: 35...40, laborPctRange: 18...24, rentPctRange: 10...15, utilitiesPctRange: 4...6, sgaPctRange: 3...5, marketingPctRange: 3...5, otherPctRange: 4...6, marginPctRange: 10...18, primeMaxPct: 64, notes: "여름 피크·겨울 비수기 — 시즌성 현금흐름 관리 핵심"),
        "takeout-coffee": .init(materialsPctRange: 25...30, laborPctRange: 25...30, rentPctRange: 12...18, utilitiesPctRange: 3...5, sgaPctRange: 2...4, marketingPctRange: 2...4, otherPctRange: 3...5, marginPctRange: 15...25, primeMaxPct: 60, notes: "회전율 매출 — 컵·우유·원두 단가 관리가 마진"),
        "specialty-coffee": .init(materialsPctRange: 30...35, laborPctRange: 25...30, rentPctRange: 12...18, utilitiesPctRange: 4...6, sgaPctRange: 2...4, marketingPctRange: 3...5, otherPctRange: 3...5, marginPctRange: 15...22, primeMaxPct: 65, notes: "프리미엄 원두 비중 高 — 객단가 높이는 메뉴 설계 필수"),
        "dessert-cafe": .init(materialsPctRange: 35...45, laborPctRange: 22...28, rentPctRange: 10...15, utilitiesPctRange: 4...6, sgaPctRange: 3...5, marketingPctRange: 4...7, otherPctRange: 3...5, marginPctRange: 10...18, primeMaxPct: 73, notes: "재료 폐기율 ↑ — 당일 제조·SNS 마케팅이 핵심"),
        "bakery-studio": .init(materialsPctRange: 30...38, laborPctRange: 30...38, rentPctRange: 10...15, utilitiesPctRange: 5...8, sgaPctRange: 2...4, marketingPctRange: 3...5, otherPctRange: 3...5, marginPctRange: 10...18, primeMaxPct: 76, notes: "제빵 기술 인건비 비중 高 — 새벽 작업·발효기 가스비 ↑"),
        "self-serve-cafe": .init(materialsPctRange: 25...30, laborPctRange: 5...12, rentPctRange: 12...18, utilitiesPctRange: 4...6, sgaPctRange: 3...5, marketingPctRange: 3...5, otherPctRange: 5...8, marginPctRange: 20...30, primeMaxPct: 42, notes: "무인 — 인건비 최소, 기기 유지보수·청소 외주비 별도"),
        "ramen-noodle": .init(materialsPctRange: 35...42, laborPctRange: 20...25, rentPctRange: 8...12, utilitiesPctRange: 4...6, sgaPctRange: 3...5, marketingPctRange: 2...4, otherPctRange: 3...5, marginPctRange: 12...20, primeMaxPct: 67, notes: "사골 육수 원재료 + 회전율 — 점심 1.5회전 이상 필요"),
        "korean-casual": .init(materialsPctRange: 40...48, laborPctRange: 22...30, rentPctRange: 8...12, utilitiesPctRange: 4...6, sgaPctRange: 3...5, marketingPctRange: 2...4, otherPctRange: 3...5, marginPctRange: 8...15, primeMaxPct: 78, notes: "반찬 多 → 식자재·폐기율 ↑ / 백반 가격 경직성 ↑"),
        "chicken-burger": .init(materialsPctRange: 35...42, laborPctRange: 18...24, rentPctRange: 8...12, utilitiesPctRange: 4...6, sgaPctRange: 10...15, marketingPctRange: 3...5, otherPctRange: 3...5, marginPctRange: 8...15, primeMaxPct: 66, notes: "★ 배달 수수료 10~15% 별도 — 매출의 25~30%가 플랫폼"),
        "delivery-meals": .init(materialsPctRange: 32...38, laborPctRange: 12...18, rentPctRange: 5...8, utilitiesPctRange: 3...5, sgaPctRange: 15...22, marketingPctRange: 3...5, otherPctRange: 3...5, marginPctRange: 10...18, primeMaxPct: 56, notes: "★ 배달 수수료 비중 최고 — 좌석 X 작은 매장이 정석"),
        "salad-healthy": .init(materialsPctRange: 38...45, laborPctRange: 20...25, rentPctRange: 10...15, utilitiesPctRange: 3...5, sgaPctRange: 4...7, marketingPctRange: 4...7, otherPctRange: 3...5, marginPctRange: 8...15, primeMaxPct: 70, notes: "신선 채소 폐기율 ↑ — 당일 입고·매진 운영"),
        "western-pasta-brunch": .init(materialsPctRange: 32...38, laborPctRange: 25...32, rentPctRange: 10...15, utilitiesPctRange: 4...6, sgaPctRange: 3...5, marketingPctRange: 4...6, otherPctRange: 3...5, marginPctRange: 10...18, primeMaxPct: 70, notes: "객단가 高 — 와인 마진·테이블 회전율이 수익 결정"),
        "hair-salon": .init(materialsPctRange: 5...10, laborPctRange: 50...60, rentPctRange: 12...18, utilitiesPctRange: 3...5, sgaPctRange: 2...4, marketingPctRange: 3...5, otherPctRange: 4...6, marginPctRange: 10...18, primeMaxPct: 70, notes: "★ 디자이너 수익 분배 50%+ — 인건비 비중 가장 높음"),
        "nail-studio": .init(materialsPctRange: 8...12, laborPctRange: 50...60, rentPctRange: 10...15, utilitiesPctRange: 2...4, sgaPctRange: 2...4, marketingPctRange: 4...6, otherPctRange: 4...6, marginPctRange: 10...18, primeMaxPct: 72, notes: "1:1 시술 — 노쇼·예약 효율이 마진 결정"),
        "skin-care-room": .init(materialsPctRange: 12...18, laborPctRange: 40...50, rentPctRange: 12...18, utilitiesPctRange: 3...5, sgaPctRange: 2...4, marketingPctRange: 5...8, otherPctRange: 3...5, marginPctRange: 12...22, primeMaxPct: 68, notes: "기기·화장품 단가 ↑ / 멤버십 모델로 안정화 가능"),
        "waxing-studio": .init(materialsPctRange: 8...12, laborPctRange: 45...55, rentPctRange: 10...15, utilitiesPctRange: 2...4, sgaPctRange: 2...4, marketingPctRange: 5...8, otherPctRange: 4...6, marginPctRange: 12...20, primeMaxPct: 67, notes: "재료 단가 낮음·기술 인건비 높음 — 단골 회전이 핵심"),
        "eyelash-brow": .init(materialsPctRange: 10...15, laborPctRange: 50...60, rentPctRange: 10...15, utilitiesPctRange: 2...4, sgaPctRange: 2...4, marketingPctRange: 5...8, otherPctRange: 3...5, marginPctRange: 10...18, primeMaxPct: 75, notes: "글루·핀셋 등 소모품 + 1인 시술자 비중 高"),
        "makeup-bridal": .init(materialsPctRange: 10...15, laborPctRange: 40...50, rentPctRange: 8...12, utilitiesPctRange: 2...4, sgaPctRange: 2...4, marketingPctRange: 8...12, otherPctRange: 3...5, marginPctRange: 15...25, primeMaxPct: 65, notes: "출장형이면 임대료 낮음 — 시즌(결혼식 5/10월) 매출 집중"),
        "pilates-studio": .init(materialsPctRange: 3...6, laborPctRange: 50...60, rentPctRange: 18...25, utilitiesPctRange: 3...5, sgaPctRange: 3...5, marketingPctRange: 4...7, otherPctRange: 4...6, marginPctRange: 8...18, primeMaxPct: 66, notes: "리포머 등 기구 감가상각 + 강사 수익 분배 50%+"),
        "pt-gym": .init(materialsPctRange: 3...6, laborPctRange: 50...60, rentPctRange: 15...25, utilitiesPctRange: 4...7, sgaPctRange: 3...5, marketingPctRange: 4...7, otherPctRange: 3...5, marginPctRange: 10...20, primeMaxPct: 66, notes: "PT 트레이너 수익 분배 + 회원권 정기 매출"),
        "yoga-studio": .init(materialsPctRange: 2...5, laborPctRange: 40...50, rentPctRange: 20...28, utilitiesPctRange: 3...5, sgaPctRange: 3...5, marketingPctRange: 4...7, otherPctRange: 4...6, marginPctRange: 10...20, primeMaxPct: 55, notes: "강사 외부 → 인건비 변동, 임대료 고정 부담 큼"),
        "crossfit-box": .init(materialsPctRange: 3...6, laborPctRange: 40...50, rentPctRange: 18...25, utilitiesPctRange: 4...7, sgaPctRange: 3...5, marketingPctRange: 4...7, otherPctRange: 5...8, marginPctRange: 10...20, primeMaxPct: 56, notes: "그룹 클래스 — 1코치당 회원수 최대화가 마진 핵심"),
        "golf-studio": .init(materialsPctRange: 2...5, laborPctRange: 25...35, rentPctRange: 15...22, utilitiesPctRange: 5...8, sgaPctRange: 3...5, marketingPctRange: 4...7, otherPctRange: 8...12, marginPctRange: 15...28, primeMaxPct: 40, notes: "장비 감가상각 高·시간당 단가 모델 — 가동률 60%+ 필요"),
        "unmanned-fitness": .init(materialsPctRange: 2...5, laborPctRange: 5...12, rentPctRange: 18...25, utilitiesPctRange: 4...7, sgaPctRange: 4...7, marketingPctRange: 5...8, otherPctRange: 8...12, marginPctRange: 25...35, primeMaxPct: 17, notes: "무인 — 인건비 최소, CCTV·출입통제 시스템 비용 별도"),
        "pet-grooming": .init(materialsPctRange: 8...12, laborPctRange: 40...50, rentPctRange: 12...18, utilitiesPctRange: 3...5, sgaPctRange: 3...5, marketingPctRange: 4...7, otherPctRange: 5...8, marginPctRange: 12...20, primeMaxPct: 62, notes: "그루머 인건비 + 도구 소모 — 1인당 일 4~6마리 한계"),
        "pet-supplies": .init(materialsPctRange: 55...65, laborPctRange: 15...22, rentPctRange: 12...18, utilitiesPctRange: 3...5, sgaPctRange: 3...5, marketingPctRange: 4...7, otherPctRange: 3...5, marginPctRange: 5...12, primeMaxPct: 87, notes: "★ 사료·용품 매입원가 비중 최고 — 마진 8~12% 박리다매"),
        "pet-hotel": .init(materialsPctRange: 8...12, laborPctRange: 35...45, rentPctRange: 15...22, utilitiesPctRange: 4...7, sgaPctRange: 3...5, marketingPctRange: 4...7, otherPctRange: 5...8, marginPctRange: 15...25, primeMaxPct: 57, notes: "공휴일·휴가철 매출 집중 — 평일 가동률 관리"),
        "pet-cafe": .init(materialsPctRange: 25...32, laborPctRange: 25...32, rentPctRange: 15...22, utilitiesPctRange: 4...7, sgaPctRange: 3...5, marketingPctRange: 4...7, otherPctRange: 6...10, marginPctRange: 10...18, primeMaxPct: 64, notes: "거주 동물 사료·의료비 고정 — 입장료 + 음료 결합"),
        "pet-training-school": .init(materialsPctRange: 3...6, laborPctRange: 50...60, rentPctRange: 15...22, utilitiesPctRange: 3...5, sgaPctRange: 2...4, marketingPctRange: 5...8, otherPctRange: 4...6, marginPctRange: 12...20, primeMaxPct: 66, notes: "트레이너 인건비 + 공간 임대료 — 회당 단가 모델"),
        "kids-academy": .init(materialsPctRange: 3...8, laborPctRange: 45...55, rentPctRange: 15...22, utilitiesPctRange: 3...5, sgaPctRange: 2...4, marketingPctRange: 5...8, otherPctRange: 4...6, marginPctRange: 12...22, primeMaxPct: 63, notes: "강사 인건비 + 교재비 — 학부모 모집·재등록률이 핵심"),
        "study-cafe-space": .init(materialsPctRange: 2...5, laborPctRange: 5...12, rentPctRange: 25...35, utilitiesPctRange: 5...8, sgaPctRange: 3...5, marketingPctRange: 4...7, otherPctRange: 10...15, marginPctRange: 20...30, primeMaxPct: 17, notes: "무인 — 좌석 가동률 70%+ 임대료 부담 회수 가능"),
        "study-room": .init(materialsPctRange: 2...5, laborPctRange: 10...18, rentPctRange: 25...35, utilitiesPctRange: 5...8, sgaPctRange: 3...5, marketingPctRange: 5...8, otherPctRange: 8...12, marginPctRange: 15...25, primeMaxPct: 23, notes: "시간 단위 단가 — 예약 충돌·재청소 비용"),
        "adult-class": .init(materialsPctRange: 10...18, laborPctRange: 35...45, rentPctRange: 12...18, utilitiesPctRange: 3...5, sgaPctRange: 2...4, marketingPctRange: 8...12, otherPctRange: 4...6, marginPctRange: 15...25, primeMaxPct: 63, notes: "취미·소수정예 — 마케팅 비중 ↑, 강사 수익 분배"),
        "language-academy": .init(materialsPctRange: 5...10, laborPctRange: 45...55, rentPctRange: 15...22, utilitiesPctRange: 3...5, sgaPctRange: 2...4, marketingPctRange: 6...10, otherPctRange: 3...5, marginPctRange: 12...22, primeMaxPct: 65, notes: "원어민 강사 단가 高 — 상시반·단기반 mix 필요"),
        "coding-class": .init(materialsPctRange: 5...10, laborPctRange: 45...55, rentPctRange: 12...18, utilitiesPctRange: 4...6, sgaPctRange: 3...5, marketingPctRange: 5...8, otherPctRange: 4...6, marginPctRange: 15...25, primeMaxPct: 65, notes: "PC·소프트웨어 라이센스 + 강사 단가"),
        "small-study-room": .init(materialsPctRange: 3...8, laborPctRange: 40...50, rentPctRange: 10...15, utilitiesPctRange: 2...4, sgaPctRange: 2...4, marketingPctRange: 4...7, otherPctRange: 3...5, marginPctRange: 20...30, primeMaxPct: 58, notes: "1:1·소수 — 작은 공간 + 사장님 직강 시 마진 高"),
        "convenience-small": .init(materialsPctRange: 70...78, laborPctRange: 10...15, rentPctRange: 5...8, utilitiesPctRange: 3...5, sgaPctRange: 2...4, marketingPctRange: 1...3, otherPctRange: 2...4, marginPctRange: 3...8, primeMaxPct: 93, notes: "★ 매입원가 70%+ — 박리다매·24시 운영"),
        "lifestyle-goods": .init(materialsPctRange: 45...55, laborPctRange: 15...22, rentPctRange: 12...18, utilitiesPctRange: 2...4, sgaPctRange: 3...5, marketingPctRange: 5...8, otherPctRange: 3...5, marginPctRange: 10...18, primeMaxPct: 77, notes: "재고 회전 + 큐레이션 — 트렌드 추종 시 폐기율 ↑"),
        "beauty-supplies": .init(materialsPctRange: 50...60, laborPctRange: 15...22, rentPctRange: 12...18, utilitiesPctRange: 2...4, sgaPctRange: 3...5, marketingPctRange: 5...8, otherPctRange: 3...5, marginPctRange: 8...15, primeMaxPct: 82, notes: "유효기간 관리 + 테스터 위생 비용"),
        "fashion-accessories": .init(materialsPctRange: 40...50, laborPctRange: 15...22, rentPctRange: 12...18, utilitiesPctRange: 2...4, sgaPctRange: 3...5, marketingPctRange: 8...12, otherPctRange: 3...5, marginPctRange: 10...18, primeMaxPct: 72, notes: "트렌드 빠름 → 시즌 폐기 + 인스타 마케팅 비중 ↑"),
        "health-food-store": .init(materialsPctRange: 55...65, laborPctRange: 15...22, rentPctRange: 10...15, utilitiesPctRange: 2...4, sgaPctRange: 3...5, marketingPctRange: 5...8, otherPctRange: 3...5, marginPctRange: 8...15, primeMaxPct: 87, notes: "건강기능식품 인증·마진 박함 — 상담 매출 추가 필요"),
        "unmanned-retail": .init(materialsPctRange: 55...65, laborPctRange: 3...8, rentPctRange: 12...18, utilitiesPctRange: 3...5, sgaPctRange: 3...5, marketingPctRange: 3...5, otherPctRange: 10...15, marginPctRange: 8...15, primeMaxPct: 73, notes: "무인 — 도난·CCTV 비용 + 1일 1회 보충 인건비"),
        "self-laundry": .init(materialsPctRange: 3...6, laborPctRange: 3...8, rentPctRange: 25...35, utilitiesPctRange: 15...22, sgaPctRange: 3...5, marketingPctRange: 3...5, otherPctRange: 10...15, marginPctRange: 15...25, primeMaxPct: 14, notes: "★ 무인 — 임대료·전기·수도가 비용 구조 핵심"),
        "laundry-service": .init(materialsPctRange: 10...15, laborPctRange: 35...45, rentPctRange: 12...18, utilitiesPctRange: 10...15, sgaPctRange: 3...5, marketingPctRange: 4...7, otherPctRange: 5...8, marginPctRange: 10...18, primeMaxPct: 60, notes: "세제·전기·수도 고정 — 의류 분실 보험 별도"),
        "cleaning-service": .init(materialsPctRange: 5...10, laborPctRange: 55...65, rentPctRange: 3...8, utilitiesPctRange: 2...4, sgaPctRange: 3...5, marketingPctRange: 5...8, otherPctRange: 10...15, marginPctRange: 10...20, primeMaxPct: 75, notes: "방문형 — 인건비 절대 비중·이동비 + 도구 소모"),
        "repair-service": .init(materialsPctRange: 25...35, laborPctRange: 35...45, rentPctRange: 8...12, utilitiesPctRange: 2...4, sgaPctRange: 3...5, marketingPctRange: 5...8, otherPctRange: 3...5, marginPctRange: 10...20, primeMaxPct: 80, notes: "부품 매입 + 기술 인건비 — 보증·재방문 처리 비용"),
        "device-repair": .init(materialsPctRange: 40...50, laborPctRange: 25...35, rentPctRange: 8...12, utilitiesPctRange: 2...4, sgaPctRange: 3...5, marketingPctRange: 4...7, otherPctRange: 3...5, marginPctRange: 10...20, primeMaxPct: 85, notes: "iPhone·갤럭시 부품 매입 비중 高"),
        "print-copy": .init(materialsPctRange: 25...35, laborPctRange: 15...22, rentPctRange: 10...15, utilitiesPctRange: 10...15, sgaPctRange: 3...5, marketingPctRange: 3...5, otherPctRange: 10...15, marginPctRange: 10...18, primeMaxPct: 57, notes: "토너·잉크·용지 매입 + 전기료"),
        "rental-studio": .init(materialsPctRange: 3...6, laborPctRange: 10...18, rentPctRange: 30...40, utilitiesPctRange: 5...8, sgaPctRange: 4...7, marketingPctRange: 5...8, otherPctRange: 10...15, marginPctRange: 15...25, primeMaxPct: 24, notes: "임대료가 비용 절반 — 시간 단위 가동률이 마진 결정"),
        "party-room": .init(materialsPctRange: 5...10, laborPctRange: 15...22, rentPctRange: 25...35, utilitiesPctRange: 5...8, sgaPctRange: 4...7, marketingPctRange: 5...8, otherPctRange: 10...15, marginPctRange: 15...25, primeMaxPct: 32, notes: "주말·야간 집중 매출 — 청소·민원 대응 비용"),
        "shared-office": .init(materialsPctRange: 3...6, laborPctRange: 10...18, rentPctRange: 35...45, utilitiesPctRange: 5...8, sgaPctRange: 4...7, marketingPctRange: 5...8, otherPctRange: 8...12, marginPctRange: 15...25, primeMaxPct: 24, notes: "임대료 비중 최대 — 멤버십 정기 매출 안정성 핵심"),
        "practice-room": .init(materialsPctRange: 3...6, laborPctRange: 5...12, rentPctRange: 30...40, utilitiesPctRange: 8...12, sgaPctRange: 3...5, marketingPctRange: 5...8, otherPctRange: 10...15, marginPctRange: 15...25, primeMaxPct: 18, notes: "방음·악기 유지보수 비용 + 시간당 단가"),
        "guesthouse": .init(materialsPctRange: 8...15, laborPctRange: 15...30, rentPctRange: 25...40, utilitiesPctRange: 8...15, sgaPctRange: 5...10, marketingPctRange: 15...22, otherPctRange: 3...7, marginPctRange: 10...25, primeMaxPct: 45, notes: "OTA 14~16% + 청소·세탁·임대료가 고정비 핵심"),
        "smart-store": .init(materialsPctRange: 40...55, laborPctRange: 10...20, rentPctRange: 3...8, utilitiesPctRange: 2...5, sgaPctRange: 8...12, marketingPctRange: 15...25, otherPctRange: 2...5, marginPctRange: 15...30, primeMaxPct: 75, notes: "결제 3.74% + 매출연동 2% + CPC 광고 누적 부담"),
        "digital-products": .init(materialsPctRange: 3...8, laborPctRange: 30...50, rentPctRange: 0...5, utilitiesPctRange: 3...7, sgaPctRange: 10...15, marketingPctRange: 20...35, otherPctRange: 2...5, marginPctRange: 70...90, primeMaxPct: 58, notes: "크몽·인프런 15~20%·노션 마켓 5%, 광고 ROI 핵심"),
        "creator-service": .init(materialsPctRange: 10...20, laborPctRange: 25...45, rentPctRange: 3...10, utilitiesPctRange: 5...10, sgaPctRange: 5...10, marketingPctRange: 10...20, otherPctRange: 3...8, marginPctRange: 40...65, primeMaxPct: 65, notes: "편집 외주·장비 감가·썸네일이 가변비 핵심"),
        "consignment-commerce": .init(materialsPctRange: 55...70, laborPctRange: 10...20, rentPctRange: 2...6, utilitiesPctRange: 2...5, sgaPctRange: 8...12, marketingPctRange: 10...18, otherPctRange: 2...5, marginPctRange: 10...20, primeMaxPct: 90, notes: "마진 얇음 — 반품·CS·환율 리스크가 손익 좌우"),
        "newsletter-membership": .init(materialsPctRange: 5...12, laborPctRange: 30...50, rentPctRange: 0...5, utilitiesPctRange: 3...8, sgaPctRange: 12...18, marketingPctRange: 15...25, otherPctRange: 3...7, marginPctRange: 55...80, primeMaxPct: 62, notes: "Stibee·Patreon 10% + Stripe 3.4% + 콘텐츠 외주"),
        "global-buying": .init(materialsPctRange: 50...65, laborPctRange: 10...18, rentPctRange: 2...6, utilitiesPctRange: 3...7, sgaPctRange: 10...15, marketingPctRange: 10...18, otherPctRange: 3...7, marginPctRange: 10...22, primeMaxPct: 83, notes: "환율·해외배송·관세가 마진 잠식, 박리다매 구조"),
        "ai-application": .init(materialsPctRange: 15...30, laborPctRange: 40...55, rentPctRange: 5...12, utilitiesPctRange: 2...5, sgaPctRange: 5...10, marketingPctRange: 3...10, otherPctRange: 2...5, marginPctRange: 70...85, primeMaxPct: 85, isBurnBasis: true, notes: "Claude·Cursor·OpenAI API가 매월 가장 빠르게 늘어남"),
        "developer-tools": .init(materialsPctRange: 8...15, laborPctRange: 50...65, rentPctRange: 5...12, utilitiesPctRange: 2...5, sgaPctRange: 5...10, marketingPctRange: 5...12, otherPctRange: 2...5, marginPctRange: 75...90, primeMaxPct: 80, isBurnBasis: true, notes: "GitHub·CI/CD 비용 + 오픈소스 GTM 광고가 핵심"),
        "b2b-saas": .init(materialsPctRange: 10...18, laborPctRange: 45...60, rentPctRange: 5...12, utilitiesPctRange: 2...5, sgaPctRange: 8...12, marketingPctRange: 10...18, otherPctRange: 2...5, marginPctRange: 75...85, primeMaxPct: 78, isBurnBasis: true, notes: "엔터프라이즈 영업·SOC2·보안인증 비용 큼"),
        "fintech-startup": .init(materialsPctRange: 12...20, laborPctRange: 40...55, rentPctRange: 5...10, utilitiesPctRange: 2...5, sgaPctRange: 12...20, marketingPctRange: 5...12, otherPctRange: 5...10, marginPctRange: 60...75, primeMaxPct: 75, isBurnBasis: true, notes: "KYC·AML·금융위 컴플라이언스·법무가 압도적"),
        "healthtech-startup": .init(materialsPctRange: 10...18, laborPctRange: 40...55, rentPctRange: 5...12, utilitiesPctRange: 3...8, sgaPctRange: 10...15, marketingPctRange: 3...8, otherPctRange: 5...15, marginPctRange: 50...70, primeMaxPct: 73, isBurnBasis: true, notes: "임상·식약처 인증·의료기기 GMP 비용 변동성 큼"),
        "security-startup": .init(materialsPctRange: 12...20, laborPctRange: 50...65, rentPctRange: 5...10, utilitiesPctRange: 2...5, sgaPctRange: 8...12, marketingPctRange: 5...10, otherPctRange: 3...7, marginPctRange: 70...85, primeMaxPct: 85, isBurnBasis: true, notes: "테스트랩·CC인증·보안 컴플라이언스 비용 발생"),
        "hardware-iot": .init(materialsPctRange: 25...40, laborPctRange: 35...50, rentPctRange: 5...10, utilitiesPctRange: 3...7, sgaPctRange: 5...10, marketingPctRange: 3...8, otherPctRange: 3...8, marginPctRange: 40...60, primeMaxPct: 90, isBurnBasis: true, notes: "BOM·금형·시제품 30%+ — 양산 전환이 분수령"),
        "robotics-physical-ai": .init(materialsPctRange: 25...40, laborPctRange: 40...55, rentPctRange: 5...10, utilitiesPctRange: 3...8, sgaPctRange: 5...10, marketingPctRange: 2...6, otherPctRange: 3...8, marginPctRange: 35...55, primeMaxPct: 95, isBurnBasis: true, notes: "센서·액추에이터 부품과 시뮬레이션 GPU 비용"),
        "semiconductor": .init(materialsPctRange: 40...60, laborPctRange: 25...40, rentPctRange: 3...8, utilitiesPctRange: 3...7, sgaPctRange: 5...10, marketingPctRange: 1...4, otherPctRange: 3...8, marginPctRange: 40...60, primeMaxPct: 95, isBurnBasis: true, notes: "MPW 1회당 수억 — 모두의 챌린지 등 정부 매칭 의존"),
        "biotech-medtech": .init(materialsPctRange: 20...35, laborPctRange: 35...50, rentPctRange: 5...12, utilitiesPctRange: 3...7, sgaPctRange: 10...15, marketingPctRange: 2...6, otherPctRange: 5...12, marginPctRange: 40...65, primeMaxPct: 85, isBurnBasis: true, notes: "전임상·임상 단계별 자금 필요, IP·라이선스 큼"),
        "climate-energy": .init(materialsPctRange: 20...35, laborPctRange: 35...50, rentPctRange: 5...12, utilitiesPctRange: 3...7, sgaPctRange: 8...12, marketingPctRange: 3...8, otherPctRange: 5...10, marginPctRange: 45...65, primeMaxPct: 85, isBurnBasis: true, notes: "측정 장비·인증·실증사업 비용, 정부 R&D 매칭"),
    ]
}
