"use client";

import { useState } from "react";
import { useDashboardCtx } from "../../../contexts/DashboardContext";

// 2026-07-15 보안(XSS): PDF 출력은 window.open("")+document.write 로 같은 origin(about:blank)
//   문서를 만든다. bpSummary/bpSections 는 LLM 이 사장님 자유입력을 반영해 생성 → 이스케이프 없이
//   HTML 에 넣으면 &lt;img onerror&gt; 등이 실행되어 localStorage 의 세션 토큰이 탈취될 수 있다.
function escapeHtml(s: string): string {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#39;");
}

export function BusinessPlanCard() {
  const d = useDashboardCtx();
  const ko = d.language === "ko";
  const decisions = d.decisions;
  const savedBp = (decisions["fundraising-readiness"] as Record<string, unknown>)?.inputs as Record<string, unknown> | undefined;
  const sections = savedBp?.bpSections as Array<{ title: string; content: string }> | undefined;
  const summary = savedBp?.bpSummary as string | undefined;
  const savedAt = savedBp?.bpSavedAt as string | undefined;

  const [expandedIdx, setExpandedIdx] = useState<number | null>(null);

  if (!sections || sections.length === 0) return null;

  const handlePrint = () => {
    const printWindow = window.open("", "_blank");
    if (!printWindow) return;
    const date = new Date().toLocaleDateString(ko ? "ko-KR" : "en-US");
    const html = `<!DOCTYPE html><html><head><meta charset="utf-8"><title>${ko ? "사업계획서" : "Business Plan"} - Found.One</title>
<style>
  @page { margin: 20mm 18mm; size: A4; }
  body { font-family: -apple-system, BlinkMacSystemFont, "Apple SD Gothic Neo", "Malgun Gothic", sans-serif; color: #1a1a1a; line-height: 1.7; font-size: 11pt; }
  .header { border-bottom: 2px solid #1d3557; padding-bottom: 12px; margin-bottom: 24px; }
  .header h1 { font-size: 18pt; color: #1d3557; margin: 0 0 4px; }
  .header .meta { font-size: 9pt; color: #888; }
  .section { margin-bottom: 20px; page-break-inside: avoid; }
  .section h2 { font-size: 13pt; color: #1d3557; margin: 0 0 8px; padding-bottom: 4px; border-bottom: 1px solid #e5e7eb; }
  .section p { margin: 0; white-space: pre-wrap; font-size: 10.5pt; color: #333; }
  .footer { position: fixed; bottom: 0; left: 0; right: 0; text-align: center; font-size: 8pt; color: #aaa; border-top: 1px solid #eee; padding-top: 4px; }
</style></head><body>
<div class="header">
  <h1>${escapeHtml(summary || (ko ? "사업계획서" : "Business Plan"))}</h1>
  <div class="meta">Generated by Found.One · ${date}</div>
</div>
${sections.map(s => `<div class="section"><h2>${escapeHtml(s.title)}</h2><p>${escapeHtml(s.content)}</p></div>`).join("")}
<div class="footer">Found.One · ${ko ? "AI 사업계획서" : "AI Business Plan"}</div>
</body></html>`;
    printWindow.document.write(html);
    printWindow.document.close();
    setTimeout(() => printWindow.print(), 300);
  };

  return (
    <article style={{
      ...({ padding: "0", overflow: "hidden", gap: "0", borderRadius: "24px", border: "1px solid rgba(29,53,87,0.08)", background: "linear-gradient(180deg, rgba(255,255,255,0.95) 0%, rgba(29,53,87,0.02) 100%)" }),
    }}>
      <div style={{ padding: "18px 22px 14px", borderBottom: "0.5px solid rgba(0,0,0,0.06)" }}>
        <div style={{ display: "flex", alignItems: "center", gap: "10px", marginBottom: "4px" }}>
          <div style={{ width: 32, height: 32, borderRadius: 10, background: "linear-gradient(135deg, var(--primary), rgba(117,163,255,0.9))", display: "flex", alignItems: "center", justifyContent: "center" }}>
            <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="#fff" strokeWidth="1.8" strokeLinecap="round"><path d="M14 2H6a2 2 0 00-2 2v16a2 2 0 002 2h12a2 2 0 002-2V8z"/><polyline points="14,2 14,8 20,8"/></svg>
          </div>
          <div style={{ flex: 1 }}>
            <div style={{ fontSize: "15px", fontWeight: 700, letterSpacing: "-0.02em" }}>{ko ? "AI 사업계획서" : "AI Business Plan"}</div>
            <div style={{ fontSize: "11px", color: "var(--muted)" }}>
              {ko ? "PSST 프레임워크" : "PSST Framework"}
              {savedAt && ` · ${new Date(savedAt).toLocaleDateString(ko ? "ko-KR" : "en-US")}`}
            </div>
          </div>
          <button type="button" onClick={handlePrint} style={{
            padding: "6px 14px", borderRadius: "8px", border: "none",
            background: "var(--primary)", color: "#fff", fontSize: "12px", fontWeight: 600, cursor: "pointer",
            display: "flex", alignItems: "center", gap: "4px",
          }}>
            <svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round"><path d="M21 15v4a2 2 0 01-2 2H5a2 2 0 01-2-2v-4"/><polyline points="7 10 12 15 17 10"/><line x1="12" y1="15" x2="12" y2="3"/></svg>
            PDF
          </button>
        </div>
        {summary && (
          <div style={{ fontSize: "13px", color: "rgba(15,23,42,0.6)", lineHeight: 1.5, marginTop: "6px" }}>{summary}</div>
        )}
      </div>

      <div style={{ padding: "8px 22px 16px" }}>
        {sections.map((sec, idx) => {
          const expanded = expandedIdx === idx;
          return (
            <div key={idx} style={{ borderBottom: idx < sections.length - 1 ? "0.5px solid rgba(0,0,0,0.04)" : "none" }}>
              <button type="button" onClick={() => setExpandedIdx(expanded ? null : idx)} style={{
                width: "100%", padding: "10px 0", border: "none", background: "transparent",
                display: "flex", justifyContent: "space-between", alignItems: "center",
                cursor: "pointer", textAlign: "left",
              }}>
                <span style={{ fontSize: "13px", fontWeight: 600, color: "#0f172a" }}>{sec.title}</span>
                <span style={{ fontSize: "12px", color: "var(--muted)", transform: expanded ? "rotate(90deg)" : "none", transition: "transform 0.2s" }}>›</span>
              </button>
              {expanded && (
                <div style={{ padding: "0 0 12px", fontSize: "12px", lineHeight: 1.7, color: "var(--muted)", whiteSpace: "pre-line" }}>
                  {sec.content}
                </div>
              )}
            </div>
          );
        })}
      </div>
    </article>
  );
}
