insert into public.market_location_signals (
  region_key,
  region_name,
  district_name,
  category_id,
  search_keywords,
  market_style,
  rent_band,
  competition_level,
  demand_level,
  access_level,
  category_fit_level,
  base_score,
  summary,
  evidence,
  freshness_status,
  last_checked_at,
  next_review_at,
  notes
)
values
  -- ─── 홍대/상수/합정 권역 ───
  (
    'hongdae-cafe',
    '홍대',
    '마포구',
    'cafe-dessert',
    array['홍대', '홍대입구', '홍익대'],
    'destination',
    'high',
    'high',
    'high',
    'strong',
    'strong',
    85,
    '브랜드형 카페와 감도 높은 디저트 업종이 강하게 집중된 대표 목적 방문 상권입니다.',
    '{"reasons":["20대 목적 방문 수요가 매우 강함","SNS 확산 효과가 크고 브랜드 인지도 빠르게 형성됨"],"warnings":["임대료 상승 지속 중","경쟁 포화 상태로 차별화가 필수"]}'::jsonb,
    'fresh',
    '2026-03-19T09:00:00+09:00',
    '2026-03-26T09:00:00+09:00',
    null
  ),
  (
    'hongdae-retail',
    '홍대',
    '마포구',
    'retail',
    array['홍대', '홍대입구', '홍익대'],
    'destination',
    'high',
    'high',
    'high',
    'strong',
    'strong',
    83,
    '발견형 소비와 브랜드 노출이 강해 소매와 팝업형 소매에 잘 맞는 상권입니다.',
    '{"reasons":["브랜드 발견형 유입이 활발함","팝업·체험형 매장과 높은 궁합"],"warnings":["임대료가 빠르게 오르고 있음","주말 집중이 심해 평일 수익 관리 필요"]}'::jsonb,
    'fresh',
    '2026-03-19T09:00:00+09:00',
    '2026-03-26T09:00:00+09:00',
    null
  ),
  (
    'hongdae-beauty',
    '홍대',
    '마포구',
    'beauty',
    array['홍대', '홍대입구', '홍익대'],
    'destination',
    'high',
    'high',
    'high',
    'strong',
    'strong',
    82,
    '뷰티 수요와 검색 유입이 강하고 젊은 층 타깃 시술·관리 업종에 잘 맞는 상권입니다.',
    '{"reasons":["20대 뷰티 소비 밀도가 높음","SNS 예약 기반 수요가 활발함"],"warnings":["경쟁 과열 상태로 포지셔닝 필수","임대료 부담이 큼"]}'::jsonb,
    'fresh',
    '2026-03-19T09:00:00+09:00',
    '2026-03-26T09:00:00+09:00',
    null
  ),
  (
    'sangsu-cafe',
    '상수동',
    '마포구',
    'cafe-dessert',
    array['상수', '상수동', '상수역'],
    'destination',
    'mid-high',
    'mid-high',
    'high',
    'strong',
    'strong',
    83,
    '홍대 인근이면서 임대료 부담이 상대적으로 낮고 브랜드 감도가 높은 카페 상권입니다.',
    '{"reasons":["홍대 수요를 받으면서 임대료는 낮은 편","감도 높은 로컬 카페 분위기"],"warnings":["상권 성숙도 따라 임대료 상승 추이 확인 필요"]}'::jsonb,
    'fresh',
    '2026-03-19T09:00:00+09:00',
    '2026-03-26T09:00:00+09:00',
    null
  ),
  (
    'hapjeong-food',
    '합정',
    '마포구',
    'food',
    array['합정', '합정역', '망원'],
    'destination',
    'mid-high',
    'mid-high',
    'high',
    'strong',
    'mid-high',
    80,
    '주거와 유흥 수요가 혼합된 상권으로 저녁형 외식과 개성 있는 콘셉트 식당에 잘 맞습니다.',
    '{"reasons":["저녁 외식 수요가 강함","합정·망원 생활권 반복 방문 가능"],"warnings":["점심 수요는 상대적으로 약함","경쟁 증가 추이 확인 필요"]}'::jsonb,
    'review_soon',
    '2026-03-18T09:00:00+09:00',
    '2026-03-25T09:00:00+09:00',
    null
  ),
  -- ─── 이태원/한남 권역 ───
  (
    'itaewon-retail',
    '이태원',
    '용산구',
    'retail',
    array['이태원', '이태원역', '경리단길'],
    'destination',
    'mid-high',
    'mid-high',
    'high',
    'strong',
    'strong',
    81,
    '외국인 수요와 목적 방문형 소비가 혼재해 글로벌 감도 소매와 편집숍에 유리한 상권입니다.',
    '{"reasons":["외국인 유입 비중이 높음","브랜드 실험과 팝업형 소매에 적합"],"warnings":["상권 변동성이 크고 계절 편차 있음","입지별 격차가 뚜렷함"]}'::jsonb,
    'review_soon',
    '2026-03-17T09:00:00+09:00',
    '2026-03-24T09:00:00+09:00',
    null
  ),
  (
    'itaewon-space',
    '이태원',
    '용산구',
    'space',
    array['이태원', '이태원역', '경리단길'],
    'destination',
    'high',
    'mid-high',
    'high',
    'strong',
    'strong',
    80,
    '외국인 관광객과 국내 목적 방문 수요가 함께 있어 공간·숙박형 업종 검토에 적합한 상권입니다.',
    '{"reasons":["외국인 관광 수요가 꾸준함","공간 경험 콘셉트와 높은 궁합"],"warnings":["운영 인력 확보 어려움","계절 편차와 상권 변동성 주의"]}'::jsonb,
    'review_soon',
    '2026-03-17T09:00:00+09:00',
    '2026-03-24T09:00:00+09:00',
    null
  ),
  (
    'hannam-cafe',
    '한남동',
    '용산구',
    'cafe-dessert',
    array['한남', '한남동', '한강진'],
    'destination',
    'high',
    'high',
    'high',
    'strong',
    'strong',
    86,
    '고소득 고객층 수요와 브랜드 감도가 높아 프리미엄 카페와 디저트 업종에 강한 상권입니다.',
    '{"reasons":["고소득 목적 방문 수요가 강함","브랜드 포지셔닝 효과가 큼"],"warnings":["임대료가 매우 높고 상승 중","브랜드 없이 진입 시 리스크 큼"]}'::jsonb,
    'fresh',
    '2026-03-19T09:00:00+09:00',
    '2026-03-26T09:00:00+09:00',
    null
  ),
  (
    'hannam-retail',
    '한남동',
    '용산구',
    'retail',
    array['한남', '한남동', '한강진'],
    'destination',
    'high',
    'high',
    'high',
    'strong',
    'strong',
    85,
    '프리미엄 소매와 브랜드 쇼룸형 매장이 잘 정착하는 고급 목적 방문 상권입니다.',
    '{"reasons":["고소득 소비층 유입이 안정적","쇼룸·편집숍과 높은 궁합"],"warnings":["초기 임대료와 인테리어 비용이 매우 높음","브랜드력 없이는 어려운 상권"]}'::jsonb,
    'fresh',
    '2026-03-19T09:00:00+09:00',
    '2026-03-26T09:00:00+09:00',
    null
  ),
  -- ─── 청담/압구정 권역 ───
  (
    'cheongdam-beauty',
    '청담',
    '강남구',
    'beauty',
    array['청담', '청담동', '청담역'],
    'destination',
    'high',
    'high',
    'high',
    'strong',
    'strong',
    88,
    '국내 최고 수준의 프리미엄 뷰티·시술 수요가 집중된 플래그십 뷰티 상권입니다.',
    '{"reasons":["고가 시술 수요와 구매력이 매우 높음","뷰티 브랜드 플래그십에 최적"],"warnings":["임대료와 초기 투자 비용이 매우 높음","브랜드 포지셔닝 없이 진입 불가"]}'::jsonb,
    'fresh',
    '2026-03-19T09:00:00+09:00',
    '2026-03-26T09:00:00+09:00',
    null
  ),
  (
    'apgujeong-beauty',
    '압구정',
    '강남구',
    'beauty',
    array['압구정', '압구정역', '압구정로데오'],
    'destination',
    'high',
    'high',
    'high',
    'strong',
    'strong',
    86,
    '성형·피부·네일 등 뷰티 전반에 걸쳐 고소비 수요가 안정적인 프리미엄 상권입니다.',
    '{"reasons":["프리미엄 뷰티 수요가 꾸준함","예약 기반 반복 방문 구조 형성 가능"],"warnings":["임대료와 경쟁이 모두 높음","신규 진입 시 차별화 포인트 필수"]}'::jsonb,
    'fresh',
    '2026-03-19T09:00:00+09:00',
    '2026-03-26T09:00:00+09:00',
    null
  ),
  (
    'apgujeong-fitness',
    '압구정',
    '강남구',
    'fitness',
    array['압구정', '압구정역', '압구정로데오'],
    'destination',
    'high',
    'high',
    'high',
    'strong',
    'strong',
    85,
    '프리미엄 PT와 스튜디오 피트니스 수요가 높고 고소득 회원을 모으기 좋은 상권입니다.',
    '{"reasons":["고소득 피트니스 수요가 풍부함","프리미엄 멤버십 가격대 수용 가능"],"warnings":["시설 투자와 임대료가 동시에 높음","인력 확보와 유지가 어려움"]}'::jsonb,
    'fresh',
    '2026-03-19T09:00:00+09:00',
    '2026-03-26T09:00:00+09:00',
    null
  ),
  -- ─── 건대/왕십리 권역 ───
  (
    'konkuk-cafe',
    '건대입구',
    '광진구',
    'cafe-dessert',
    array['건대', '건대입구', '건대입구역'],
    'destination',
    'mid-high',
    'high',
    'high',
    'strong',
    'strong',
    82,
    '대학가 목적 방문 수요와 저녁 유흥 수요가 함께 있어 카페·디저트에 잘 맞는 상권입니다.',
    '{"reasons":["20대 유입이 강하고 야간 수요도 있음","브랜드형 카페 실험에 적합"],"warnings":["임대료가 상승 중","주말 쏠림 현상 있음"]}'::jsonb,
    'fresh',
    '2026-03-19T09:00:00+09:00',
    '2026-03-26T09:00:00+09:00',
    null
  ),
  (
    'konkuk-food',
    '건대입구',
    '광진구',
    'food',
    array['건대', '건대입구', '건대입구역'],
    'destination',
    'mid-high',
    'high',
    'high',
    'strong',
    'mid-high',
    80,
    '대학가 외식 수요와 저녁 회식 수요가 함께 있어 다양한 외식 콘셉트를 시험하기 좋습니다.',
    '{"reasons":["저녁 외식 수요가 강함","다양한 가격대 소비자가 공존"],"warnings":["점심 수요는 상대적으로 약함","경쟁 밀도가 높음"]}'::jsonb,
    'fresh',
    '2026-03-19T09:00:00+09:00',
    '2026-03-26T09:00:00+09:00',
    null
  ),
  (
    'wangsimni-food',
    '왕십리',
    '성동구',
    'food',
    array['왕십리', '왕십리역'],
    'office',
    'mid-high',
    'mid-high',
    'high',
    'strong',
    'mid-high',
    79,
    '직장인과 대학가 수요가 혼합된 왕십리 상권은 점심·저녁 회전형 외식에 적합합니다.',
    '{"reasons":["점심과 저녁 수요가 모두 있음","환승역 유입으로 접근성이 좋음"],"warnings":["주말 수요가 약함","상권 내 입지별 편차가 있음"]}'::jsonb,
    'fresh',
    '2026-03-19T09:00:00+09:00',
    '2026-03-26T09:00:00+09:00',
    null
  ),
  -- ─── 마곡/가산 오피스 권역 ───
  (
    'magok-cafe',
    '마곡',
    '강서구',
    'cafe-dessert',
    array['마곡', '마곡역', '마곡나루'],
    'office',
    'mid-high',
    'mid',
    'high',
    'strong',
    'mid-high',
    78,
    '대규모 IT·제조 오피스 수요가 집중된 마곡은 테이크아웃형 카페 운영에 유리한 상권입니다.',
    '{"reasons":["출근·점심 테이크아웃 수요가 명확함","오피스 밀집으로 반복 방문 가능"],"warnings":["주말 수요가 거의 없음","상권 성숙까지 시간이 필요할 수 있음"]}'::jsonb,
    'fresh',
    '2026-03-19T09:00:00+09:00',
    '2026-03-26T09:00:00+09:00',
    null
  ),
  (
    'magok-food',
    '마곡',
    '강서구',
    'food',
    array['마곡', '마곡역', '마곡나루'],
    'office',
    'mid-high',
    'mid',
    'high',
    'strong',
    'strong',
    80,
    '점심 수요가 뚜렷한 오피스 상권으로 빠른 회전형 식사 모델에 안정적인 입지입니다.',
    '{"reasons":["점심 유입이 예측 가능함","오피스 직원 충성 고객 확보 가능"],"warnings":["주말 영업은 사실상 어려움","저녁 수요 확보에 추가 전략 필요"]}'::jsonb,
    'fresh',
    '2026-03-19T09:00:00+09:00',
    '2026-03-26T09:00:00+09:00',
    null
  ),
  (
    'gasan-food',
    '가산',
    '금천구',
    'food',
    array['가산', '가산디지털단지', '가산역'],
    'office',
    'mid',
    'mid-high',
    'high',
    'strong',
    'mid-high',
    77,
    '가산디지털단지 중심의 직장인 점심 수요가 강해 회전율 중심 외식 운영에 적합합니다.',
    '{"reasons":["점심 유입이 예측 가능하고 안정적","임대료가 강남 대비 낮아 비용 통제 유리"],"warnings":["주말 수요가 거의 없음","저녁과 야간 상권은 약함"]}'::jsonb,
    'fresh',
    '2026-03-19T09:00:00+09:00',
    '2026-03-26T09:00:00+09:00',
    null
  ),
  -- ─── 목동/노원 생활권 ───
  (
    'mokdong-fitness',
    '목동',
    '양천구',
    'fitness',
    array['목동', '오목교'],
    'residential',
    'mid-high',
    'mid',
    'mid',
    'balanced',
    'strong',
    80,
    '중산층 주거 수요가 강하고 피트니스·PT 스튜디오 반복 방문을 만들기 좋은 생활권입니다.',
    '{"reasons":["중산층 멤버십 수요가 안정적","가족 단위 건강 관심 높음"],"warnings":["고가 PT보다 합리적 가격대가 유리","경쟁 스튜디오 증가 추이 확인 필요"]}'::jsonb,
    'fresh',
    '2026-03-19T09:00:00+09:00',
    '2026-03-26T09:00:00+09:00',
    null
  ),
  (
    'mokdong-education',
    '목동',
    '양천구',
    'education',
    array['목동', '오목교'],
    'residential',
    'mid-high',
    'high',
    'high',
    'balanced',
    'strong',
    84,
    '전국 최고 수준의 교육열 기반 수요가 있어 학원·교육 업종에 강한 대표 주거 상권입니다.',
    '{"reasons":["학원 수요와 재등록률이 매우 높음","학부모 소비 여력이 충분함"],"warnings":["경쟁 학원 밀도가 높음","임대료가 교육 상권 치고는 높은 편"]}'::jsonb,
    'fresh',
    '2026-03-19T09:00:00+09:00',
    '2026-03-26T09:00:00+09:00',
    null
  ),
  (
    'mokdong-living',
    '목동',
    '양천구',
    'living-service',
    array['목동', '오목교'],
    'residential',
    'mid-high',
    'mid',
    'mid',
    'balanced',
    'strong',
    79,
    '중산층 가족 생활권으로 세탁·청소·수선 등 생활 밀착형 서비스 수요가 안정적입니다.',
    '{"reasons":["가족 단위 반복 수요가 꾸준함","생활 편의 서비스 수요가 안정적"],"warnings":["서비스 품질 관리가 재방문 핵심","마케팅 없이는 인지도 확보가 느림"]}'::jsonb,
    'fresh',
    '2026-03-19T09:00:00+09:00',
    '2026-03-26T09:00:00+09:00',
    null
  ),
  (
    'nowon-education',
    '노원',
    '노원구',
    'education',
    array['노원', '노원역', '상계동'],
    'residential',
    'mid',
    'mid-high',
    'mid',
    'balanced',
    'strong',
    81,
    '교육 수요가 풍부하고 임대료가 상대적으로 낮아 초기 교육 업종 진입에 유리한 지역입니다.',
    '{"reasons":["학원 수요가 안정적","임대료가 낮아 수익 구조 만들기 유리"],"warnings":["브랜드 인지도 확보까지 시간 필요","소득 수준 기반 가격 조정 필요"]}'::jsonb,
    'fresh',
    '2026-03-19T09:00:00+09:00',
    '2026-03-26T09:00:00+09:00',
    null
  ),
  (
    'nowon-pet',
    '노원',
    '노원구',
    'pet',
    array['노원', '노원역', '상계동'],
    'residential',
    'mid',
    'mid-low',
    'mid',
    'balanced',
    'strong',
    78,
    '주거 밀집 지역으로 반려동물 미용·호텔·용품 수요가 꾸준히 있는 생활권 상권입니다.',
    '{"reasons":["반복 방문 수요를 만들기 좋음","경쟁 강도가 낮아 초기 정착 유리"],"warnings":["객단가 한계로 수익 확장이 느릴 수 있음"]}'::jsonb,
    'fresh',
    '2026-03-18T09:00:00+09:00',
    '2026-03-25T09:00:00+09:00',
    null
  ),
  (
    'nowon-living',
    '노원',
    '노원구',
    'living-service',
    array['노원', '노원역', '상계동'],
    'residential',
    'mid',
    'mid-low',
    'mid',
    'balanced',
    'strong',
    77,
    '임대료가 낮고 반복 방문 수요가 안정적인 생활 서비스 진입에 적합한 주거 상권입니다.',
    '{"reasons":["진입 비용이 낮아 초기 부담 적음","생활권 밀착 수요가 꾸준함"],"warnings":["객단가 상한이 있어 고가 서비스 운영은 어려움"]}'::jsonb,
    'fresh',
    '2026-03-18T09:00:00+09:00',
    '2026-03-25T09:00:00+09:00',
    null
  ),
  -- ─── 북촌/서촌 권역 ───
  (
    'bukchon-cafe',
    '북촌',
    '종로구',
    'cafe-dessert',
    array['북촌', '북촌로', '가회동'],
    'destination',
    'mid-high',
    'mid-high',
    'high',
    'balanced',
    'strong',
    82,
    '관광객과 감도 높은 국내 방문객이 혼재하는 한옥 분위기 카페 상권입니다.',
    '{"reasons":["관광 수요와 목적 방문이 강함","한옥 감성과 브랜드 스토리가 잘 붙음"],"warnings":["주중과 주말 수요 편차가 큼","입지별 유입 차이가 뚜렷함"]}'::jsonb,
    'review_soon',
    '2026-03-17T09:00:00+09:00',
    '2026-03-24T09:00:00+09:00',
    null
  ),
  (
    'seochon-cafe',
    '서촌',
    '종로구',
    'cafe-dessert',
    array['서촌', '경복궁역', '통인시장'],
    'destination',
    'mid-high',
    'mid-high',
    'high',
    'balanced',
    'strong',
    81,
    '로컬 감성과 관광 수요가 혼재해 독립 카페와 브랜드 감도 높은 디저트 업종에 잘 맞습니다.',
    '{"reasons":["관광객과 동네 단골이 공존","골목 카페 감성과 브랜드 스토리가 잘 맞음"],"warnings":["대로 기준 유입이 약한 골목은 발견이 어려움","계절 편차 있음"]}'::jsonb,
    'review_soon',
    '2026-03-16T09:00:00+09:00',
    '2026-03-23T09:00:00+09:00',
    null
  ),
  -- ─── 강남 외식 / 송파 피트니스 ───
  (
    'gangnam-food',
    '강남',
    '강남구',
    'food',
    array['강남', '강남역', '신논현'],
    'office',
    'high',
    'high',
    'high',
    'strong',
    'strong',
    83,
    '점심·저녁 직장인 수요가 매우 강해 회전율 중심 외식 운영에 유리하지만 고정비 부담도 큰 상권입니다.',
    '{"reasons":["점심·저녁 회전 수요가 매우 안정적","직장인 단체 식사 수요도 있음"],"warnings":["임대료와 경쟁이 모두 높음","원가 통제 없이는 수익 확보 어려움"]}'::jsonb,
    'fresh',
    '2026-03-19T09:00:00+09:00',
    '2026-03-26T09:00:00+09:00',
    null
  ),
  (
    'songpa-fitness',
    '잠실',
    '송파구',
    'fitness',
    array['잠실', '잠실역', '올림픽공원'],
    'residential',
    'mid-high',
    'mid-high',
    'mid',
    'strong',
    'strong',
    81,
    '주거 수요와 올림픽공원 인근 건강 관심 수요가 맞닿아 피트니스·스튜디오 운영에 적합합니다.',
    '{"reasons":["가족 단위 건강 수요가 안정적","올림픽공원 인근으로 활동 인구 존재"],"warnings":["고가 PT보다 합리적 가격대가 경쟁력 있음","경쟁 스튜디오 확인 필요"]}'::jsonb,
    'fresh',
    '2026-03-19T09:00:00+09:00',
    '2026-03-26T09:00:00+09:00',
    null
  ),
  -- ─── 지방 주요 상권 ───
  (
    'jeju-cafe',
    '제주',
    '제주시',
    'cafe-dessert',
    array['제주', '제주시', '제주도'],
    'destination',
    'mid-high',
    'high',
    'high',
    'balanced',
    'strong',
    82,
    '관광 수요와 SNS 확산 효과가 강해 비주얼·브랜드형 카페 창업에 잘 맞는 상권입니다.',
    '{"reasons":["관광객 목적 방문 수요가 매우 강함","SNS 확산 효과가 빠름"],"warnings":["성수기·비성수기 매출 편차가 매우 큼","임대료가 지방 기준으로는 높은 편"]}'::jsonb,
    'review_soon',
    '2026-03-17T09:00:00+09:00',
    '2026-03-24T09:00:00+09:00',
    '비성수기 운영 전략 별도 수립 권장'
  ),
  (
    'jeju-space',
    '제주',
    '제주시',
    'space',
    array['제주', '제주시', '제주도'],
    'destination',
    'mid-high',
    'mid-high',
    'high',
    'balanced',
    'strong',
    81,
    '관광 수요 기반의 숙박·공유 공간 수요가 강해 공간형 업종 검토에 적합한 상권입니다.',
    '{"reasons":["관광 수요가 꾸준하고 숙박 니즈가 명확함","독립 숙소·감성 공간 콘셉트에 유리"],"warnings":["비성수기 공실 리스크가 큼","플랫폼 수수료와 운영비 함께 계산 필요"]}'::jsonb,
    'review_soon',
    '2026-03-17T09:00:00+09:00',
    '2026-03-24T09:00:00+09:00',
    '계절 편차 데이터 재확인 권장'
  ),
  (
    'daejeon-food',
    '대전 은행동',
    '대전시',
    'food',
    array['대전', '은행동', '대전역'],
    'destination',
    'mid',
    'mid-high',
    'mid',
    'balanced',
    'mid-high',
    76,
    '대전 중심 상권으로 저녁 외식과 주말 목적 방문 수요가 있어 외식 창업 검토가 가능합니다.',
    '{"reasons":["충청권 중심지로 유입이 안정적","임대료가 서울 대비 낮아 수익 구조 유리"],"warnings":["서울보다 상권 성장 속도가 느림","브랜드 확산은 지역 특성 고려 필요"]}'::jsonb,
    'fresh',
    '2026-03-18T09:00:00+09:00',
    '2026-03-25T09:00:00+09:00',
    null
  ),
  (
    'daejeon-cafe',
    '대전 둔산',
    '대전시',
    'cafe-dessert',
    array['대전', '둔산', '갤러리아'],
    'destination',
    'mid',
    'mid-high',
    'mid',
    'balanced',
    'mid-high',
    75,
    '중산층 주거와 상업이 혼합된 둔산 지역은 대전 내 카페 수요가 가장 안정적인 지역입니다.',
    '{"reasons":["중산층 소비 기반이 안정적","프랜차이즈와 독립 카페 공존 상권"],"warnings":["경쟁이 점점 심화되는 추이","프리미엄 포지셔닝 시 수요 검증 필요"]}'::jsonb,
    'fresh',
    '2026-03-18T09:00:00+09:00',
    '2026-03-25T09:00:00+09:00',
    null
  ),
  (
    'daegu-retail',
    '동성로',
    '대구시',
    'retail',
    array['동성로', '대구', '중앙로'],
    'destination',
    'mid-high',
    'high',
    'high',
    'strong',
    'strong',
    78,
    '대구 최대 번화가로 발견형 소비와 브랜드 노출 수요가 강한 소매 상권입니다.',
    '{"reasons":["영남권 최대 상권으로 유입이 강함","브랜드 노출과 발견형 소비에 유리"],"warnings":["임대료가 지방 기준으로 높음","온라인 쇼핑 전환 영향 확인 필요"]}'::jsonb,
    'review_soon',
    '2026-03-17T09:00:00+09:00',
    '2026-03-24T09:00:00+09:00',
    null
  ),
  (
    'gwangju-food',
    '충장로',
    '광주시',
    'food',
    array['충장로', '광주', '금남로'],
    'destination',
    'mid',
    'mid-high',
    'mid',
    'balanced',
    'mid-high',
    75,
    '광주 중심 상권으로 외식 수요가 꾸준하고 임대료가 낮아 초기 운영 부담이 적습니다.',
    '{"reasons":["호남권 중심 상권으로 유입 안정적","임대료가 낮아 초기 비용 통제 유리"],"warnings":["성장 속도가 수도권보다 느림","브랜드 확산 전략이 다르게 필요"]}'::jsonb,
    'fresh',
    '2026-03-18T09:00:00+09:00',
    '2026-03-25T09:00:00+09:00',
    null
  ),
  (
    'cheonan-living',
    '천안',
    '천안시',
    'living-service',
    array['천안', '천안역', '두정동'],
    'residential',
    'mid-low',
    'mid-low',
    'mid',
    'balanced',
    'strong',
    76,
    '수도권 접근성이 좋고 주거 수요가 안정적인 천안은 생활 서비스 업종에 진입하기 좋은 지역입니다.',
    '{"reasons":["서울 접근 가능하고 임대료가 낮음","생활권 반복 수요가 꾸준함"],"warnings":["브랜드 인지도 확보가 느릴 수 있음","상권 성장 속도 확인 필요"]}'::jsonb,
    'fresh',
    '2026-03-18T09:00:00+09:00',
    '2026-03-25T09:00:00+09:00',
    null
  )
on conflict (region_key) do update
set
  region_name = excluded.region_name,
  district_name = excluded.district_name,
  category_id = excluded.category_id,
  search_keywords = excluded.search_keywords,
  market_style = excluded.market_style,
  rent_band = excluded.rent_band,
  competition_level = excluded.competition_level,
  demand_level = excluded.demand_level,
  access_level = excluded.access_level,
  category_fit_level = excluded.category_fit_level,
  base_score = excluded.base_score,
  summary = excluded.summary,
  evidence = excluded.evidence,
  freshness_status = excluded.freshness_status,
  last_checked_at = excluded.last_checked_at,
  next_review_at = excluded.next_review_at,
  notes = excluded.notes,
  is_active = true,
  updated_at = now();
