-- Seed real commercial sub-area data for residential districts
-- Covers: 노원구, 관악구, 강서구, 도봉구/강북구, 성북구, 양천구, 구로구, 동작구, 은평구, 수도권 주요 상권

insert into public.market_location_signals (
  region_key,
  region_name,
  district_name,
  category_id,
  search_keywords,
  market_style,
  rent_band,
  competition_level,
  demand_level,
  access_level,
  category_fit_level,
  base_score,
  summary,
  evidence,
  freshness_status,
  last_checked_at,
  next_review_at,
  notes
)
values

  -- ─── 노원구 ───
  (
    'nowon-station-general',
    '노원역 상권',
    '노원구',
    null,
    array['노원', '노원구', '노원역', '상계동'],
    'office',
    'mid-high',
    'high',
    'high',
    'strong',
    'strong',
    88,
    '서울 북동부 최대 역세권 상권으로 하루 유동인구 10만 이상입니다. 먹자골목과 판매 수요가 모두 강합니다.',
    '{"reasons":["지하철 4·7호선 환승역으로 유입이 안정적","노원구 최대 소비 집결지","다양한 연령대 유동인구"],"warnings":["역 직접 주변 임대료는 빠르게 상승 중","상가 경쟁도가 높음"]}'::jsonb,
    'fresh',
    '2026-03-01',
    '2026-09-01',
    null
  ),
  (
    'junggye-dong-general',
    '중계동 은행사거리',
    '노원구',
    null,
    array['노원구', '중계동', '중계역', '은행사거리', '학원가'],
    'residential',
    'mid',
    'mid',
    'mid-high',
    'mid-high',
    'strong',
    82,
    '노원구 내 학원가 중심의 반복 방문 수요가 강한 생활 상권입니다. 초·중·고 학부모 소비가 안정적입니다.',
    '{"reasons":["대치동 학원가 다음으로 학원 밀집도 높음","주거 밀집으로 반복 방문 고객 확보에 유리","임대료 대비 수익성 좋음"],"warnings":["저녁·주말 수요 비중 확인 필요","세대 수요 다양성이 낮음"]}'::jsonb,
    'fresh',
    '2026-03-01',
    '2026-09-01',
    null
  ),
  (
    'hagye-station-general',
    '하계역 상권',
    '노원구',
    null,
    array['노원구', '하계동', '하계역', '하계'],
    'residential',
    'mid',
    'mid',
    'mid',
    'mid-high',
    'mid-high',
    75,
    '노원구 내 경쟁도가 낮고 임대료가 저렴한 편입니다. 아파트 단지 배후 수요를 안정적으로 확보할 수 있습니다.',
    '{"reasons":["경쟁 대비 고정비 부담이 낮음","인근 대단지 아파트 반복 방문 수요"],"warnings":["상권 범위가 좁아 유동인구 규모 제한적","성장성 확인 필요"]}'::jsonb,
    'fresh',
    '2026-03-01',
    '2026-09-01',
    null
  ),
  (
    'gongreung-general',
    '공릉동 먹자골목',
    '노원구',
    null,
    array['노원구', '공릉동', '공릉', '서울과기대', '육사'],
    'destination',
    'low',
    'mid',
    'mid-high',
    'mid',
    'strong',
    78,
    '서울과학기술대와 육군사관학교 인접 상권으로 젊은 층 소비가 집중됩니다. 임대료가 낮아 초기 창업 비용 부담이 적습니다.',
    '{"reasons":["대학가 특수 수요로 점심·저녁 고정 매출","임대료가 서울 평균 대비 낮은 편","경쟁 밀도 낮아 신규 진입 가능"],"warnings":["방학 기간 매출 급락 가능성","배후 거주 인구 한계"]}'::jsonb,
    'fresh',
    '2026-03-01',
    '2026-09-01',
    null
  ),

  -- ─── 관악구 ───
  (
    'sillim-station-general',
    '신림역 상권',
    '관악구',
    null,
    array['관악구', '신림', '신림역', '신림동'],
    'residential',
    'mid',
    'high',
    'high',
    'strong',
    'strong',
    85,
    '서울 남부 최대 주거 밀집 상권 중 하나입니다. 1인 가구와 고시촌 수요로 가성비 업종 중심의 방문 빈도가 높습니다.',
    '{"reasons":["인구 밀도가 매우 높아 고정 수요 안정적","1인 가구 비중 높아 배달·포장 수요 강함","지하철 2호선 접근성 탁월"],"warnings":["가격 민감도가 높은 수요층","경쟁 밀도가 높아 차별화 전략 필요"]}'::jsonb,
    'fresh',
    '2026-03-01',
    '2026-09-01',
    null
  ),
  (
    'snu-station-general',
    '서울대입구역 상권',
    '관악구',
    null,
    array['관악구', '서울대입구', '서울대입구역', '샤로수길', '낙성대'],
    'destination',
    'mid-high',
    'mid-high',
    'high',
    'strong',
    'strong',
    87,
    '서울대 배후 수요와 샤로수길 트렌드 상권이 결합된 지역입니다. 젊은 층 취향을 반영한 감도 높은 업종에 유리합니다.',
    '{"reasons":["샤로수길 중심으로 트렌디한 수요 증가","대학·병원·연구소 직장인 복합 수요","미디어 노출로 외부 방문객 유입"],"warnings":["임대료가 빠르게 오르는 추세","계절적 수요 변동 있음"]}'::jsonb,
    'fresh',
    '2026-03-01',
    '2026-09-01',
    null
  ),
  (
    'bongcheon-general',
    '봉천동 상권',
    '관악구',
    null,
    array['관악구', '봉천동', '봉천', '서울대벤처타운'],
    'residential',
    'low',
    'mid',
    'mid',
    'mid',
    'mid-high',
    74,
    '관악구 내 임대료가 낮고 주거 배후 수요가 탄탄한 생활 상권입니다. 초기 창업 비용을 최소화하려는 경우 적합합니다.',
    '{"reasons":["서울 기준 임대료 낮은 편","반복 방문 주거 수요","경쟁 밀도 상대적으로 낮음"],"warnings":["외부 유동인구 적음","비주거 수요 약함"]}'::jsonb,
    'fresh',
    '2026-03-01',
    '2026-09-01',
    null
  ),

  -- ─── 강서구 ───
  (
    'balsan-station-general',
    '발산역 상권',
    '강서구',
    null,
    array['강서구', '발산', '발산역', '마곡', '마곡나루'],
    'office',
    'mid-high',
    'mid-high',
    'high',
    'strong',
    'strong',
    88,
    '마곡 산업단지 개발로 직장인 수요가 급증한 신흥 상권입니다. LG·코오롱 등 대기업 임직원 소비력이 높습니다.',
    '{"reasons":["마곡 입주 기업 직장인 점심·저녁 수요 급증","서울 서남권 최대 산업단지 배후","지하철 5·9호선 접근성 우수"],"warnings":["주말 수요가 평일 대비 낮음","신규 상가 공급 과잉 우려"]}'::jsonb,
    'fresh',
    '2026-03-01',
    '2026-09-01',
    null
  ),
  (
    'hwagok-general',
    '화곡역 상권',
    '강서구',
    null,
    array['강서구', '화곡', '화곡역', '화곡동'],
    'residential',
    'mid',
    'mid',
    'mid-high',
    'mid-high',
    'strong',
    80,
    '강서구 구도심 핵심 상권으로 주거 배후 수요가 안정적입니다. 서울 서부권에서 임대료 대비 수익성이 좋은 지역입니다.',
    '{"reasons":["강서구 인구 밀집 지역","반복 방문 생활 수요 강함","임대료 대비 매출 안정성 높음"],"warnings":["유동 인구 규모는 역세권 대비 제한적","세대 교체 속도가 느린 상권"]}'::jsonb,
    'fresh',
    '2026-03-01',
    '2026-09-01',
    null
  ),
  (
    'gayang-general',
    '가양역 상권',
    '강서구',
    null,
    array['강서구', '가양', '가양역', '가양동'],
    'residential',
    'low',
    'mid',
    'mid',
    'mid-high',
    'mid-high',
    76,
    '강서구 서쪽 주거 상권으로 임대료가 낮고 대단지 아파트 배후 수요가 확보됩니다.',
    '{"reasons":["임대료가 서울 기준 낮은 편","대규모 아파트 단지 반복 방문 수요"],"warnings":["외부 유입 수요 제한적","상권 성장성 낮은 편"]}'::jsonb,
    'fresh',
    '2026-03-01',
    '2026-09-01',
    null
  ),

  -- ─── 도봉구·강북구 ───
  (
    'suyu-station-general',
    '수유역 상권',
    '강북구',
    null,
    array['강북구', '수유', '수유역', '수유동', '강북'],
    'residential',
    'mid',
    'mid-high',
    'high',
    'strong',
    'strong',
    83,
    '강북구 최대 역세권 상권으로 서울 북부권 중심 소비지입니다. 4호선 환승 유동인구가 꾸준합니다.',
    '{"reasons":["강북구 최대 교통 결절점","먹자골목 중심 외식 수요 강함","인근 미아사거리와 연계 상권"],"warnings":["고령화로 소비 트렌드 변화 느린 편","신규 브랜드 수용 속도 확인 필요"]}'::jsonb,
    'fresh',
    '2026-03-01',
    '2026-09-01',
    null
  ),
  (
    'changdong-general',
    '창동 상권',
    '도봉구',
    null,
    array['도봉구', '창동', '창동역', '쌍문', '노원', '창동 활성화'],
    'office',
    'mid',
    'mid',
    'mid-high',
    'strong',
    'mid-high',
    79,
    '서울 동북권 신경제 거점으로 개발 중인 지역입니다. 창동 플랫폼 개발과 함께 유동인구가 증가하고 있습니다.',
    '{"reasons":["창동 플랫폼 문화복합시설 개발로 유동인구 증가 중","지하철 1·4호선 더블 역세권","상대적으로 낮은 임대료"],"warnings":["개발 완료 전 수요 불확실성","현재 상권 규모는 제한적"]}'::jsonb,
    'fresh',
    '2026-03-01',
    '2026-09-01',
    null
  ),

  -- ─── 성북구 ───
  (
    'gireum-general',
    '길음역 상권',
    '성북구',
    null,
    array['성북구', '길음', '길음역', '길음동', '돈암'],
    'residential',
    'mid',
    'mid',
    'mid-high',
    'strong',
    'strong',
    81,
    '성북구와 강북구의 경계에 위치한 4호선 역세권 상권입니다. 주거 밀집으로 반복 방문 수요가 안정적입니다.',
    '{"reasons":["4호선 접근성으로 출퇴근 유동인구 확보","성북구 주거 배후 수요 안정적","임대료 적정 수준"],"warnings":["외부 유입 목적 방문은 적음","트렌드 수용 속도 느린 상권"]}'::jsonb,
    'fresh',
    '2026-03-01',
    '2026-09-01',
    null
  ),
  (
    'dongguk-univ-general',
    '성신여대입구 상권',
    '성북구',
    null,
    array['성북구', '성신여대', '성신여대입구', '돈암동', '한성대'],
    'destination',
    'mid-high',
    'mid-high',
    'high',
    'strong',
    'strong',
    84,
    '성신여대·한성대 배후 대학 상권으로 20대 여성 소비 트렌드에 민감한 지역입니다. 뷰티·카페 업종 수요가 강합니다.',
    '{"reasons":["대학생 중심 20대 소비 트렌드 수요","카페·뷰티·패션 업종 높은 수용성","지하철 4호선 접근성"],"warnings":["방학 시즌 수요 급락 가능성","임대료 상승 추세"]}'::jsonb,
    'fresh',
    '2026-03-01',
    '2026-09-01',
    null
  ),

  -- ─── 양천구·구로구 ───
  (
    'mokdong-general',
    '목동 오거리 상권',
    '양천구',
    null,
    array['양천구', '목동', '목동오거리', '목동역', '오목교'],
    'residential',
    'mid-high',
    'mid-high',
    'high',
    'strong',
    'strong',
    85,
    '중산층 주거 밀집 지역으로 가족 단위 외식 수요와 학원가 수요가 함께 형성된 안정 상권입니다.',
    '{"reasons":["교육열 높은 중산층 가족 수요로 소비력 높음","목동 신시가지 중심 상권 집결지","반복 방문 빈도 높음"],"warnings":["임대료가 강남 수준으로 높은 편","신규 브랜드 검증 기간 필요"]}'::jsonb,
    'fresh',
    '2026-03-01',
    '2026-09-01',
    null
  ),
  (
    'guro-digital-general',
    '구로디지털단지 상권',
    '구로구',
    null,
    array['구로구', '구로디지털단지', '구로디지털', 'G밸리', '가산'],
    'office',
    'mid',
    'high',
    'high',
    'strong',
    'strong',
    86,
    'G밸리(구로·가산 디지털단지) 직장인 평일 점심·저녁 수요가 압도적입니다. 입주 기업 20만 이상의 직장인 고정 수요.',
    '{"reasons":["평일 점심 수요 매우 강함","IT·제조업 직장인 소비 패턴 예측 가능","임대료 대비 매출 안정성 높음"],"warnings":["주말 수요가 평일의 20% 미만","저녁 상권 발달 수준 확인 필요"]}'::jsonb,
    'fresh',
    '2026-03-01',
    '2026-09-01',
    null
  ),

  -- ─── 동작구 ───
  (
    'sadang-general',
    '사당역 상권',
    '동작구',
    null,
    array['동작구', '사당', '사당역', '방배', '이수'],
    'office',
    'mid-high',
    'high',
    'high',
    'strong',
    'strong',
    87,
    '2·4호선 환승 역세권으로 서울 남부 최대 환승 상권 중 하나입니다. 출퇴근 유동인구가 풍부합니다.',
    '{"reasons":["하루 유동인구 상위권 역세권","남부권 최대 교통 결절점","외식·카페·미용 수요 복합"],"warnings":["역 직접 주변 임대료 높음","골목 안쪽과 역 앞 수요 격차 큼"]}'::jsonb,
    'fresh',
    '2026-03-01',
    '2026-09-01',
    null
  ),
  (
    'noryangjin-general',
    '노량진 상권',
    '동작구',
    null,
    array['동작구', '노량진', '노량진역', '노량진 고시촌'],
    'residential',
    'low',
    'high',
    'high',
    'strong',
    'mid-high',
    78,
    '고시촌 수요 중심으로 가성비 업종에 특화된 상권입니다. 임대료가 낮고 1인 가구 포장·배달 수요가 강합니다.',
    '{"reasons":["낮은 임대료로 초기 진입 유리","안정적 학습 인구 기반 수요","배달·포장 높은 수요"],"warnings":["소비력 한계","트렌디 업종 수용 어려움"]}'::jsonb,
    'fresh',
    '2026-03-01',
    '2026-09-01',
    null
  ),

  -- ─── 은평구 ───
  (
    'yeonsinnae-general',
    '연신내역 상권',
    '은평구',
    null,
    array['은평구', '연신내', '연신내역', '불광', '구파발'],
    'residential',
    'mid',
    'mid-high',
    'high',
    'strong',
    'strong',
    83,
    '은평구 최대 상권으로 3·6호선 환승 역세권입니다. 서울 서북부 생활 상권의 핵심 집결지입니다.',
    '{"reasons":["3·6호선 환승역 유동인구 풍부","은평구 최대 소비 집결지","먹자골목 외식 수요 강함"],"warnings":["임대료 상승 추세","핵심 구역과 주변부 수요 격차"]}'::jsonb,
    'fresh',
    '2026-03-01',
    '2026-09-01',
    null
  ),

  -- ─── 수원·경기 ───
  (
    'suwon-ingye-general',
    '수원 인계동 상권',
    '수원시 팔달구',
    null,
    array['수원', '수원시', '인계동', '인계', '수원 중심'],
    'destination',
    'mid',
    'mid-high',
    'high',
    'strong',
    'strong',
    84,
    '수원 최대 번화가로 경기 남부권 소비가 집결하는 핵심 상권입니다. 외식·쇼핑·미용 수요가 복합적으로 형성되어 있습니다.',
    '{"reasons":["수원 최대 유흥·외식 집결지","경기 남부 접근성 우수","다양한 소비층 혼재"],"warnings":["주차 접근성 확인 필요","경쟁도 높음"]}'::jsonb,
    'fresh',
    '2026-03-01',
    '2026-09-01',
    null
  ),
  (
    'suwon-station-general',
    '수원역 상권',
    '수원시 권선구',
    null,
    array['수원', '수원시', '수원역', '매산동', '매탄'],
    'office',
    'mid-high',
    'high',
    'high',
    'strong',
    'strong',
    85,
    '수원역 광역 환승 거점으로 유동인구 규모가 큰 상권입니다. 평일·주말 모두 안정적 수요를 기대할 수 있습니다.',
    '{"reasons":["KTX·GTX 연결로 광역 유동인구","수원 최대 교통 결절점","판매·외식 복합 수요"],"warnings":["역 직접 인접 임대료 높음","동탄 등 신도시 수요 분산 가능성"]}'::jsonb,
    'fresh',
    '2026-03-01',
    '2026-09-01',
    null
  ),
  (
    'bundang-jeongja-general',
    '정자역 상권',
    '성남시 분당구',
    null,
    array['분당', '분당구', '정자', '정자역', '성남', '판교'],
    'office',
    'high',
    'mid-high',
    'high',
    'strong',
    'strong',
    88,
    '판교 IT 클러스터와 분당 중산층 수요가 결합된 고소득 직장인 상권입니다. 소비력이 높고 트렌드 수용이 빠릅니다.',
    '{"reasons":["판교 IT 기업 직장인 높은 소비력","분당 중산층 주거 배후 수요","트렌디 업종 수용성 높음"],"warnings":["임대료가 높은 편","판교 역세권과 경쟁"]}'::jsonb,
    'fresh',
    '2026-03-01',
    '2026-09-01',
    null
  ),
  (
    'incheon-bupyeong-general',
    '부평역 상권',
    '인천시 부평구',
    null,
    array['인천', '부평', '부평역', '부평구', '인천 부평'],
    'destination',
    'mid',
    'high',
    'high',
    'strong',
    'strong',
    83,
    '인천 최대 역세권 상권 중 하나로 인천 서북부 소비 중심지입니다. 1호선·인천지하철 환승으로 유동인구가 풍부합니다.',
    '{"reasons":["인천 서북부 최대 상업 집결지","환승역 유동인구 풍부","다양한 연령·소득층 혼재 수요"],"warnings":["경쟁도 높음","구역별 수요 편차 큼"]}'::jsonb,
    'fresh',
    '2026-03-01',
    '2026-09-01',
    null
  ),
  (
    'goyang-wangsimni-general',
    '일산 웨스턴돔 상권',
    '고양시 일산서구',
    null,
    array['고양', '일산', '일산서구', '주엽', '웨스턴돔', '라페스타'],
    'destination',
    'mid',
    'mid-high',
    'high',
    'strong',
    'strong',
    82,
    '일산 대표 번화가로 라페스타·웨스턴돔 중심의 외식·카페·쇼핑 복합 상권입니다. 경기 서북부 소비 집결지입니다.',
    '{"reasons":["일산 최대 상업 집결지","경기 서북부 광역 수요 유입","카페·외식 감도 높은 수요층"],"warnings":["GTX 개통 후 수요 변화 가능","주차 접근성 중요"]}'::jsonb,
    'fresh',
    '2026-03-01',
    '2026-09-01',
    null
  )

on conflict (region_key) do update
  set
    region_name = excluded.region_name,
    district_name = excluded.district_name,
    summary = excluded.summary,
    evidence = excluded.evidence,
    updated_at = now();
