insert into public.market_location_signals (
  region_key,
  region_name,
  district_name,
  category_id,
  search_keywords,
  market_style,
  rent_band,
  competition_level,
  demand_level,
  access_level,
  category_fit_level,
  base_score,
  summary,
  evidence,
  freshness_status,
  last_checked_at,
  next_review_at,
  notes
)
values
  (
    'yeonnam-cafe',
    '연남동',
    '마포구',
    'cafe-dessert',
    array['연남', '연남동', '홍대입구'],
    'destination',
    'high',
    'high',
    'high',
    'strong',
    'strong',
    86,
    '브랜드 감도와 목적 방문 수요가 강해 카페·디저트 업종과 잘 맞는 상권입니다.',
    '{"reasons":["브랜드 발견형 유입이 활발함","도보 목적 방문 비중이 높음"],"warnings":["경쟁 강도와 임대료가 높음"]}'::jsonb,
    'fresh',
    '2026-03-19T09:00:00+09:00',
    '2026-03-26T09:00:00+09:00',
    null
  ),
  (
    'songridan-cafe',
    '송리단길',
    '송파구',
    'cafe-dessert',
    array['송리단길', '송파', '석촌호수'],
    'destination',
    'mid-high',
    'high',
    'high',
    'strong',
    'strong',
    84,
    '브랜딩과 목적 방문이 잘 붙는 카페·디저트형 상권입니다.',
    '{"reasons":["주말 목적 방문 수요가 강함","브랜드형 매장과 궁합이 좋음"],"warnings":["시즌별 편차와 주말 쏠림이 큼"]}'::jsonb,
    'review_soon',
    '2026-03-17T09:00:00+09:00',
    '2026-03-24T09:00:00+09:00',
    '주말 편중 수요 재확인 필요'
  ),
  (
    'yeouido-food',
    '여의도',
    '영등포구',
    'food',
    array['여의도', '여의도역'],
    'office',
    'high',
    'mid-high',
    'high',
    'strong',
    'strong',
    85,
    '점심과 저녁 회전이 빠른 외식형 업종에 강한 오피스 상권입니다.',
    '{"reasons":["직장인 점심 수요가 뚜렷함","회전율 중심 운영에 유리"],"warnings":["주말 수요가 약하고 임대료가 높음"]}'::jsonb,
    'fresh',
    '2026-03-19T09:00:00+09:00',
    '2026-03-26T09:00:00+09:00',
    null
  ),
  (
    'gangnam-beauty',
    '강남',
    '강남구',
    'beauty',
    array['강남', '강남역', '신논현'],
    'destination',
    'high',
    'high',
    'high',
    'strong',
    'strong',
    84,
    '브랜드형 뷰티와 시술 서비스가 밀집되어 있지만 수요도 큰 상권입니다.',
    '{"reasons":["뷰티 수요와 검색량이 모두 높음","브랜드 포지셔닝에 유리"],"warnings":["경쟁 과열과 높은 초기 비용에 주의"]}'::jsonb,
    'review_soon',
    '2026-03-18T09:00:00+09:00',
    '2026-03-25T09:00:00+09:00',
    null
  ),
  (
    'daechi-education',
    '대치동',
    '강남구',
    'education',
    array['대치', '대치동', '학원가'],
    'residential',
    'high',
    'high',
    'high',
    'strong',
    'strong',
    88,
    '교육 업종에서는 신뢰와 수요가 모두 강한 대표 상권입니다.',
    '{"reasons":["교육 수요가 매우 명확함","프리미엄 교육형 포지셔닝 가능"],"warnings":["임대료와 경쟁이 매우 높음"]}'::jsonb,
    'fresh',
    '2026-03-19T09:00:00+09:00',
    '2026-03-26T09:00:00+09:00',
    null
  ),
  (
    'bundang-living',
    '분당',
    '성남시',
    'living-service',
    array['분당', '서현', '정자'],
    'residential',
    'mid-high',
    'mid',
    'mid',
    'strong',
    'strong',
    80,
    '생활 서비스와 근거리 편의 업종이 안정적으로 검토되는 주거 상권입니다.',
    '{"reasons":["근거리 반복 수요가 안정적","생활형 서비스가 정착하기 좋음"],"warnings":["프리미엄 생활권이라 초기 비용은 높을 수 있음"]}'::jsonb,
    'fresh',
    '2026-03-18T09:00:00+09:00',
    '2026-03-25T09:00:00+09:00',
    null
  ),
  (
    'haeundae-cafe',
    '해운대',
    '해운대구',
    'cafe-dessert',
    array['해운대', '해운대역'],
    'destination',
    'high',
    'high',
    'high',
    'strong',
    'strong',
    83,
    '관광·목적 방문 수요가 강해 카페와 디저트 업종이 검토되는 상권입니다.',
    '{"reasons":["관광 수요와 목적 방문이 큼","비주얼·브랜드형 업종에 유리"],"warnings":["계절 편차와 임대료 변동성에 주의"]}'::jsonb,
    'review_soon',
    '2026-03-17T09:00:00+09:00',
    '2026-03-24T09:00:00+09:00',
    null
  ),
  (
    'iksun-retail',
    '익선동',
    '종로구',
    'retail',
    array['익선동', '종로3가'],
    'destination',
    'mid-high',
    'high',
    'high',
    'balanced',
    'strong',
    81,
    '브랜드형 소매와 경험형 공간이 잘 붙는 목적 방문 상권입니다.',
    '{"reasons":["공간 경험과 브랜드 발견형 소비가 활발함","소형 브랜드 매장과 잘 맞음"],"warnings":["주말 편중이 크고 회전 관리가 중요"]}'::jsonb,
    'review_soon',
    '2026-03-16T09:00:00+09:00',
    '2026-03-23T09:00:00+09:00',
    null
  ),
  (
    'dongtan-education',
    '동탄',
    '화성시',
    'education',
    array['동탄', '동탄신도시'],
    'residential',
    'mid-high',
    'mid',
    'mid',
    'balanced',
    'strong',
    80,
    '가족 중심 주거 수요가 강해 교육 업종과 잘 맞는 신도시 상권입니다.',
    '{"reasons":["학부모 기반 수요가 안정적","장기 재등록 구조를 만들기 좋음"],"warnings":["입지별 편차가 있어 세부 입지 점검 필요"]}'::jsonb,
    'fresh',
    '2026-03-18T09:00:00+09:00',
    '2026-03-25T09:00:00+09:00',
    null
  ),
  (
    'suwon-ingyedong-food',
    '인계동',
    '수원시',
    'food',
    array['인계동', '수원 인계동'],
    'destination',
    'mid-high',
    'high',
    'high',
    'strong',
    'balanced',
    79,
    '외식과 주류 복합 소비가 강한 중심 상권으로 식사형 외식도 검토 가능합니다.',
    '{"reasons":["유동인구가 충분함","야간 수요가 강함"],"warnings":["업종별 경쟁 밀도 차이가 큼"]}'::jsonb,
    'review_soon',
    '2026-03-16T09:00:00+09:00',
    '2026-03-23T09:00:00+09:00',
    null
  ),
  (
    'jamsil-retail',
    '잠실',
    '송파구',
    'retail',
    array['잠실', '잠실역'],
    'destination',
    'high',
    'high',
    'high',
    'strong',
    'strong',
    82,
    '대형 유동과 목적 방문이 동시에 있어 브랜드형 소매에 잘 맞는 상권입니다.',
    '{"reasons":["대형 유입이 강함","브랜드 노출 효과가 큼"],"warnings":["임대료와 경쟁 강도가 매우 높음"]}'::jsonb,
    'fresh',
    '2026-03-19T09:00:00+09:00',
    '2026-03-26T09:00:00+09:00',
    null
  ),
  (
    'ilsan-pet',
    '일산',
    '고양시',
    'pet',
    array['일산', '라페스타', '백석'],
    'residential',
    'mid',
    'mid',
    'mid',
    'balanced',
    'strong',
    78,
    '주거 기반 반려동물 수요가 꾸준해 펫 서비스 업종 검토에 적합한 지역입니다.',
    '{"reasons":["반복 방문 수요를 만들기 좋음","펫미용·호텔·용품 결합 가능"],"warnings":["생활권별 편차를 다시 봐야 함"]}'::jsonb,
    'fresh',
    '2026-03-18T09:00:00+09:00',
    '2026-03-25T09:00:00+09:00',
    null
  )
on conflict (region_key) do update
set
  region_name = excluded.region_name,
  district_name = excluded.district_name,
  category_id = excluded.category_id,
  search_keywords = excluded.search_keywords,
  market_style = excluded.market_style,
  rent_band = excluded.rent_band,
  competition_level = excluded.competition_level,
  demand_level = excluded.demand_level,
  access_level = excluded.access_level,
  category_fit_level = excluded.category_fit_level,
  base_score = excluded.base_score,
  summary = excluded.summary,
  evidence = excluded.evidence,
  freshness_status = excluded.freshness_status,
  last_checked_at = excluded.last_checked_at,
  next_review_at = excluded.next_review_at,
  notes = excluded.notes,
  is_active = true,
  updated_at = now();
