-- ═══════════════════════════════════════════════════════════════════════════
--  인테리어 가이드 확장 v4 — 10개 세부업종 자재 6개 + 디자인 컨셉 3개
--  기존 v2/v3에서 1-2개씩만 있던 데이터를 6+3 규격으로 확장
--  출처: 한국·미국 2025-2026 인테리어 트렌드 조사 (한/영 듀얼 리서치)
-- ═══════════════════════════════════════════════════════════════════════════

-- 기존 데이터 삭제 후 재삽입 (10개 대상 업종만)
DELETE FROM interior_design_guides WHERE sub_industry_id IN (
  'delivery-meals', 'ramen-noodle', 'salad-healthy', 'snack-street',
  'specialty-coffee', 'bakery-studio',
  'nail-studio', 'skin-care-room',
  'yoga-studio', 'pt-gym'
);

-- ╔═══════════════════════════════════════════════════════════════╗
-- ║  1. FOOD: 배달전문점 (delivery-meals)                        ║
-- ╚═══════════════════════════════════════════════════════════════╝
INSERT INTO interior_design_guides (category_id, sub_industry_id, guide_type, name_ko, name_en, description_ko, description_en, icon_name, tags, pros, cons, cost_range_ko, trend_source, priority) VALUES
-- 자재 6개
('food', 'delivery-meals', 'material',
 '스테인리스 포장 스테이션', 'Stainless Packaging Station',
 '배달 포장 전용 작업대. 봉투·용기 적재 선반 통합형. 포장 속도가 매출을 결정하는 배달 업태의 핵심 설비.',
 'Dedicated packing workstation with integrated container shelves. Packaging speed determines revenue in delivery-only operations.',
 'Zap', '{"포장", "효율", "배달"}', NULL, NULL, '150~400만원', '한국 2025', 1),
('food', 'delivery-meals', 'material',
 '업소용 배기 후드 (고풍량)', 'High-CFM Commercial Exhaust Hood',
 '고스트키친은 좁은 공간에서 다수 조리기구가 동시 가동. 2000CFM 이상 고풍량 후드+그리스 트랩 필수.',
 'Ghost kitchens run multiple cooking stations simultaneously in compact spaces. 2000+ CFM hood with grease trap essential.',
 'Wind', '{"환기", "안전", "필수"}', NULL, NULL, '300~800만원', '한국 2025', 2),
('food', 'delivery-meals', 'material',
 '논슬립 에폭시 바닥', 'Non-slip Epoxy Floor',
 '주방 바닥 전용 논슬립 에폭시 코팅. 물·기름에 강하고 HACCP 기준 충족. 배수구 경사 시공 포함.',
 'Non-slip epoxy coating for kitchen floors. Resistant to water/oil, HACCP compliant. Includes drain slope installation.',
 'Shield', '{"바닥", "안전", "위생"}', NULL, NULL, '평당 10~20만원', '한국 2025', 3),
('food', 'delivery-meals', 'material',
 '보온·보냉 선반 (히팅 캐비닛)', 'Heating/Cooling Cabinet',
 '완성된 음식을 배달기사 픽업 전까지 최적 온도로 보관. 피크 시간 5~10분 대기가 품질 좌우.',
 'Keeps finished orders at optimal temperature until rider pickup. 5-10 min wait during peak hours determines quality.',
 'Layers', '{"보온", "품질", "배달"}', NULL, NULL, '80~250만원', '한국 2025', 4),
('food', 'delivery-meals', 'material',
 'FRP 벽면 패널 (위생 벽)', 'FRP Wall Panel',
 '유리섬유강화 플라스틱 벽면. 기름·습기에 강하고 물세척 가능. 타일 대비 시공 빠르고 줄눈 없음.',
 'Fiberglass reinforced plastic wall. Oil/moisture resistant, washable. Faster than tile, no grout lines.',
 'Shield', '{"벽면", "위생", "세척"}', NULL, NULL, '평당 8~15만원', '글로벌 2025', 5),
('food', 'delivery-meals', 'material',
 'LED 작업등 (6500K 주광색)', 'LED Task Light (6500K Daylight)',
 '주방 작업대 위 고조도 LED. 6500K 주광색으로 식재료 색상 정확 확인. 밀폐 방수형 필수.',
 'High-intensity LED above workstations. 6500K daylight for accurate ingredient color check. Sealed waterproof type required.',
 'Lightbulb', '{"조명", "주방", "작업"}', NULL, NULL, '등기구당 5~15만원', '한국 2025', 6),

-- 컨셉 3개
('food', 'delivery-meals', 'concept',
 '고스트 키친 (배달 전용)', 'Ghost Kitchen (Delivery-Only)',
 '홀 없이 주방만 운영하는 배달 전용 공간. 임대료 50%+ 절감. 다브랜드 동시 운영으로 매출 극대화. 배달앱 마케팅에 집중 투자.',
 'Kitchen-only delivery space with no dining area. 50%+ rent savings. Multi-brand operation maximizes revenue. Focus marketing on delivery apps.',
 'Zap', '{"배달전용", "저비용", "효율극대화"}',
 '{"임대료 대폭 절감 (홀 면적 불필요)", "주방 동선 최적화로 조리 속도 향상", "다브랜드 동시 운영 가능", "초기 투자 최소화"}',
 '{"고객 접점 없어 브랜드 인지도 구축 어려움", "배달앱 수수료 의존도 높음", "리뷰 관리가 생존 조건"}',
 '평당 50~100만원', '한국 2025', 1),
('food', 'delivery-meals', 'concept',
 '공유주방 입점형', 'Shared Kitchen Tenant',
 '위쿡·고스트키친코리아 등 공유주방에 입점. 보증금+월세만으로 즉시 창업. 설비·인허가 공유로 리스크 최소화.',
 'Join shared kitchens like WeeCook. Start immediately with deposit+rent only. Shared equipment and permits minimize risk.',
 'Home', '{"공유주방", "초저비용", "빠른창업"}',
 '{"초기 투자 1000만원 이하 가능", "인허가 절차 간소화", "설비 유지보수 공유", "위치 이동 자유로움"}',
 '{"공간 제약으로 메뉴 확장 한계", "운영 시간 제한 가능", "독립 브랜딩 어려움"}',
 '보증금 300~1000만원 + 월 80~200만원', '한국 2025', 2),
('food', 'delivery-meals', 'concept',
 '미니 매장+배달 하이브리드', 'Mini Storefront + Delivery Hybrid',
 '5~8평 소형 테이크아웃 매장 + 배달 병행. 최소한의 카운터와 대기 공간으로 오프라인 인지도 확보.',
 'Small 5-8 pyeong takeout shop + delivery combination. Minimal counter and waiting area for offline brand awareness.',
 'Star', '{"하이브리드", "테이크아웃", "브랜딩"}',
 '{"오프라인 브랜드 인지도 확보", "배달+테이크아웃 이중 매출", "단골 고객 형성 가능", "배달앱 의존도 분산"}',
 '{"임대료 상승", "최소 인력 1명 필요", "인테리어 비용 추가 발생"}',
 '평당 80~150만원', '한국 2025', 3);

-- ╔═══════════════════════════════════════════════════════════════╗
-- ║  2. FOOD: 라면/면류점 (ramen-noodle)                         ║
-- ╚═══════════════════════════════════════════════════════════════╝
INSERT INTO interior_design_guides (category_id, sub_industry_id, guide_type, name_ko, name_en, description_ko, description_en, icon_name, tags, pros, cons, cost_range_ko, trend_source, priority) VALUES
-- 자재 6개
('food', 'ramen-noodle', 'material',
 '원목 카운터 바 (오픈 주방)', 'Wood Counter Bar (Open Kitchen)',
 '일본식 라멘 카운터. 두께 40mm+ 원목 또는 집성목. 주방을 정면으로 보는 카운터석이 라멘집의 정체성.',
 'Japanese-style ramen counter. 40mm+ solid or laminated wood. Counter seats facing the kitchen define ramen shop identity.',
 'Star', '{"카운터", "오픈주방", "라멘"}', NULL, NULL, '카운터 전체 150~400만원', '한국 2025', 1),
('food', 'ramen-noodle', 'material',
 '노렌 커튼 (입구/칸막이)', 'Noren Curtain (Entry/Partition)',
 '일본 전통 천 가리개. 매장 입구와 주방 입구에 설치하여 일본 라멘집 정통 분위기 연출. 브랜드 로고 인쇄 가능.',
 'Traditional Japanese fabric divider. Install at store and kitchen entrances for authentic atmosphere. Brand logo printable.',
 'Layers', '{"일본감성", "인테리어", "정통"}', NULL, NULL, '개당 5~20만원', '글로벌 2025', 2),
('food', 'ramen-noodle', 'material',
 '고풍량 스팀 후드 (면 조리 전용)', 'High-Volume Steam Hood',
 '면 삶기에서 발생하는 대량의 증기 처리용 후드. 일반 후드 대비 2배 풍량 필요. 결로 방지 덕트 포함.',
 'Hood for handling heavy steam from noodle cooking. Requires 2x airflow vs standard hoods. Includes condensation-proof ducting.',
 'Wind', '{"환기", "증기", "필수"}', NULL, NULL, '300~600만원', '한국 2025', 3),
('food', 'ramen-noodle', 'material',
 '화이트 서브웨이 타일 벽면', 'White Subway Tile Wall',
 '주방 뒤 벽면에 시공. 기름·증기에 강하고 청소 용이. 검정 그라우트로 포인트 시 일본 감성 강화.',
 'Applied behind kitchen wall. Resistant to oil/steam and easy to clean. Black grout accent enhances Japanese aesthetic.',
 'Layers', '{"벽면", "위생", "감성"}', NULL, NULL, '평당 8~15만원', '글로벌 2025', 4),
('food', 'ramen-noodle', 'material',
 '라멘돈부리 디스플레이 선반', 'Ramen Bowl Display Shelf',
 '시그니처 라멘 그릇을 진열하는 오픈 선반. 그릇 자체가 인테리어 소품이 됨. 일본 도기 그릇 추천.',
 'Open shelf displaying signature ramen bowls. Bowls themselves become interior decor. Japanese ceramic bowls recommended.',
 'Layers', '{"디스플레이", "소품", "일본감성"}', NULL, NULL, '선반 20~60만원 + 그릇 세트 30~100만원', '한국 2025', 5),
('food', 'ramen-noodle', 'material',
 '따뜻한 펜던트 조명 (2700K)', 'Warm Pendant Light (2700K)',
 '카운터 상부 펜던트 조명. 2700K 따뜻한 톤으로 라멘 국물의 색감을 극대화. 간격 60~80cm 배치.',
 'Counter-top pendant lights. 2700K warm tone maximizes ramen broth color appeal. Spaced 60-80cm apart.',
 'Lightbulb', '{"조명", "분위기", "음식사진"}', NULL, NULL, '개당 5~20만원', '한국 2025', 6),

-- 컨셉 3개
('food', 'ramen-noodle', 'concept',
 '이자카야 라멘 바', 'Izakaya Ramen Bar',
 '어두운 우드톤 + 따뜻한 간접 조명 + 일본 주점 분위기. 라멘+교자+카라아게+사케로 객단가 상승. 저녁 주류 매출 병행.',
 'Dark wood tone + warm ambient lighting + izakaya atmosphere. Ramen + gyoza + karaage + sake for higher ticket. Evening alcohol revenue.',
 'Star', '{"일본감성", "우드톤", "주류"}',
 '{"객단가 상승 (주류+사이드 추가)", "SNS 포토제닉 분위기", "저녁 매출 강화", "차별화된 브랜드 이미지"}',
 '{"인테리어 비용 높음", "환기 설비 대형화 필요", "목재 관리 (습기·기름)"}',
 '평당 150~250만원', '한국 2025', 1),
('food', 'ramen-noodle', 'concept',
 '미니멀 라멘 카운터', 'Minimal Ramen Counter',
 '화이트+스테인리스+원목 카운터 중심. 8~12석 소규모. 메뉴 3~5종으로 집중. 1인 식사 친화적 동선.',
 'White + stainless + wood counter focused. 8-12 seats small scale. Focused menu of 3-5 items. Solo-diner friendly flow.',
 'Layers', '{"미니멀", "1인식", "소규모"}',
 '{"소자본 창업 가능", "회전율 극대화", "1인 고객 친화적", "운영 효율 최고"}',
 '{"좌석 수 제한으로 매출 천장", "그룹 고객 수용 어려움", "단조로운 느낌 가능"}',
 '평당 100~160만원', '한국 2025', 2),
('food', 'ramen-noodle', 'concept',
 '네오 재패니즈 모던', 'Neo-Japanese Modern',
 '일본 전통 요소(격자·노렌·도기)를 현대적으로 재해석. 블랙+내추럴 우드+간접 조명. 고급 라멘 다이닝.',
 'Modern reinterpretation of Japanese elements (lattice, noren, ceramics). Black + natural wood + ambient lighting. Premium ramen dining.',
 'Crown', '{"프리미엄", "모던재패니즈", "고급"}',
 '{"프리미엄 가격 정당화", "데이트 코스 포지셔닝", "인스타그래머블 공간", "브랜드 가치 극대화"}',
 '{"높은 인테리어 투자", "일본 소품 수입 비용", "넓은 면적 필요"}',
 '평당 200~350만원', '글로벌 2025', 3);

-- ╔═══════════════════════════════════════════════════════════════╗
-- ║  3. FOOD: 샐러드/건강식 (salad-healthy)                      ║
-- ╚═══════════════════════════════════════════════════════════════╝
INSERT INTO interior_design_guides (category_id, sub_industry_id, guide_type, name_ko, name_en, description_ko, description_en, icon_name, tags, pros, cons, cost_range_ko, trend_source, priority) VALUES
-- 자재 6개
('food', 'salad-healthy', 'material',
 '냉장 오픈 쇼케이스 (샐러드 바)', 'Refrigerated Open Showcase',
 '신선한 채소·토핑을 보여주는 투명 냉장 쇼케이스. 건강식 매장의 첫인상을 결정하는 핵심 장비.',
 'Transparent refrigerated showcase displaying fresh vegetables and toppings. Core equipment defining first impression of healthy food stores.',
 'Leaf', '{"신선", "쇼케이스", "건강"}', NULL, NULL, '300~800만원', '한국 2025', 1),
('food', 'salad-healthy', 'material',
 '식물 벽 (버티컬 가든)', 'Living Wall (Vertical Garden)',
 '실내 벽면 녹화. 자동 관수 시스템 포함. 건강식 매장의 자연 친화적 이미지를 시각적으로 전달.',
 'Indoor wall greening with auto-irrigation system. Visually communicates nature-friendly image of healthy food stores.',
 'Leaf', '{"식물", "친환경", "인테리어"}', NULL, NULL, '평당 30~80만원 + 관수 시스템 50~150만원', '글로벌 2025', 2),
('food', 'salad-healthy', 'material',
 '대나무/재생목 카운터', 'Bamboo/Reclaimed Wood Counter',
 '지속가능한 소재의 카운터탑. 대나무 또는 재생목(리클레임드 우드). 친환경 브랜드 가치 전달.',
 'Sustainable counter material. Bamboo or reclaimed wood. Communicates eco-friendly brand values.',
 'Leaf', '{"카운터", "친환경", "지속가능"}', NULL, NULL, '카운터 전체 100~300만원', '글로벌 2025', 3),
('food', 'salad-healthy', 'material',
 '자연광 연출 조명 (5000K)', 'Natural Daylight LED (5000K)',
 '5000K 자연광 톤 LED로 채소의 신선한 색감을 살림. 쇼케이스 내부 + 천장 조명 통일.',
 '5000K natural daylight LED to highlight fresh vegetable colors. Unified inside showcase + ceiling lighting.',
 'Lightbulb', '{"조명", "신선감", "자연광"}', NULL, NULL, '세트 50~150만원', '한국 2025', 4),
('food', 'salad-healthy', 'material',
 '친환경 포장 스테이션', 'Eco-Packaging Station',
 '생분해성 용기·종이 빨대·옥수수 전분 포크 보관 및 포장 전용 구역. 친환경 가치를 고객이 직접 체감.',
 'Biodegradable containers, paper straws, corn starch forks storage and packing zone. Customers directly experience eco values.',
 'Leaf', '{"포장", "친환경", "테이크아웃"}', NULL, NULL, '초기 세팅 30~80만원', '글로벌 2025', 5),
('food', 'salad-healthy', 'material',
 '테라조 바닥재', 'Terrazzo Floor',
 '자연석 칩이 박힌 시멘트 마감. 깔끔하면서도 개성 있는 바닥. 건강식 매장의 세련된 이미지 연출.',
 'Cement finish with natural stone chips. Clean yet distinctive floor. Creates sophisticated image for health food stores.',
 'Layers', '{"바닥", "세련", "내구성"}', NULL, NULL, '평당 15~30만원', '글로벌 2025', 6),

-- 컨셉 3개
('food', 'salad-healthy', 'concept',
 '그린 내추럴 컨셉', 'Green Natural Concept',
 '밝은 화이트 + 그린 식물 + 천연 소재(우드·대나무). 건강한 라이프스타일을 공간 전체로 시각화. 바이오필릭 디자인 적용.',
 'Bright white + green plants + natural materials (wood, bamboo). Visualize healthy lifestyle throughout the space. Biophilic design applied.',
 'Leaf', '{"건강", "자연", "친환경"}',
 '{"건강식 이미지 시각적 강화", "MZ세대 타겟 적합", "SNS 바이럴 유도", "프리미엄 가격 정당화"}',
 '{"식물 관리 비용 (월 10~30만원)", "자연소재 내구성 낮음", "벌레/곰팡이 관리 필요"}',
 '평당 100~180만원', '한국 2025', 1),
('food', 'salad-healthy', 'concept',
 '클린 모던 테이크아웃', 'Clean Modern Takeout',
 '화이트+민트 톤 + 스테인리스 쇼케이스. 테이크아웃 동선 최적화. 대기 시간 최소화 레이아웃.',
 'White + mint tone + stainless showcase. Takeout flow optimized. Layout minimizing wait time.',
 'Layers', '{"테이크아웃", "클린", "효율"}',
 '{"테이크아웃 회전율 극대화", "인테리어 비용 최소화", "청결 이미지 유지 용이", "배달 병행 가능"}',
 '{"체류형 고객 유치 어려움", "객단가 상승 한계", "감성적 요소 부족 가능"}',
 '평당 80~140만원', '한국 2025', 2),
('food', 'salad-healthy', 'concept',
 '팜투테이블 다이닝', 'Farm-to-Table Dining',
 '실내 허브 가든 + 로컬 식재료 디스플레이 + 원목 테이블. 식재료 원산지·농장 스토리를 벽면에 전시.',
 'Indoor herb garden + local ingredient display + wood tables. Display ingredient origins and farm stories on walls.',
 'Crown', '{"팜투테이블", "프리미엄", "스토리텔링"}',
 '{"스토리텔링으로 브랜드 가치 극대화", "프리미엄 가격 정당화", "충성 고객 형성", "ESG 가치 부합"}',
 '{"식재료 원가 높음", "허브 가든 관리 비용", "넓은 공간 필요"}',
 '평당 150~250만원', '글로벌 2025', 3);

-- ╔═══════════════════════════════════════════════════════════════╗
-- ║  4. FOOD: 분식/길거리음식 (snack-street)                     ║
-- ╚═══════════════════════════════════════════════════════════════╝
INSERT INTO interior_design_guides (category_id, sub_industry_id, guide_type, name_ko, name_en, description_ko, description_en, icon_name, tags, pros, cons, cost_range_ko, trend_source, priority) VALUES
-- 자재 6개
('food', 'snack-street', 'material',
 '오픈 카운터 (조리 과정 노출)', 'Open Counter (Visible Cooking)',
 '떡볶이·튀김 등 조리 과정을 고객이 직접 볼 수 있는 L자형 또는 U자형 오픈 카운터. 현장감이 핵심.',
 'L-shaped or U-shaped open counter letting customers watch tteokbokki/fried food cooking. Live atmosphere is key.',
 'Star', '{"오픈카운터", "현장감", "분식"}', NULL, NULL, '카운터 전체 100~300만원', '한국 2025', 1),
('food', 'snack-street', 'material',
 '디지털 메뉴보드 (DID)', 'Digital Menu Board (DID)',
 '벽걸이형 32~55인치 디지털 메뉴판. 사진+가격 표시. 계절 메뉴·이벤트 즉시 교체. 주문 속도 향상.',
 'Wall-mounted 32-55 inch digital menu display. Photo+price display. Instant seasonal/event menu changes. Speeds up ordering.',
 'Monitor', '{"디지털", "메뉴", "효율"}', NULL, NULL, '50~150만원', '한국 2025', 2),
('food', 'snack-street', 'material',
 '양념 스테이션 (셀프 바)', 'Condiment Station (Self Bar)',
 '단무지·파·양념·소스 셀프 바. 스테인리스 GN팬 세트 + 냉장 디스플레이. 인건비 절감+고객 만족.',
 'Self-service bar for radish, green onion, sauces. Stainless GN pan set + refrigerated display. Saves labor + customer satisfaction.',
 'Layers', '{"셀프", "양념", "효율"}', NULL, NULL, '세트 30~100만원', '한국 2025', 3),
('food', 'snack-street', 'material',
 '미끄럼 방지 타일 바닥 (200x200)', 'Anti-slip Tile Floor (200x200)',
 '기름·물에 강한 논슬립 소형 타일. 분식집 특성상 바닥 오염이 잦으므로 200x200 소형 타일로 배수 용이.',
 'Non-slip small tiles resistant to oil/water. Frequent floor soiling in snack shops requires 200x200 tiles for easy drainage.',
 'Shield', '{"바닥", "안전", "위생"}', NULL, NULL, '평당 8~18만원', '한국 2025', 4),
('food', 'snack-street', 'material',
 '외부 LED 간판 (채널 사인)', 'LED Channel Sign (Exterior)',
 '분식집은 거리 가시성이 매출 직결. 밝은 LED 채널 사인으로 멀리서도 눈에 띄는 간판 필수.',
 'Street visibility directly impacts revenue. Bright LED channel sign visible from distance is essential.',
 'Lightbulb', '{"간판", "외부", "가시성"}', NULL, NULL, '100~250만원', '한국 2025', 5),
('food', 'snack-street', 'material',
 '벤치형 좌석 (공간 효율)', 'Bench-style Seating',
 '벽면 붙임 벤치석 + 이동식 스툴. 좁은 공간에서 좌석 수 극대화. 청소 용이한 비닐 또는 인조가죽.',
 'Wall-mounted bench + movable stools. Maximize seating in small spaces. Vinyl or faux leather for easy cleaning.',
 'Layers', '{"좌석", "공간효율", "가성비"}', NULL, NULL, '벤치석 1m당 15~30만원', '한국 2025', 6),

-- 컨셉 3개
('food', 'snack-street', 'concept',
 '뉴트로 분식집', 'Newtro Korean Snack Bar',
 '80-90년대 분식집 감성을 현대적으로 재해석. 스테인리스+타일+플라스틱 의자+네온사인. MZ세대에게 향수+신선함.',
 '80s-90s Korean snack bar reimagined. Stainless + tile + plastic chairs + neon. Nostalgia + freshness for MZ generation.',
 'Star', '{"레트로", "MZ세대", "뉴트로"}',
 '{"초저비용 시공 가능", "SNS 바이럴 효과 극대화", "MZ세대 호응", "빈티지 소품 저렴 구매 가능"}',
 '{"유행 주기 짧을 수 있음", "실제 불편함 가능 (플라스틱 의자)", "40대+ 고객 호불호"}',
 '평당 70~120만원', '한국 2025', 1),
('food', 'snack-street', 'concept',
 '클린 모던 분식', 'Clean Modern Snack',
 '화이트+그레이 톤에 깔끔한 조명. 분식의 B급 이미지를 탈피한 프리미엄 캐주얼. 키오스크 주문.',
 'White + gray tones with clean lighting. Premium casual breaking free from B-grade snack image. Kiosk ordering.',
 'Layers', '{"모던", "클린", "프리미엄"}',
 '{"프리미엄 분식으로 객단가 상승", "청결 이미지 확보", "프랜차이즈 확장 용이", "여성 고객 유치"}',
 '{"분식 가성비 기대와 충돌 가능", "인테리어 비용 상승", "가격 저항 가능"}',
 '평당 100~160만원', '한국 2025', 2),
('food', 'snack-street', 'concept',
 '포장마차 감성 (길거리 스타일)', 'Street Stall Vibe',
 '텐트 천막 모티프 + 빨간 플라스틱 의자 + 철제 테이블 + 소주 포스터. 노스탤지어 길거리 음식 경험.',
 'Tent canopy motif + red plastic chairs + steel tables + soju posters. Nostalgic street food experience.',
 'Star', '{"포장마차", "노스탤지어", "길거리"}',
 '{"초저비용 시공", "즉각적 분위기 전달", "주류 매출 동반 가능", "외국인 관광객 매력"}',
 '{"위생 이미지 우려", "편안함 부족", "여름 냉방·겨울 난방 어려움"}',
 '평당 50~90만원', '한국 2025', 3);

-- ╔═══════════════════════════════════════════════════════════════╗
-- ║  5. CAFE: 스페셜티 커피 (specialty-coffee)                   ║
-- ╚═══════════════════════════════════════════════════════════════╝
INSERT INTO interior_design_guides (category_id, sub_industry_id, guide_type, name_ko, name_en, description_ko, description_en, icon_name, tags, pros, cons, cost_range_ko, trend_source, priority) VALUES
-- 자재 6개
('cafe-dessert', 'specialty-coffee', 'material',
 '에스프레소 바 카운터 (월넛 슬랩)', 'Espresso Bar Counter (Walnut Slab)',
 '두께 50mm+ 월넛 또는 오크 라이브엣지 슬랩. 에스프레소 머신을 정면 배치하여 바리스타 퍼포먼스 쇼케이스.',
 '50mm+ walnut or oak live-edge slab. Espresso machine placed front-facing to showcase barista performance.',
 'Star', '{"카운터", "스페셜티", "원목"}', NULL, NULL, '카운터 전체 200~500만원', '한국 2025', 1),
('cafe-dessert', 'specialty-coffee', 'material',
 '핸드드립/푸어오버 스테이션', 'Pour-over / Hand Drip Station',
 '스테인리스 드립 트레이 + 구스넥 케틀 거치대 + 서버 디스플레이. 브루잉 과정이 시각적 콘텐츠.',
 'Stainless drip tray + gooseneck kettle stand + server display. Brewing process becomes visual content.',
 'Layers', '{"핸드드립", "브루잉", "스페셜티"}', NULL, NULL, '세트 80~200만원', '미국 2025', 2),
('cafe-dessert', 'specialty-coffee', 'material',
 '원두 디스플레이 월', 'Coffee Bean Display Wall',
 '산지별 원두를 유리 용기에 진열하는 벽면. 원산지·로스팅 프로필·풍미 노트 표시. 원두 선택 경험 제공.',
 'Wall displaying beans by origin in glass containers. Shows origin, roast profile, flavor notes. Provides bean selection experience.',
 'Layers', '{"원두", "디스플레이", "교육"}', NULL, NULL, '벽면 세트 50~150만원', '글로벌 2025', 3),
('cafe-dessert', 'specialty-coffee', 'material',
 '폴리싱 콘크리트 바닥', 'Polished Concrete Floor',
 '기존 콘크리트를 연마·코팅. 시공비 저렴하고 내구성 최상. 서드웨이브 카페의 글로벌 표준 바닥재.',
 'Ground and coated existing concrete. Low cost, top durability. Global standard flooring for third-wave cafes.',
 'Layers', '{"바닥", "인더스트리얼", "가성비"}', NULL, NULL, '평당 8~15만원', '글로벌 2025', 4),
('cafe-dessert', 'specialty-coffee', 'material',
 '로스터 쇼케이스 공간', 'Roaster Showcase Area',
 '소형 로스터(1~3kg)를 매장 내 배치하여 로스팅 과정 공개. 갓 볶은 원두 향기가 자연스러운 마케팅.',
 'In-store small roaster (1-3kg) showcasing roasting process. Fresh-roasted bean aroma as natural marketing.',
 'Factory', '{"로스팅", "체험", "차별화"}', NULL, NULL, '로스터 1000~3000만원 + 배기 공간 300만원', '한국 2025', 5),
('cafe-dessert', 'specialty-coffee', 'material',
 '정수 시스템 디스플레이', 'Water Filtration Display',
 '역삼투압(RO) 또는 BWT 정수기를 투명 설치. 물 품질이 커피 맛의 98%라는 메시지를 시각적으로 전달.',
 'Transparent RO or BWT water filter installation. Visually communicates that water quality is 98% of coffee taste.',
 'Layers', '{"정수", "품질", "투명"}', NULL, NULL, '정수 시스템 200~500만원', '글로벌 2025', 6),

-- 컨셉 3개
('cafe-dessert', 'specialty-coffee', 'concept',
 '서드웨이브 커피 바', 'Third Wave Coffee Bar',
 '바 형태 카운터 + 원목 + 노출 콘크리트. 바리스타와 대화하며 커피를 받는 경험 중심. 좌석 수보다 커피 경험에 집중.',
 'Bar-style counter + natural wood + exposed concrete. Experience-focused: chatting with barista while receiving coffee.',
 'Star', '{"서드웨이브", "바카운터", "경험"}',
 '{"커피 전문성 극대화", "높은 객단가 정당화", "마니아 단골 형성", "SNS 차별화 강력"}',
 '{"좌석 수 제한으로 매출 천장", "높은 인테리어 비용", "바리스타 역량 의존도 높음"}',
 '평당 180~300만원', '한국 2025', 1),
('cafe-dessert', 'specialty-coffee', 'concept',
 '내추럴 바이오필릭 카페', 'Natural Biophilic Cafe',
 '코르크·우드·린넨 등 자연 소재 + 실내 식물 + 대형 채광창. 커피와 자연이 어우러지는 힐링 공간.',
 'Natural materials (cork, wood, linen) + indoor plants + large windows. Healing space where coffee meets nature.',
 'Leaf', '{"바이오필릭", "자연", "힐링"}',
 '{"넓은 고객층 소구", "체류시간 증가로 음료 추가 주문", "리피트율 높음", "사계절 매력"}',
 '{"식물 관리 비용 월 10~20만원", "자연소재 관리 필요", "넓은 면적 필요"}',
 '평당 160~250만원', '글로벌 2025', 2),
('cafe-dessert', 'specialty-coffee', 'concept',
 '인더스트리얼 로스터리', 'Industrial Roastery',
 '노출 천장 + 철제 파이프 + 콘크리트 벽 + 대형 로스터. 공장에서 커피를 만드는 느낌. 공간 자체가 브랜드.',
 'Exposed ceiling + metal pipes + concrete walls + large roaster. Factory-style coffee making. The space itself is the brand.',
 'Factory', '{"인더스트리얼", "로스터리", "공장감성"}',
 '{"강렬한 브랜드 인상", "로스터 관련 투어/체험 가능", "천장 미시공으로 공사비 절감", "SNS 바이럴"}',
 '{"소음 문제 (로스터 가동)", "먼지·연기 관리 필요", "추울 수 있음 (단열)"}',
 '평당 120~200만원', '글로벌 2025', 3);

-- ╔═══════════════════════════════════════════════════════════════╗
-- ║  6. CAFE: 베이커리 스튜디오 (bakery-studio)                  ║
-- ╚═══════════════════════════════════════════════════════════════╝
INSERT INTO interior_design_guides (category_id, sub_industry_id, guide_type, name_ko, name_en, description_ko, description_en, icon_name, tags, pros, cons, cost_range_ko, trend_source, priority) VALUES
-- 자재 6개
('cafe-dessert', 'bakery-studio', 'material',
 '원목 빵 진열대 (다단 쇼케이스)', 'Wood Bread Display (Multi-tier)',
 '따뜻한 원목 소재 다단 진열대. 갓 구운 빵의 색감을 돋보이게 하는 LED 조명 내장. 매장 정면 배치.',
 'Warm wood multi-tier display with built-in LED highlighting fresh bread colors. Placed at store front.',
 'Layers', '{"진열대", "빵", "쇼케이스"}', NULL, NULL, '세트 200~600만원', '한국 2025', 1),
('cafe-dessert', 'bakery-studio', 'material',
 '오픈 오븐 스테이션', 'Open Oven Station',
 '반죽부터 굽기까지 보여주는 오픈 주방. 갓 구운 빵 향기가 자연스러운 마케팅. 내열 유리 파티션 추천.',
 'Open kitchen showing from dough to baking. Fresh-baked aroma as natural marketing. Heat-resistant glass partition recommended.',
 'Factory', '{"오픈주방", "베이킹", "체험"}', NULL, NULL, '오븐+공간 세팅 2000~5000만원', '한국 2025', 2),
('cafe-dessert', 'bakery-studio', 'material',
 '밀가루 방진 마감재', 'Flour-proof Surface Finish',
 '베이커리 특성상 밀가루 분진이 다량 발생. 바닥은 에폭시, 벽면은 유광 타일 또는 FRP로 시공하여 세척 용이.',
 'Bakeries generate heavy flour dust. Epoxy floors, glossy tile or FRP walls for easy cleaning.',
 'Shield', '{"위생", "분진", "세척"}', NULL, NULL, '바닥+벽면 평당 15~30만원', '한국 2025', 3),
('cafe-dessert', 'bakery-studio', 'material',
 '케이크 쇼케이스 (곡면 유리 냉장)', 'Cake Showcase (Curved Glass Refrigerated)',
 '곡면 유리 냉장 진열대. LED 내장으로 케이크·타르트를 보석처럼 연출. 매장 첫인상 결정 장비.',
 'Curved glass refrigerated display. Built-in LED showcases cakes/tarts like jewels. Defines store first impression.',
 'Star', '{"케이크", "쇼케이스", "냉장"}', NULL, NULL, '150~400만원', '한국 2025', 4),
('cafe-dessert', 'bakery-studio', 'material',
 '포장 카운터 & 선물 포장대', 'Packaging Counter & Gift Wrap Station',
 '빵 포장과 선물 세트 포장을 위한 전용 카운터. 리본·박스·쇼핑백 수납 통합. 선물 수요 대응.',
 'Dedicated counter for bread packaging and gift sets. Integrated storage for ribbons, boxes, shopping bags. Gift demand ready.',
 'Layers', '{"포장", "선물", "카운터"}', NULL, NULL, '카운터 50~150만원', '한국 2025', 5),
('cafe-dessert', 'bakery-studio', 'material',
 '따뜻한 조명 (2700K 다운라이트)', 'Warm Downlight (2700K)',
 '빵의 갈색 크러스트를 맛있게 보이게 하는 2700K 따뜻한 조명. 진열대 상부에 집중 배치.',
 '2700K warm lighting making bread golden crust look appetizing. Concentrated above display shelves.',
 'Lightbulb', '{"조명", "빵", "따뜻함"}', NULL, NULL, '등기구당 3~10만원', '한국 2025', 6),

-- 컨셉 3개
('cafe-dessert', 'bakery-studio', 'concept',
 '유러피안 아티장 베이커리', 'European Artisan Bakery',
 '따뜻한 우드 + 대리석 + 아이언 선반 + 벽돌. 유럽 빵집 감성. 빵을 진열하는 쇼케이스 자체가 인테리어의 핵심.',
 'Warm wood + marble + iron shelves + brick. European bakery feel. The bread showcase IS the interior design centerpiece.',
 'Crown', '{"유럽감성", "프리미엄", "쇼케이스"}',
 '{"프리미엄 가격 정당화", "선물/이벤트 수요 흡수", "SNS 사진 촬영 명소", "브랜드 가치 극대화"}',
 '{"높은 인테리어 비용", "대리석 관리 어려움", "조리 공간 확보 필요"}',
 '평당 200~350만원', '한국 2025', 1),
('cafe-dessert', 'bakery-studio', 'concept',
 '오픈 키친 베이커리 카페', 'Open Kitchen Bakery Cafe',
 '제빵 과정을 통유리로 공개 + 카페 좌석 병행. 빵 굽는 모습이 콘텐츠이자 마케팅. 베이킹 클래스 공간 겸용.',
 'Baking process visible through glass + cafe seating. Baking is content and marketing. Space doubles as baking class venue.',
 'Factory', '{"오픈키친", "베이킹클래스", "체험"}',
 '{"제빵 과정이 무료 마케팅", "베이킹 클래스 부수입", "신뢰감 형성", "SNS 콘텐츠 자동 생산"}',
 '{"넓은 면적 필요 (30평+)", "위생 관리 강화 필요", "소음/열 관리"}',
 '평당 180~280만원', '한국 2025', 2),
('cafe-dessert', 'bakery-studio', 'concept',
 '미니멀 동네 빵집', 'Minimal Neighborhood Bakery',
 '화이트+라이트 우드 + 심플한 진열대. 소규모 10~15평. 시그니처 빵 3~5종 집중. 동네 단골 밀착형.',
 'White + light wood + simple displays. Small 10-15 pyeong. Focus on 3-5 signature breads. Neighborhood regular customer focused.',
 'Home', '{"동네빵집", "소규모", "단골"}',
 '{"소자본 창업 가능", "시그니처 빵으로 차별화", "단골 고객 형성 용이", "운영 효율 최적"}',
 '{"매출 규모 한계", "메뉴 다양성 부족", "대형 베이커리와 경쟁"}',
 '평당 100~160만원', '한국 2025', 3);

-- ╔═══════════════════════════════════════════════════════════════╗
-- ║  7. BEAUTY: 네일 스튜디오 (nail-studio)                      ║
-- ╚═══════════════════════════════════════════════════════════════╝
INSERT INTO interior_design_guides (category_id, sub_industry_id, guide_type, name_ko, name_en, description_ko, description_en, icon_name, tags, pros, cons, cost_range_ko, trend_source, priority) VALUES
-- 자재 6개
('beauty', 'nail-studio', 'material',
 '네일 시술 테이블 (흡진기 내장)', 'Nail Table with Dust Collector',
 '흡진기(더스트 콜렉터) 내장형 시술 테이블. LED 각도 조절 조명 포함. 네일 파우더 비산 방지로 위생과 고객 만족의 기본.',
 'Built-in dust collector table with adjustable LED lighting. Prevents nail powder dispersion for basic hygiene and client satisfaction.',
 'Star', '{"네일", "위생", "흡진기"}', NULL, NULL, '테이블당 50~150만원', '한국 2025', 1),
('beauty', 'nail-studio', 'material',
 'UV/LED 젤 램프 스테이션', 'UV/LED Gel Lamp Station',
 '각 시술 테이블에 고정형 UV/LED 램프. 48W 이상 듀얼 광원. 경화 속도와 고객 편의 동시 확보.',
 'Fixed UV/LED lamp at each table. 48W+ dual light source. Ensures curing speed and client convenience.',
 'Lightbulb', '{"젤네일", "UV", "장비"}', NULL, NULL, '대당 5~15만원', '한국 2025', 2),
('beauty', 'nail-studio', 'material',
 '폴리시 디스플레이 월', 'Polish Display Wall',
 '컬러 젤/폴리시를 색상별로 진열하는 벽면 선반. 고객이 직접 고르는 경험 제공. 조명과 함께 설치 시 시각 효과 극대화.',
 'Wall shelves displaying color gels/polishes by hue. Provides hands-on color selection experience. Maximizes visual impact with lighting.',
 'Palette', '{"컬러", "디스플레이", "선택"}', NULL, NULL, '벽면 선반 세트 30~100만원', '한국 2025', 3),
('beauty', 'nail-studio', 'material',
 '페디큐어 스파 체어', 'Pedicure Spa Chair',
 '발 마사지 + 온수 족욕 기능 내장 리클라이닝 체어. 고객 편안함이 재방문율에 직결. 배관 공사 필요.',
 'Reclining chair with foot massage + warm water footbath. Client comfort directly impacts return rate. Plumbing work required.',
 'Home', '{"페디큐어", "스파", "편안함"}', NULL, NULL, '체어당 80~250만원', '한국 2025', 4),
('beauty', 'nail-studio', 'material',
 '환기 시스템 (HEPA 필터)', 'Ventilation System (HEPA Filter)',
 '네일 시술 시 발생하는 화학물질(아세톤·아크릴) 제거용. 각 테이블별 국소 배기 + 전체 환기. HEPA 필터로 미세먼지 제거.',
 'Removes chemicals (acetone, acrylic) from nail procedures. Per-table local exhaust + room ventilation. HEPA filter for fine dust removal.',
 'Wind', '{"환기", "건강", "필수"}', NULL, NULL, '시스템 전체 100~300만원', '글로벌 2025', 5),
('beauty', 'nail-studio', 'material',
 '대기 공간 소파 & 잡지 선반', 'Waiting Area Sofa & Magazine Shelf',
 '시술 대기 고객을 위한 편안한 1-2인 소파. 네일 아트 잡지·트렌드북 비치. 벽면 거울로 공간감 확보.',
 'Comfortable 1-2 seat sofa for waiting clients. Nail art magazines and trendbooks. Wall mirror for spatial feel.',
 'Home', '{"대기", "편안함", "소파"}', NULL, NULL, '소파 30~80만원 + 선반 10~30만원', '한국 2025', 6),

-- 컨셉 3개
('beauty', 'nail-studio', 'concept',
 '페미닌 핑크 & 마블', 'Feminine Pink & Marble',
 '핑크+화이트+대리석 패턴. 네일아트의 정교함을 반영하는 깔끔하고 고급스러운 공간. 로즈골드 악센트.',
 'Pink + white + marble pattern. Clean and luxurious space reflecting nail art precision. Rose gold accents.',
 'Palette', '{"여성", "핑크", "고급"}',
 '{"MZ 여성 타겟 최적", "SNS 사진 촬영 유도", "프리미엄 가격 정당화", "청결한 이미지 전달"}',
 '{"트렌드 변화에 취약 가능", "남성 고객 진입 장벽", "대리석 관리 비용"}',
 '평당 120~200만원', '한국 2025', 1),
('beauty', 'nail-studio', 'concept',
 '미니멀 화이트 네일바', 'Minimal White Nail Bar',
 '화이트+우드+간접 조명의 심플한 공간. 폴리시 컬러가 돋보이는 무채색 배경. 1인 운영에 최적화.',
 'Simple space with white + wood + ambient lighting. Neutral background making polish colors stand out. Optimized for solo operation.',
 'Layers', '{"미니멀", "1인운영", "심플"}',
 '{"소자본 창업 가능", "유지 관리 용이", "폴리시 컬러 돋보임", "시대 불문 디자인"}',
 '{"차별화 어려움", "개성 부족 가능", "감성적 요소 약함"}',
 '평당 80~140만원', '한국 2025', 2),
('beauty', 'nail-studio', 'concept',
 '럭셔리 부티크 네일살롱', 'Luxury Boutique Nail Salon',
 '다크 톤(네이비/차콜) + 골드 악센트 + 벨벳 소파 + 샹들리에. 프라이빗 VIP 룸 포함. 고급 네일 서비스.',
 'Dark tones (navy/charcoal) + gold accents + velvet sofa + chandelier. Private VIP room included. Premium nail services.',
 'Crown', '{"럭셔리", "VIP", "프리미엄"}',
 '{"최고 객단가 (5만원+)", "VIP 고객 충성도 높음", "입소문 마케팅 효과", "브랜드 가치 극대화"}',
 '{"높은 초기 투자", "좁은 타겟층", "유지 관리 비용 높음"}',
 '평당 200~350만원', '글로벌 2025', 3);

-- ╔═══════════════════════════════════════════════════════════════╗
-- ║  8. BEAUTY: 피부관리실 (skin-care-room)                      ║
-- ╚═══════════════════════════════════════════════════════════════╝
INSERT INTO interior_design_guides (category_id, sub_industry_id, guide_type, name_ko, name_en, description_ko, description_en, icon_name, tags, pros, cons, cost_range_ko, trend_source, priority) VALUES
-- 자재 6개
('beauty', 'skin-care-room', 'material',
 '유압식 관리 베드', 'Hydraulic Treatment Bed',
 '높이 조절 가능한 유압식 베드. 전동형 대비 가성비 좋고 고장 적음. 메모리폼 매트리스로 고객 편안함 극대화.',
 'Height-adjustable hydraulic bed. Better cost-performance and fewer breakdowns than electric. Memory foam mattress for maximum client comfort.',
 'Home', '{"베드", "관리", "편안함"}', NULL, NULL, '베드당 80~250만원', '한국 2025', 1),
('beauty', 'skin-care-room', 'material',
 '디밍 조명 시스템', 'Dimming Light System',
 '밝기 조절 가능한 LED 간접 조명. 상담 시 밝게, 시술 시 어둡게 자동 전환. 고객 이완에 필수적.',
 'Adjustable LED ambient lighting. Bright for consultation, dim for treatment. Essential for client relaxation.',
 'Lightbulb', '{"조명", "이완", "분위기"}', NULL, NULL, '룸당 30~80만원', '한국 2025', 2),
('beauty', 'skin-care-room', 'material',
 '제품 디스플레이 선반 (조명 내장)', 'Product Display Shelf (Lit)',
 '화장품·앰플·마스크팩 진열 선반. LED 조명 내장으로 제품이 돋보이게. 리테일 매출 유도 목적.',
 'Shelf for cosmetics, ampoules, masks. Built-in LED makes products stand out. Drives retail sales.',
 'Layers', '{"제품", "디스플레이", "리테일"}', NULL, NULL, '선반 세트 50~150만원', '한국 2025', 3),
('beauty', 'skin-care-room', 'material',
 '타월 워머 & 스티머', 'Towel Warmer & Steamer',
 '따뜻한 타월 제공용 워머 + 페이셜 스티머. 스파 경험의 기본. 소형 스티머는 이동식으로 활용.',
 'Towel warmer for warm towels + facial steamer. Basics of spa experience. Small steamer as portable option.',
 'Layers', '{"타월", "스티머", "스파"}', NULL, NULL, '워머 20~50만원 + 스티머 30~100만원', '한국 2025', 4),
('beauty', 'skin-care-room', 'material',
 '프라이버시 커튼/파티션', 'Privacy Curtain/Partition',
 '개별 관리 베드 간 프라이버시 확보용. 방염 커튼 또는 반투명 파티션. 공간 효율과 프라이버시 균형.',
 'Privacy between treatment beds. Fire-retardant curtains or semi-transparent partitions. Balance between space efficiency and privacy.',
 'Shield', '{"프라이버시", "파티션", "방염"}', NULL, NULL, '베드당 10~30만원', '한국 2025', 5),
('beauty', 'skin-care-room', 'material',
 '상담 데스크 & 피부 분석기', 'Consultation Desk & Skin Analyzer',
 '고객 피부 상태 분석 후 맞춤 관리 제안용 데스크. 피부 분석기(UV/편광 카메라) 세팅으로 전문성 어필.',
 'Desk for custom treatment recommendations after skin analysis. Skin analyzer (UV/polarized camera) setup for professional appeal.',
 'Monitor', '{"상담", "분석", "전문성"}', NULL, NULL, '데스크 30~80만원 + 분석기 100~500만원', '한국 2025', 6),

-- 컨셉 3개
('beauty', 'skin-care-room', 'concept',
 '스파 & 힐링 컨셉', 'Spa & Healing Concept',
 '어두운 톤(그레이/베이지) + 간접 조명 + 아로마 + 자연 소재(우드·스톤). 도심 속 힐링 공간. 고객이 잠들 수 있는 편안함.',
 'Dark tones (gray/beige) + ambient lighting + aroma + natural materials (wood, stone). Urban healing space. Comfort where clients fall asleep.',
 'Leaf', '{"힐링", "스파", "편안함"}',
 '{"프리미엄 가격 정당화", "재방문율 향상 (이완 경험)", "입소문 마케팅 효과", "차별화된 경험 제공"}',
 '{"관리비 높음 (향초/아로마 소모)", "공간 분리에 면적 필요", "청소/위생 관리 강화 필수"}',
 '평당 150~280만원', '한국 2025', 1),
('beauty', 'skin-care-room', 'concept',
 '클리닉 화이트 에스테틱', 'Clinic White Esthetic',
 '화이트+크롬+유리의 의료적 깔끔함. 피부과 느낌의 전문성. 최신 기기 디스플레이로 기술력 어필.',
 'White + chrome + glass medical cleanliness. Dermatology-like professionalism. Latest equipment display for technical appeal.',
 'Shield', '{"클리닉", "전문성", "의료감"}',
 '{"전문성·신뢰감 극대화", "의료 에스테틱과 차별화", "청결 이미지 자동 확보", "장비 투자 대비 효과적"}',
 '{"차가운 느낌으로 이완 부족", "가정적 분위기 부족", "고가 장비 필요"}',
 '평당 120~200만원', '한국 2025', 2),
('beauty', 'skin-care-room', 'concept',
 '프라이빗 부티크 스킨케어', 'Private Boutique Skincare',
 '완전 개별 룸(5~8평/룸) + 프리미엄 마감. 예약제 운영. 1:1 맞춤 관리. VIP 고객 특화.',
 'Fully private rooms (5-8 pyeong each) + premium finish. By-appointment only. 1:1 customized care. VIP client specialized.',
 'Crown', '{"프라이빗", "VIP", "맞춤"}',
 '{"최고 객단가 (10만원+/회)", "충성 고객 형성", "프라이버시 완벽 보장", "프리미엄 브랜딩"}',
 '{"넓은 면적 필요 (20평+)", "높은 임대료 부담", "고객 수 제한 (예약제)"}',
 '평당 200~350만원', '글로벌 2025', 3);

-- ╔═══════════════════════════════════════════════════════════════╗
-- ║  9. FITNESS: 요가 스튜디오 (yoga-studio)                     ║
-- ╚═══════════════════════════════════════════════════════════════╝
INSERT INTO interior_design_guides (category_id, sub_industry_id, guide_type, name_ko, name_en, description_ko, description_en, icon_name, tags, pros, cons, cost_range_ko, trend_source, priority) VALUES
-- 자재 6개
('fitness', 'yoga-studio', 'material',
 '코르크 바닥재', 'Cork Flooring',
 '맨발 활동에 최적. 따뜻하고 쿠셔닝 있으며 천연 항균 성분 포함. 소음 흡수로 명상에 적합한 환경 조성.',
 'Optimal for barefoot activities. Warm, cushioned, and naturally antimicrobial. Sound absorption creates meditation-friendly environment.',
 'Leaf', '{"바닥", "코르크", "친환경"}', NULL, NULL, '평당 8~18만원', '글로벌 2025', 1),
('fitness', 'yoga-studio', 'material',
 '전면 거울 벽', 'Full Mirror Wall',
 '한쪽 벽면 전체 거울. 수련자가 자세를 교정할 수 있도록 지원. 공간이 2배로 넓어 보이는 시각 효과.',
 'Full wall mirror for practitioners to check alignment. Visual effect of doubling the perceived space.',
 'Layers', '{"거울", "자세교정", "공간감"}', NULL, NULL, '평당 10~20만원', '한국 2025', 2),
('fitness', 'yoga-studio', 'material',
 '요가 소품 수납장', 'Yoga Prop Storage',
 '매트·블록·스트랩·볼스터 보관용 벽면 수납장. 수업 전후 정리가 빠르도록 칸막이 분류. 원목 또는 화이트 마감.',
 'Wall storage for mats, blocks, straps, bolsters. Compartmentalized for quick pre/post-class organizing. Wood or white finish.',
 'Layers', '{"수납", "소품", "정리"}', NULL, NULL, '수납장 세트 50~150만원', '한국 2025', 3),
('fitness', 'yoga-studio', 'material',
 '블루투스 천장 스피커 시스템', 'Bluetooth Ceiling Speaker System',
 '명상 음악·자연 소리 재생용 고음질 스피커. 천장 매립형으로 깔끔. 균일한 음향 분배.',
 'High-quality speakers for meditation music and nature sounds. Ceiling-mounted for clean look. Even sound distribution.',
 'Layers', '{"스피커", "음악", "명상"}', NULL, NULL, '시스템 전체 50~200만원', '한국 2025', 4),
('fitness', 'yoga-studio', 'material',
 '자연광 최적화 (대형 채광창)', 'Natural Light Optimization (Large Windows)',
 '요가 스튜디오는 자연광이 핵심. 대형 창문 또는 천창(스카이라이트). UV 차단 필름 + 롤블라인드로 조절 가능.',
 'Natural light is key for yoga studios. Large windows or skylight. UV-blocking film + roller blinds for control.',
 'Lightbulb', '{"자연광", "창문", "채광"}', NULL, NULL, '창문 100~500만원 (규모에 따라)', '한국 2025', 5),
('fitness', 'yoga-studio', 'material',
 '탈의실 & 샤워 부스', 'Changing Room & Shower Booth',
 '수련 전후 착·탈의 공간. 로커 + 벤치 + 거울 + 샤워 부스. 최소 2~3칸 확보. 환기 필수.',
 'Pre/post-practice changing area. Lockers + bench + mirror + shower booth. Minimum 2-3 stalls. Ventilation essential.',
 'Home', '{"탈의실", "샤워", "편의"}', NULL, NULL, '세트 200~500만원', '한국 2025', 6),

-- 컨셉 3개
('fitness', 'yoga-studio', 'concept',
 '젠 미니멀 스튜디오', 'Zen Minimal Studio',
 '밝은 화이트 + 원목 + 간접 조명 + 대형 거울. 넓은 공간감과 차분한 분위기. 소품은 최소화하고 공간 자체로 승부.',
 'Bright white + wood + ambient lighting + large mirrors. Spacious calm atmosphere. Minimal props, the space itself is the selling point.',
 'Leaf', '{"선(禪)", "미니멀", "명상"}',
 '{"수업 집중도 향상", "다양한 요가 스타일 호환 (하타/빈야사/음양)", "촬영 적합", "청결 유지 용이"}',
 '{"공간 효율 낮음 (넓은 면적 필요)", "냉난방 비용 높음", "거울 관리/세척 필요"}',
 '평당 80~150만원', '한국 2025', 1),
('fitness', 'yoga-studio', 'concept',
 '바이오필릭 웰니스 스튜디오', 'Biophilic Wellness Studio',
 '실내 식물 + 자연광 + 대나무/코르크/울 등 자연 소재. 숲속 요가 느낌. 명상·이완 수업에 최적.',
 'Indoor plants + natural light + bamboo/cork/wool natural materials. Forest yoga feeling. Optimal for meditation and relaxation classes.',
 'Leaf', '{"바이오필릭", "자연", "웰니스"}',
 '{"독보적 차별화", "고가 수업료 정당화", "이완·명상 수업 최적", "인스타그래머블"}',
 '{"식물 관리 비용 월 10~30만원", "벌레·곰팡이 관리", "넓은 면적+높은 층고 필요"}',
 '평당 120~220만원', '글로벌 2025', 2),
('fitness', 'yoga-studio', 'concept',
 '핫요가/인프라레드 스튜디오', 'Hot Yoga / Infrared Studio',
 '적외선 패널 히팅 + 습도 조절 + 방습 마감. 비크람/핫요가 전용 공간. 바닥 방수 처리와 환기가 핵심.',
 'Infrared panel heating + humidity control + moisture-proof finish. Dedicated Bikram/hot yoga space. Floor waterproofing and ventilation are key.',
 'Zap', '{"핫요가", "적외선", "전문"}',
 '{"전문 수업으로 높은 수업료", "겨울철 수요 폭증", "차별화 극강", "건강 효과 어필"}',
 '{"고가 설비 (적외선 패널)", "전기료 높음", "방수/방습 시공 필수"}',
 '평당 150~280만원', '한국 2025', 3);

-- ╔═══════════════════════════════════════════════════════════════╗
-- ║  10. FITNESS: PT전문 헬스장 (pt-gym)                         ║
-- ╚═══════════════════════════════════════════════════════════════╝
INSERT INTO interior_design_guides (category_id, sub_industry_id, guide_type, name_ko, name_en, description_ko, description_en, icon_name, tags, pros, cons, cost_range_ko, trend_source, priority) VALUES
-- 자재 6개
('fitness', 'pt-gym', 'material',
 '탄성 고무 바닥 (에버롤 20mm+)', 'Rubber Floor Mat (Everroll 20mm+)',
 '중량 운동 시 바닥 보호 + 소음 감소 + 충격 흡수. 20mm 이상 고밀도 고무 매트 필수. 색상으로 구역 구분 가능.',
 'Floor protection + noise reduction + shock absorption for weightlifting. 20mm+ high-density rubber mat required. Colors can define zones.',
 'Shield', '{"바닥", "고무", "안전"}', NULL, NULL, '평당 5~15만원', '한국 2025', 1),
('fitness', 'pt-gym', 'material',
 '대형 전면 거울 + 간접 조명', 'Large Wall Mirror + Ambient Light',
 '운동 자세 확인용 전면 거울. 상하부 LED 간접 조명으로 입체적 공간미. 거울 테두리 보호대 설치 필수.',
 'Full wall mirror for exercise form check. Upper/lower LED ambient lighting for spatial depth. Edge protectors required.',
 'Layers', '{"거울", "조명", "자세"}', NULL, NULL, '거울 평당 10~20만원 + 조명 20~50만원', '한국 2025', 2),
('fitness', 'pt-gym', 'material',
 '웨이트 장비 & 기능성 트레이닝 리그', 'Weight Equipment & Functional Training Rig',
 '파워랙·케이블머신·덤벨랙 + 풀업바/TRX/배틀로프 등 기능성 리그. PT 프로그램 다양성 확보.',
 'Power rack, cable machine, dumbbell rack + pull-up bar/TRX/battle rope functional rig. Ensures PT program diversity.',
 'Zap', '{"장비", "웨이트", "기능성"}', NULL, NULL, '기본 세트 3000~8000만원', '한국 2025', 3),
('fitness', 'pt-gym', 'material',
 '벽면 수납 랙 (소도구)', 'Wall-mounted Equipment Rack',
 '덤벨·케틀벨·메디신볼·밴드 등 소도구 수납. 바닥 공간 확보를 위한 벽면 고정형. 미관과 정리 동시.',
 'Storage for dumbbells, kettlebells, medicine balls, bands. Wall-mounted to free floor space. Aesthetics and organization combined.',
 'Layers', '{"수납", "정리", "벽면"}', NULL, NULL, '유닛당 30~100만원', '글로벌 2025', 4),
('fitness', 'pt-gym', 'material',
 '모티베이션 월 (그래피티/레터링)', 'Motivation Wall (Graffiti/Lettering)',
 '운동 동기 부여 문구를 벽면에 대형 레터링 또는 그래피티 아트. 브랜드 컬러 포인트. SNS 포토존 겸용.',
 'Large lettering or graffiti art with motivational quotes on walls. Brand color accents. Doubles as SNS photo zone.',
 'Star', '{"동기부여", "그래피티", "브랜딩"}', NULL, NULL, '벽면당 50~200만원', '글로벌 2025', 5),
('fitness', 'pt-gym', 'material',
 '인조잔디 펑셔널 트레이닝 존', 'Turf Functional Training Zone',
 '썰매밀기·스프린트·민첩성 훈련용 인조잔디 레인. 길이 8~15m. 고무 바닥과 색상 대비로 구역 구분.',
 'Artificial turf lane for sled push, sprint, agility training. 8-15m length. Color contrast with rubber floor defines zones.',
 'Leaf', '{"인조잔디", "기능성", "스프린트"}', NULL, NULL, '평당 8~15만원', '글로벌 2025', 6),

-- 컨셉 3개
('fitness', 'pt-gym', 'concept',
 '인더스트리얼 짐', 'Industrial Gym',
 '노출 콘크리트 + 메탈 프레임 + 어두운 톤(블랙/차콜). 강한 운동 의지를 자극하는 하드코어 분위기. 투자 대비 임팩트 최고.',
 'Exposed concrete + metal frame + dark tones (black/charcoal). Hardcore atmosphere stimulating training drive. Best impact per investment.',
 'Zap', '{"하드코어", "인더스트리얼", "근력"}',
 '{"운동 동기 부여 극대화", "남성 고객 강력 선호", "노출 마감으로 공사비 절감", "내구성 우수 (긁힘/충격 무관)"}',
 '{"여성 고객 접근성 낮음", "조명 부족 시 안전 위험", "먼지 관리 어려움"}',
 '평당 60~120만원', '한국 2025', 1),
('fitness', 'pt-gym', 'concept',
 '부티크 PT 스튜디오', 'Boutique PT Studio',
 '밝은 톤(화이트/그레이) + 우드 악센트 + 세련된 조명. 여성·초보 친화적. 소규모 10~20평 프리미엄.',
 'Bright tones (white/gray) + wood accents + sophisticated lighting. Female and beginner friendly. Small 10-20 pyeong premium.',
 'Star', '{"부티크", "프리미엄", "여성친화"}',
 '{"여성 고객 유치 (헬스장의 60%)", "프리미엄 PT 가격 정당화", "소자본 창업 가능", "깔끔한 브랜드 이미지"}',
 '{"좁은 공간으로 동시 수업 제한", "대형 기구 배치 어려움", "남성 고객 유출 가능"}',
 '평당 100~180만원', '한국 2025', 2),
('fitness', 'pt-gym', 'concept',
 '하이테크 스마트짐', 'Hi-Tech Smart Gym',
 'LED 네온 조명 + 대형 TV 운동 가이드 + 체성분 분석기 + 스마트 미러. 최신 기술로 차별화된 트레이닝 경험.',
 'LED neon lighting + large TV workout guides + body composition analyzer + smart mirror. Tech-differentiated training experience.',
 'Monitor', '{"하이테크", "스마트", "최신"}',
 '{"차별화 극강 (스마트 미러/체성분)", "MZ세대 유인 효과", "데이터 기반 PT 가능", "SNS 바이럴 유도"}',
 '{"높은 초기 투자 (스마트 기기)", "기기 유지보수 비용", "기술 트렌드 변화 빠름"}',
 '평당 120~250만원', '글로벌 2025', 3);
