insert into public.market_location_signals (
  region_key,
  region_name,
  district_name,
  category_id,
  search_keywords,
  market_style,
  rent_band,
  competition_level,
  demand_level,
  access_level,
  category_fit_level,
  base_score,
  summary,
  evidence,
  freshness_status,
  last_checked_at,
  next_review_at,
  notes
)
values
  (
    'seongsu-cafe',
    '성수동',
    '성동구',
    'cafe-dessert',
    array['성수', '성수동', '서울숲'],
    'destination',
    'high',
    'high',
    'high',
    'strong',
    'strong',
    87,
    '브랜드형 카페와 디저트 업종이 노출과 목적 방문을 같이 노리기 좋은 상권입니다.',
    '{"reasons":["20~30대 목적 방문 수요가 강함","브랜드 노출 효과가 큼"],"warnings":["임대료와 경쟁 강도가 높음"]}'::jsonb,
    'fresh',
    '2026-03-19T09:00:00+09:00',
    '2026-03-26T09:00:00+09:00',
    '계약 직전 임대료 변동 재확인 필요'
  ),
  (
    'mangwon-food',
    '망원동',
    '마포구',
    'food',
    array['망원', '망원동'],
    'residential',
    'mid',
    'mid',
    'mid',
    'balanced',
    'strong',
    81,
    '동네 반복 수요와 식사형 외식에 비교적 안정적인 상권입니다.',
    '{"reasons":["주거형 반복 방문 구조가 안정적","초기 비용 통제가 비교적 쉬움"],"warnings":["빠른 확장 속도는 다소 느릴 수 있음"]}'::jsonb,
    'review_soon',
    '2026-03-17T09:00:00+09:00',
    '2026-03-24T09:00:00+09:00',
    '근린 상권 경쟁도 재확인 필요'
  ),
  (
    'pangyo-office-food',
    '판교',
    '성남시',
    'food',
    array['판교', '판교역'],
    'office',
    'mid-high',
    'mid',
    'high',
    'strong',
    'strong',
    84,
    '점심 중심 외식과 빠른 회전형 식사 모델이 강한 오피스 상권입니다.',
    '{"reasons":["직장인 점심 수요가 뚜렷함","빠른 유입과 객수 확보에 유리"],"warnings":["주말 수요 편차가 큼"]}'::jsonb,
    'fresh',
    '2026-03-19T09:00:00+09:00',
    '2026-03-26T09:00:00+09:00',
    null
  ),
  (
    'yeongtong-education',
    '영통',
    '수원시',
    'education',
    array['영통', '영통구'],
    'residential',
    'mid',
    'mid-low',
    'mid',
    'balanced',
    'strong',
    82,
    '가족 단위 거주 수요가 강해 교육형 업종과 잘 맞는 지역입니다.',
    '{"reasons":["학부모 기반 수요가 안정적","재등록 구조를 만들기 쉬움"],"warnings":["브랜드 인지도 확보까지 시간이 걸릴 수 있음"]}'::jsonb,
    'fresh',
    '2026-03-18T09:00:00+09:00',
    '2026-03-25T09:00:00+09:00',
    null
  ),
  (
    'jeonpo-retail',
    '전포',
    '부산진구',
    'retail',
    array['전포', '전포동'],
    'destination',
    'mid-high',
    'high',
    'high',
    'strong',
    'strong',
    83,
    '브랜드형 소매와 발견형 소비가 잘 붙는 목적 방문 상권입니다.',
    '{"reasons":["브랜드 발견형 소비가 활발함","공간 연출과 SNS 확산에 유리"],"warnings":["경쟁이 빠르게 심화될 수 있음"]}'::jsonb,
    'review_soon',
    '2026-03-16T09:00:00+09:00',
    '2026-03-23T09:00:00+09:00',
    '신규 출점 증가 추이 재확인 필요'
  ),
  (
    'songdo-fitness',
    '송도',
    '연수구',
    'fitness',
    array['송도', '송도국제도시'],
    'residential',
    'mid-high',
    'mid',
    'mid',
    'balanced',
    'strong',
    79,
    '주거 밀집과 중산층 소비 기반이 있어 피트니스와 웰니스 업종 검토에 적합합니다.',
    '{"reasons":["장기 회원 구조를 만들기 좋음","가족 단위 생활권 수요가 존재"],"warnings":["초기 임대료와 시설 투자 부담이 있음"]}'::jsonb,
    'fresh',
    '2026-03-18T09:00:00+09:00',
    '2026-03-25T09:00:00+09:00',
    null
  )
on conflict (region_key) do update
set
  region_name = excluded.region_name,
  district_name = excluded.district_name,
  category_id = excluded.category_id,
  search_keywords = excluded.search_keywords,
  market_style = excluded.market_style,
  rent_band = excluded.rent_band,
  competition_level = excluded.competition_level,
  demand_level = excluded.demand_level,
  access_level = excluded.access_level,
  category_fit_level = excluded.category_fit_level,
  base_score = excluded.base_score,
  summary = excluded.summary,
  evidence = excluded.evidence,
  freshness_status = excluded.freshness_status,
  last_checked_at = excluded.last_checked_at,
  next_review_at = excluded.next_review_at,
  notes = excluded.notes,
  is_active = true,
  updated_at = now();
