-- ─── 지원 프로그램 시드 데이터 ─────────────────────────────────────────────────
-- 정부 + 대기업 + 민간/재단 + 지자체 + 대회/경진대회

insert into public.support_programs (
  program_key, category, name_ko, name_en, organizer_ko, organizer_en,
  target_ko, target_en, benefit_ko, benefit_en, amount,
  season_ko, season_en, url, for_small_biz, for_franchise, highlight,
  max_age, business_year_min, business_year_max, industries, regions,
  application_status, data_year, freshness_status, last_checked_at, next_review_at
) values

-- ═══════════════════════════════════════════════════════════════════════════════
-- GOVERNMENT (정부)
-- ═══════════════════════════════════════════════════════════════════════════════

('pre-startup-package', 'government',
 '예비창업패키지', 'Pre-Startup Package',
 '창업진흥원 (중소벤처기업부)', 'KISED (MSS)',
 '혁신 기술 아이디어를 가진 예비창업자', 'Pre-founders with innovative tech ideas',
 '시제품 제작, 마케팅, 지식재산권 등 사업화자금 + 멘토링', 'Prototyping, marketing, IP registration + mentoring',
 '최대 1억원 (평균 5,000만원)',
 '매년 초 공고 (1~3월)', 'Annual early-year notice (Jan-Mar)',
 'https://www.kised.or.kr/menu.es?mid=a10205010000',
 true, false, true,
 null, 0, 0, null, null,
 'upcoming', '2026', 'fresh', now(), now() + interval '90 days'),

('early-startup-package', 'government',
 '초기창업패키지', 'Early Startup Package',
 '창업진흥원 (중소벤처기업부)', 'KISED (MSS)',
 '창업 3년 이내 기업', 'Companies within 3 years of founding',
 '사업화자금 + 전담 멘토링 + 투자 연계', 'Biz funds + dedicated mentoring + investment linkage',
 '일반 최대 1억, 딥테크 최대 1.5억',
 '매년 초 공고', 'Annual early-year notice',
 'https://www.kised.or.kr/menu.es?mid=a10205020000',
 true, false, true,
 null, 0, 3, null, null,
 'upcoming', '2026', 'fresh', now(), now() + interval '90 days'),

('youth-startup-fund', 'government',
 '청년전용 창업자금', 'Youth Startup Fund',
 '중소벤처기업진흥공단', 'KOSMES',
 '만 39세 이하, 업력 3년 미만', 'Under 39, less than 3 years in business',
 '저금리 융자 (연 2.5% 고정금리)', 'Low-interest loan (2.5% fixed)',
 '최대 1억원 (제조업 2억)',
 '상시 신청', 'Year-round applications',
 'https://start.kosmes.or.kr',
 true, true, true,
 39, 0, 3, null, null,
 'open', '2026', 'fresh', now(), now() + interval '90 days'),

('youth-startup-academy', 'government',
 '청년창업사관학교', 'Youth Startup Academy',
 '중소벤처기업진흥공단', 'KOSMES',
 '만 39세 이하, 창업 3년 이내', 'Under 39, within 3 years of founding',
 '사무공간 + 교육 + 사업비 최대 1억원 패키지 지원', 'Office space + education + up to 100M KRW package',
 '최대 1억원',
 '매년 초 공고', 'Annual early-year notice',
 'https://start.kosmes.or.kr',
 true, false, false,
 39, 0, 3, null, null,
 'upcoming', '2026', 'fresh', now(), now() + interval '90 days'),

('sme-policy-fund', 'government',
 '소상공인 정책자금', 'SME Policy Fund',
 '소상공인시장진흥공단', 'SEMAS',
 '소상공인 요건 충족 사업자', 'Registered small business owners',
 '저금리 융자 (운전·시설자금)', 'Low-interest loan (working capital & facilities)',
 '운전 최대 5억, 시설 포함 최대 10억',
 '상시 신청 (연 초 공고)', 'Year-round (annual notice)',
 'https://www.semas.or.kr/web/SUP01/SUP0103/SUP010301.kmdc',
 true, true, false,
 null, null, null, null, null,
 'open', '2026', 'fresh', now(), now() + interval '90 days'),

('startup-leap-package', 'government',
 '창업도약패키지', 'Startup Leap Package',
 '창업진흥원', 'KISED',
 '창업 3~7년 기업 (매출 정체·모델 한계)', '3-7yr companies (revenue plateau)',
 '사업모델 재설계 + 투자 연계 + 스케일업', 'Biz model redesign + investment + scale-up',
 '최대 3억원',
 '매년 초 공고', 'Annual early-year notice',
 'https://www.kised.or.kr/menu.es?mid=a10205030000',
 true, false, false,
 null, 3, 7, null, null,
 'upcoming', '2026', 'fresh', now(), now() + interval '90 days'),

('tips-program', 'government',
 'TIPS (기술창업 투자프로그램)', 'TIPS (Tech Incubator Program for Startup)',
 '중소벤처기업부', 'MSS',
 'TIPS 운영사로부터 투자·추천받은 기술 스타트업', 'Tech startups invested/recommended by TIPS operators',
 'R&D 자금 + 창업사업화 + 해외마케팅', 'R&D funds + commercialization + global marketing',
 'R&D 최대 8억원 (2026년 증액)',
 '상시 (운영사 추천 후 신청)', 'Year-round (after operator recommendation)',
 'https://www.jointips.or.kr',
 false, false, true,
 null, 0, 7, null, null,
 'open', '2026', 'fresh', now(), now() + interval '90 days'),

('hope-return-package', 'government',
 '희망리턴패키지', 'Hope Return Package',
 '소상공인시장진흥공단', 'SEMAS',
 '폐업 예정·폐업 후 재기 희망 소상공인', 'SMEs planning closure or restarting after closure',
 '폐업 컨설팅 + 재취업·재창업 교육 + 사업정리자금', 'Closure consulting + retraining + settlement funds',
 '사업정리자금 최대 200만원 + 교육',
 '상시 신청', 'Year-round',
 'https://www.semas.or.kr',
 true, true, false,
 null, null, null, null, null,
 'open', '2026', 'fresh', now(), now() + interval '90 days'),

('around-x', 'government',
 '어라운드엑스 (글로벌 기업 협업)', 'Around X (Global Corp Collaboration)',
 '중소벤처기업부', 'MSS',
 '글로벌 기업과 협업 가능한 스타트업', 'Startups that can collaborate with global corporations',
 '사업화 자금 최대 2억 + NVIDIA·OpenAI·Google 등 17개 파트너 연계', 'Up to 200M fund + 17 partners incl. NVIDIA, OpenAI, Google',
 '최대 2억원',
 '매년 초 공고 (2~3월)', 'Annual early-year (Feb-Mar)',
 'https://www.bizinfo.go.kr',
 false, false, false,
 null, null, null, null, null,
 'upcoming', '2026', 'fresh', now(), now() + interval '90 days'),

-- ═══════════════════════════════════════════════════════════════════════════════
-- CORPORATE (대기업)
-- ═══════════════════════════════════════════════════════════════════════════════

('samsung-clab-outside', 'corporate',
 '삼성 C-Lab Outside', 'Samsung C-Lab Outside',
 '삼성전자', 'Samsung Electronics',
 '혁신 기술 보유 외부 스타트업', 'External startups with innovative technology',
 'PoC 지원금 최대 1억원 (지분 없음) + CES 출품 + 삼성 특허 무상 이전 + 컨설팅', 'Up to 100M KRW PoC fund (no equity) + CES + Samsung patent licensing + consulting',
 '최대 1억원',
 '연 1회 (3~4월 모집)', 'Annual (Mar-Apr)',
 'https://www.samsung.com/sec/sustainability/popup/popup_doc/AYUBw0_6ArQAIx8i/',
 false, false, true,
 null, null, null, '{ai,fintech,robotics}'::text[], null,
 'upcoming', '2026', 'fresh', now(), now() + interval '90 days'),

('samsung-fn-clab', 'corporate',
 '삼성금융 C-Lab Outside', 'Samsung Financial C-Lab Outside',
 '삼성금융네트웍스 (삼성생명·화재·카드·증권)', 'Samsung Financial Network',
 '금융 AI·핀테크·업무혁신 스타트업', 'Financial AI, fintech, operational innovation startups',
 '기본 3,000만원 + 회사별 1,000만원 우수상 + CES + 삼성벤처투자 검토', 'Base 30M + 10M best award per company + CES + Samsung VC review',
 '최대 7,000만원+',
 '2026.3.3~4.5 모집, 5개월 프로그램', '2026 Mar 3-Apr 5, 5-month program',
 'https://samsungfnstartup.com',
 false, false, false,
 null, null, null, '{ai,fintech}'::text[], null,
 'open', '2026', 'fresh', now(), now() + interval '60 days'),

('naver-d2sf', 'corporate',
 '네이버 D2SF', 'NAVER D2SF',
 '네이버', 'NAVER',
 '기술 기반 초기 스타트업 (AI·로보틱스·데이터)', 'Tech-based early startups (AI, robotics, data)',
 '시드/초기 투자 + 네이버 기술 인프라 + 멘토링', 'Seed/early investment + NAVER tech infra + mentoring',
 '투자 규모 비공개 (시드~Series A)',
 '상시 투자', 'Year-round investment',
 'https://d2startup.com/ko',
 false, false, true,
 null, null, null, '{ai,deep-tech,data}'::text[], null,
 'open', '2026', 'fresh', now(), now() + interval '90 days'),

('naver-d2sf-campus', 'corporate',
 '네이버 D2SF 캠퍼스 기술창업 공모전', 'NAVER D2SF Campus Tech Startup Competition',
 '네이버 D2SF', 'NAVER D2SF',
 '대학(원)생 (재학 또는 졸업 1년 이내, 팀원 1명 이상)', 'University students (enrolled or within 1yr of graduation)',
 '기술개발 자금 1,000만원 (지분 없음) + GPU·클라우드 500만원 + 강남/1784 작업 공간 + D2SF 직접 투자 검토', '10M dev fund (no dilution) + 5M GPU/cloud + workspace + D2SF direct investment review',
 '1,500만원+',
 '제18회: 2026.5.10 마감, 6월 면접, 7~12월 인큐베이팅', '18th: May 10 2026 deadline, Jun interview, Jul-Dec incubation',
 'https://d2startup.com/ko',
 false, false, false,
 null, 0, 1, null, null,
 'open', '2026', 'fresh', now(), now() + interval '60 days'),

('naver-cloud-greenhouse', 'corporate',
 '네이버 클라우드 그린하우스', 'Naver Cloud Greenhouse',
 '네이버클라우드', 'Naver Cloud',
 '스타트업 (다양한 단계)', 'Startups (various stages)',
 '클라우드 크레딧 최대 1억원 + 기술 아키텍처 컨설팅 + 공동 마케팅/PR/세일즈', 'Up to 100M cloud credits + tech consulting + co-marketing/PR/sales',
 '클라우드 크레딧 최대 1억원',
 '상시 신청', 'Year-round',
 'https://www.ncloud.com/v2/support/greenHouse',
 false, false, false,
 null, null, null, null, null,
 'open', '2026', 'fresh', now(), now() + interval '90 days'),

('kakao-ventures', 'corporate',
 '카카오벤처스', 'Kakao Ventures',
 '카카오벤처스', 'Kakao Ventures',
 '소프트웨어·ICT·딥테크 초기 스타트업', 'Software, ICT, deep tech early startups',
 '시드/Pre-Series A 투자 + Startup Korea 카카오 코파일럿 펀드 440억', 'Seed/Pre-A investment + Startup Korea Kakao Copilot Fund 44B KRW',
 '투자 규모 건별 상이',
 '상시 투자', 'Year-round investment',
 'https://www.kakao.vc/en',
 false, false, false,
 null, null, null, '{ai,software,deep-tech,healthcare,gaming}'::text[], null,
 'open', '2026', 'fresh', now(), now() + interval '90 days'),

('kakao-impact', 'corporate',
 '카카오임팩트 Tech for Impact LAB', 'Kakao Impact Tech for Impact LAB',
 '카카오임팩트', 'Kakao Impact',
 '사회문제 해결에 IT를 활용하는 소셜 이노베이터', 'Social innovators using IT for social problem-solving',
 'IT 전문가 매칭 + 기술 개발 지원 + 임팩트 프로젝트 협업', 'IT expert matching + tech dev support + impact project collaboration',
 null,
 '연 1회 모집', 'Annual recruitment',
 'https://www.kakaoimpact.org',
 false, false, false,
 null, null, null, null, null,
 'upcoming', '2026', 'fresh', now(), now() + interval '90 days'),

('toss-miniapp-challenge', 'corporate',
 '토스 앱인토스 미니앱 챌린지', 'Toss Apps-in-Toss Mini-App Challenge',
 '토스 (비바리퍼블리카) + CNT Tech', 'Toss (Viva Republica) + CNT Tech',
 '토스 플랫폼 내 미니앱을 만들 수 있는 초기 스타트업', 'Early startups that can build mini-apps in Toss platform',
 '토스 2,900만 MAU 유저 접근 + IAA/IAP 수익화 + 정부 연계 사업화 자금', 'Access to Toss 29M MAU + monetization + gov-linked commercialization funds',
 null,
 '2025년 8월 (연 1회)', 'August 2025 (annual)',
 'https://toss.im',
 false, false, false,
 null, null, null, null, null,
 'upcoming', '2026', 'fresh', now(), now() + interval '90 days'),

('sk-true-innovation', 'corporate',
 'SK텔레콤 트루이노베이션', 'SKT True Innovation',
 'SK텔레콤', 'SK Telecom',
 'AI·5G·IoT·클라우드·모빌리티 스타트업', 'AI, 5G, IoT, cloud, mobility startups',
 '엑셀러레이팅 + MWC/CES 공동 전시 + 투자 연계 + 글로벌 진출 지원', 'Acceleration + MWC/CES co-exhibit + investment + global expansion',
 null,
 '상시 (AI Startup Lab으로 개편 중)', 'Year-round (being renovated as AI Startup Lab)',
 'https://www.true-inno.com/',
 false, false, false,
 null, null, null, '{ai,5g,iot,cloud,mobility}'::text[], null,
 'open', '2026', 'fresh', now(), now() + interval '90 days'),

('hyundai-zer01ne', 'corporate',
 '현대차그룹 제로원 액셀러레이터', 'Hyundai ZER01NE Accelerator',
 '현대자동차그룹', 'Hyundai Motor Group',
 '모빌리티·지속가능성·물류·배터리·로보틱스 스타트업', 'Mobility, sustainability, logistics, battery, robotics startups',
 'PoC 자금 최대 5,000만원 + 제로원 펀드 투자 검토 + CES 출품', 'Up to 50M PoC fund + ZER01NE Fund investment review + CES',
 '최대 5,000만원',
 '연 1~2회 모집', '1-2 batches/year',
 'https://zer01ne.zone/',
 false, false, false,
 null, null, null, '{mobility,logistics,robotics,battery}'::text[], null,
 'upcoming', '2026', 'fresh', now(), now() + interval '90 days'),

('lotte-lcamp', 'corporate',
 '롯데벤처스 L-CAMP', 'Lotte Ventures L-CAMP',
 '롯데벤처스', 'Lotte Ventures',
 'AI·로보틱스·시니어케어 + 롯데 그룹사 시너지 스타트업', 'AI, robotics, senior care + Lotte group synergy startups',
 '롯데 계열사 PoC + 직접 투자 검토 + AWS/Azure 크레딧 + PR·회계·법률 바우처', 'Lotte affiliate PoC + investment review + cloud credits + PR/legal vouchers',
 null,
 '제14기: 2026.3.31 마감', '14th: Mar 31, 2026 deadline',
 'http://lotteventures.com/main',
 false, false, false,
 null, null, null, '{ai,robotics,food-tech}'::text[], null,
 'open', '2026', 'fresh', now(), now() + interval '60 days'),

('cj-ciat', 'corporate',
 'CJ 씨앗 (CIAT)', 'CJ CIAT',
 'CJ그룹 (제일제당·대한통운·ENM)', 'CJ Group',
 '식품·바이오·물류·엔터 분야 성장기 스타트업 (3~7년)', 'Growth-stage startups in food, bio, logistics, entertainment (3-7yr)',
 '사업화 자금 최대 3억 + CJ 계열사 협업 + 데모데이 + 글로벌 전시', 'Up to 300M fund + CJ affiliate collaboration + Demo Day + global exhibition',
 '최대 3억원',
 '연 1회 모집', 'Annual recruitment',
 'https://cjnews.cj.net',
 false, false, false,
 null, 3, 7, '{food,logistics,entertainment}'::text[], null,
 'upcoming', '2026', 'fresh', now(), now() + interval '90 days'),

('cj-onstyle-oncubating', 'corporate',
 'CJ온스타일 온큐베이팅', 'CJ Onstyle ON-Cubating',
 'CJ온스타일', 'CJ Onstyle',
 '뷰티·웰니스 브랜드 (개인 기획자/인플루언서/초기 창업자 포함)', 'Beauty & wellness brands (incl. planners, influencers, early founders)',
 '전용 110억 펀드 + 상품기획~글로벌 유통 + 정부 매칭 최대 10억 + Amazon·Ulta·Walmart 연계', '11B KRW fund + planning to global distribution + gov matching up to 1B + Amazon/Ulta/Walmart',
 '최대 10억원+',
 '2026.3.13 마감', 'Mar 13, 2026 deadline',
 'https://oncubating.cjonstyle.com/',
 false, false, false,
 null, null, null, '{beauty,wellness}'::text[], null,
 'closed', '2026', 'fresh', now(), now() + interval '90 days'),

('gs-challenge', 'corporate',
 'GS 리테일 The GS Challenge', 'GS Retail The GS Challenge',
 'GS리테일 + 서울창조경제혁신센터', 'GS Retail + Seoul CEIC',
 '리테일 테크 스타트업 (고객 데이터·콘텐츠 자동화·마케팅·CS)', 'Retail tech startups (customer data, content automation, marketing, CS)',
 'PoC 자금 최대 1,000만원 + 3개월 GS리테일 PoC + 1:1 멘토링 + 투자 검토', 'Up to 10M PoC fund + 3-month GS Retail PoC + mentoring + investment review',
 '최대 1,000만원',
 '연 1회 (3기: 2025)', 'Annual (3rd: 2025)',
 'https://www.thegschallenge.com/',
 false, false, false,
 null, null, null, '{retail,data,marketing}'::text[], null,
 'upcoming', '2026', 'fresh', now(), now() + interval '90 days'),

('lg-social-campus', 'corporate',
 'LG 소셜캠퍼스 소셜펠로우', 'LG Social Campus Social Fellow',
 'LG전자 + LG화학', 'LG Electronics + LG Chem',
 '기후·환경 분야 소셜 기업/스타트업', 'Climate/environment social enterprises/startups',
 '초기 3,000만원 + 성과 기반 추가 + 6개월 멘토링 + 전문 컨설팅 (회계·법률·노무·마케팅)', 'Initial 30M + performance bonus + 6-month mentoring + specialized consulting',
 '3,000만원+',
 '연 1회 모집', 'Annual recruitment',
 'https://lgsocialcampus.com',
 false, false, false,
 null, null, null, '{climate,environment}'::text[], null,
 'upcoming', '2026', 'fresh', now(), now() + interval '90 days'),

-- ═══════════════════════════════════════════════════════════════════════════════
-- FINANCIAL GROUPS (금융그룹)
-- ═══════════════════════════════════════════════════════════════════════════════

('shinhan-futures-lab', 'corporate',
 '신한 퓨처스랩', 'Shinhan Future''s Lab',
 '신한금융그룹', 'Shinhan Financial Group',
 '핀테크/스타트업 (협업 트랙 + 성장 트랙)', 'Fintech/startups (Collaboration + Growth tracks)',
 '신한 계열사 협업 + 투자 연계 + 글로벌 진출(베트남/일본) + 인큐베이션', 'Shinhan affiliate collaboration + investment + global expansion + incubation',
 null,
 '연 1회 (3월 모집)', 'Annual (Mar recruitment)',
 'https://www.futureslab.kr/',
 false, false, false,
 null, null, null, '{fintech,ai}'::text[], null,
 'upcoming', '2026', 'fresh', now(), now() + interval '90 days'),

('kb-starters', 'corporate',
 'KB 이노베이션허브 KB스타터스', 'KB Innovation HUB KB Starters',
 'KB금융그룹', 'KB Financial Group',
 '국내 7년 이내 기업 + 동남아 진출 기업', 'Domestic companies within 7yr + Southeast Asia expansion',
 'KB CVC 투자 연계 + KB Wise 컨설팅 (세무·노무·법률) + 계열사 협업 + 워크스페이스', 'KB CVC investment + KB Wise consulting + affiliate collaboration + workspace',
 '누적 투자 연계 2,544억원',
 '2026.2.2~3.6 모집', '2026 Feb 2-Mar 6 recruitment',
 'https://kbinnovationhub.com/apply/',
 false, false, false,
 null, 0, 7, null, null,
 'closed', '2026', 'fresh', now(), now() + interval '90 days'),

('hana-1q-agile-lab', 'corporate',
 '하나금융 원큐 애자일랩', 'Hana Financial 1Q Agile Lab',
 '하나은행 / 하나금융그룹', 'Hana Bank / Hana Financial Group',
 'AI·빅데이터·클라우드·핀테크 스타트업', 'AI, big data, cloud, fintech startups',
 '사무공간 + 하나금융 계열사 협업 + 직·간접 투자 + 글로벌 진출 + 청년 창업 지원', 'Office + Hana affiliate collaboration + investment + global + youth support',
 null,
 '연 1회 모집', 'Annual recruitment',
 'https://www.kebhana.com/1QLab/program/index.jsp',
 false, false, false,
 null, null, null, '{ai,fintech,data,cloud}'::text[], null,
 'upcoming', '2026', 'fresh', now(), now() + interval '90 days'),

('woori-dinnolab', 'corporate',
 '우리금융 디노랩', 'Woori Financial DINNOLab',
 '우리금융그룹', 'Woori Financial Group',
 'AI 핀테크·모빌리티·리걸테크·인슈어테크 스타트업', 'AI fintech, mobility, legaltech, insurtech startups',
 '스타트업 엑셀러레이팅 + 계열사 협업 + 투자 연계 (누적 4,000억 투자 연계) + DINNOLab 베트남', 'Acceleration + affiliate collaboration + investment linkage (cumulative 400B) + DINNOLab Vietnam',
 null,
 '연 1~2회 모집', '1-2 batches/year',
 'https://www.dinnolab.kr',
 false, false, false,
 null, null, null, '{ai,fintech,mobility,legaltech}'::text[], null,
 'upcoming', '2026', 'fresh', now(), now() + interval '90 days'),

('hanwha-dreamplus', 'corporate',
 '한화 드림플러스', 'Hanwha Dreamplus',
 '한화생명', 'Hanwha Life',
 '핀테크·라이프스타일 (헬스케어/웰니스/교육/디지털콘텐츠) 스타트업', 'Fintech & lifestyle (healthcare, wellness, education, digital content) startups',
 '6개월 전담 엑셀러레이팅 + 한화 금융 5개 계열사 협업 + 파트너 (고대의료원, 바이엘, 교원, 이랜드 등)', '6-month acceleration + 5 Hanwha financial affiliates + partners (Korea Univ Hospital, Bayer, etc.)',
 null,
 '연 1~2회 모집', '1-2 batches/year',
 'https://dreamplus.asia/',
 false, false, false,
 null, null, null, '{fintech,healthcare,wellness,education}'::text[], null,
 'upcoming', '2026', 'fresh', now(), now() + interval '90 days'),

-- ═══════════════════════════════════════════════════════════════════════════════
-- PRIVATE / FOUNDATION (민간·재단·액셀러레이터)
-- ═══════════════════════════════════════════════════════════════════════════════

('asan-doers', 'private',
 '아산 두어스', 'Asan Doers',
 '아산나눔재단', 'Asan Nanum Foundation',
 '만 19~29세 예비창업가 (법인 미설립)', 'Ages 19-29, pre-incorporation',
 '해외 진출 지원금 100만원 + 7개월 인큐베이팅 + 멘토링 + MARU 네트워크', '1M KRW overseas fund + 7-month incubation + mentoring + MARU network',
 '1인 100만원 + 멘토링',
 '연 1~2회 모집 (3~4월)', '1-2 batches/year (Mar-Apr)',
 'https://doers.asan-nanum.org',
 false, false, true,
 29, 0, 0, null, null,
 'upcoming', '2026', 'fresh', now(), now() + interval '90 days'),

('primer-batch', 'private',
 '프라이머 배치', 'Primer Batch',
 '프라이머 (국내 최초 액셀러레이터)', 'Primer (Korea''s first accelerator)',
 '초기 스타트업 (선호도 1위 액셀러레이터)', 'Early startups (#1 preferred accelerator)',
 '시드 투자 1억원 (기업가치 10억 기준) + 멘토링 + 네트워킹 + 데모데이', 'Seed investment 100M (at 1B valuation) + mentoring + networking + demo day',
 '1억원 투자',
 '연 2회 배치 (6월, 12월)', '2 batches/year (Jun, Dec)',
 'https://www.primer.kr',
 false, false, true,
 null, null, null, null, null,
 'upcoming', '2026', 'fresh', now(), now() + interval '90 days'),

('sparklabs-batch', 'private',
 '스파크랩 배치 프로그램', 'SparkLabs Batch Program',
 '스파크랩', 'SparkLabs',
 '초기 스타트업 (글로벌 진출 의향, 2인 이상 팀, 설립 3년 이내)', 'Early startups (global ambition, 2+ members, within 3yr)',
 '1억원+ 투자 (CPS/SAFE, 약 6%) + 22주 1:1 코칭 + 데모데이 + 글로벌 네트워크', '100M+ investment (CPS/SAFE, ~6%) + 22-week coaching + demo day + global network',
 '1억원+ 투자',
 '연 2회 (4월, 9월 접수)', '2 batches/year (Apr, Sep)',
 'https://sparklabs.co.kr/kr/',
 false, false, false,
 null, 0, 3, null, null,
 'upcoming', '2026', 'fresh', now(), now() + interval '90 days'),

('mashup-ventures', 'private',
 '매쉬업벤처스', 'MashUp Ventures',
 '매쉬업벤처스 (구 매쉬업엔젤스)', 'MashUp Ventures (fmr MashUp Angels)',
 'AI·SaaS·커머스·딥테크 초기 스타트업', 'AI, SaaS, commerce, deep tech early startups',
 '최대 5억원 투자 + 팔로온 적극 투자 + TIPS 100% 선정률 + 클라우드 크레딧 최대 8억', 'Up to 500M investment + active follow-on + 100% TIPS rate + up to 800M cloud credits',
 '최대 5억원',
 '상시 투자', 'Year-round investment',
 'https://www.mashupventures.co/',
 false, false, false,
 null, null, null, '{ai,saas,commerce,deep-tech}'::text[], null,
 'open', '2026', 'fresh', now(), now() + interval '90 days'),

('bonangels-chosim', 'private',
 '본엔젤스 초심캠프', 'BonAngels Chosim Camp',
 '본엔젤스벤처파트너스', 'BonAngels Venture Partners',
 '시드/Pre-A 단계 스타트업', 'Seed/Pre-A stage startups',
 '최대 3억원 투자 + 팔로온 투자 + TIPS 추천', 'Up to 300M investment + follow-on + TIPS recommendation',
 '최대 3억원',
 '연 2회 (상반기, 하반기)', '2 batches/year (H1, H2)',
 'https://www.bonangels.net/',
 false, false, false,
 null, null, null, null, null,
 'upcoming', '2026', 'fresh', now(), now() + interval '90 days'),

('bluepoint-partners', 'private',
 '블루포인트파트너스', 'Bluepoint Partners',
 '블루포인트파트너스', 'Bluepoint Partners',
 '딥테크·초기 스타트업', 'DeepTech & early startups',
 '시드 투자 + 국내 최대 규모 데모데이 + 멘토링 + RAPTORS 방산 진입 지원', 'Seed investment + Korea''s largest demo day + mentoring + RAPTORS defense program',
 null,
 '연 1~2회', '1-2 times/year',
 'https://bluepoint.ac/',
 false, false, false,
 null, null, null, null, null,
 'upcoming', '2026', 'fresh', now(), now() + interval '90 days'),

('futureplay', 'private',
 '퓨처플레이', 'FuturePlay',
 '퓨처플레이', 'FuturePlay',
 'AI·자율주행·로봇·드론·디지털헬스케어·핀테크·VR/AR 스타트업', 'AI, autonomous driving, robotics, drone, digital healthcare, fintech, VR/AR startups',
 '사업화 자금 1,000~5,000만원 + 지분 투자 + 1:1 전담 멘토', 'Commercialization 10-50M + equity investment + dedicated 1:1 mentor',
 '1,000~5,000만원 + 투자',
 '상시', 'Year-round',
 'https://futureplay.co/',
 false, false, false,
 null, null, null, '{ai,robotics,healthcare,fintech}'::text[], null,
 'open', '2026', 'fresh', now(), now() + interval '90 days'),

('dcamp-dday', 'private',
 'D.CAMP 디데이', 'D.CAMP D.DAY',
 '은행권청년창업재단', 'Banks Youth Startup Foundation',
 '초기 스타트업 (매월 선발)', 'Early startups (monthly selection)',
 '월간 피칭 대회 + 투자 연계 + 디캠프/프론트원 입주 기회 (최대 1년)', 'Monthly pitch + investment linkage + D.CAMP/FRONT1 residency (up to 1yr)',
 null,
 '매월 진행', 'Monthly',
 'https://dcamp.kr/dday',
 false, false, true,
 null, null, null, null, null,
 'open', '2026', 'fresh', now(), now() + interval '90 days'),

('sk-lookie', 'private',
 'SK LOOKIE', 'SK LOOKIE',
 'SK 행복나눔재단', 'SK Happiness Foundation',
 '대학생 소셜 이노베이터', 'University social innovators',
 '소셜 비즈니스 모델 개발 + 멘토링 + 네트워크 (2017년~ 1,000명+ 양성)', 'Social biz model dev + mentoring + network (1,000+ alumni since 2017)',
 null,
 '연 1회 모집', 'Annual recruitment',
 'https://www.sklookie.com',
 false, false, false,
 null, null, null, null, null,
 'upcoming', '2026', 'fresh', now(), now() + interval '90 days'),

('hyundai-cmk', 'private',
 'CMK 임팩트프러너 (구 H-온드림)', 'CMK Impactpreneur (fmr H-OnDream)',
 '현대차 정몽구 재단', 'Hyundai CMK Foundation',
 '사회문제 해결 임팩트 스타트업', 'Social impact startups',
 '사업화 자금 + 멘토링 + UNDP 글로벌 프로그램 연계 + 투자', 'Biz funds + mentoring + UNDP global linkage + investment',
 null,
 '연 1회 모집 (상반기)', 'Annual recruitment (H1)',
 'https://www.h-ondream.kr',
 false, false, false,
 null, null, null, null, null,
 'upcoming', '2026', 'fresh', now(), now() + interval '90 days'),

-- ═══════════════════════════════════════════════════════════════════════════════
-- COMPETITIONS (대회/경진대회)
-- ═══════════════════════════════════════════════════════════════════════════════

('challenge-k-startup', 'competition',
 '도전! K-스타트업', 'Challenge! K-Startup',
 '중소벤처기업부 + 9개 정부부처', 'MSS + 9 government ministries',
 '전 연령 창업자 (혁신창업리그 + 예비창업리그)', 'All-age founders (Innovation League + Pre-Startup League)',
 '대한민국 최대 규모 창업 경진대회 + 수상 시 정부 창업패키지 가점 + 시상금', 'Korea''s largest startup competition + gov package preference + prizes',
 '시상금 + 정부패키지 가점',
 '상반기 접수, 하반기 본선', 'H1 application, H2 finals',
 'https://www.challengek.org/',
 true, false, true,
 null, null, null, null, null,
 'upcoming', '2026', 'fresh', now(), now() + interval '90 days'),

('jjy-competition', 'competition',
 '정주영 창업경진대회', 'Chung Ju-yung Startup Competition',
 '아산나눔재단', 'Asan Nanum Foundation',
 '전 연령 (글로벌·다양성·기후테크·예비창업 4개 트랙)', 'All ages (4 tracks: Global, Diversity, ClimateTech, Pre-startup)',
 '총 상금 4억원 + 멘토링 + 해외진출 (MARU SF) + 투자 연계', '400M KRW total prize + mentoring + overseas (MARU SF) + investment',
 '총 상금 4억원',
 '상반기 모집 (2026.2.26~3.22), 하반기 데모데이', 'H1 recruitment (2026 Feb 26-Mar 22), H2 demo day',
 'https://startup.asan-nanum.org/',
 false, false, true,
 null, null, null, null, null,
 'closed', '2026', 'fresh', now(), now() + interval '60 days'),

('social-venture-competition', 'competition',
 '소셜벤처 경연대회', 'Social Venture Competition',
 '고용노동부 + 한국사회적기업진흥원', 'Ministry of Employment + KOSEA',
 '사회적 가치 창출 창의적 아이디어 보유 (예비)창업자', 'Pre-founders with creative social value ideas',
 '수상 시 사업화 자금 + 멘토링 + 투자 연계', 'Prizes + commercialization fund + mentoring + investment',
 null,
 '연 1회', 'Annual',
 'https://www.socialventure.or.kr',
 false, false, false,
 null, null, null, null, null,
 'upcoming', '2026', 'fresh', now(), now() + interval '90 days'),

('k-startup-grand-challenge', 'competition',
 'K-Startup 그랜드챌린지', 'K-Startup Grand Challenge',
 'NIPA + 중소벤처기업부', 'NIPA + MSS',
 '한국 진출 희망 해외 스타트업', 'Foreign startups seeking to establish in Korea',
 '평균 5,000만원 (최대 8,000만원) + 글로벌 스타트업센터 입주 + 투자·비자·법인설립 지원', 'Avg 50M (max 80M) + Global Startup Center + investment, visa, company setup',
 '평균 5,000만원',
 '연 1회 (상반기 모집)', 'Annual (H1 recruitment)',
 'https://www.k-startupgc.org/',
 false, false, false,
 null, null, null, '{ai,robotics,bio,fintech,clean-energy}'::text[], null,
 'upcoming', '2026', 'fresh', now(), now() + interval '90 days'),

('seoul-finnovation', 'competition',
 '서울핀테크랩 피노베이션 챌린지', 'Seoul FinTech Lab FINnovation Challenge',
 '서울시 + 신한은행', 'Seoul Metropolitan + Shinhan Bank',
 '핀테크·AI·빅데이터·인슈어테크·프롭테크 스타트업', 'Fintech, AI, big data, insurtech, proptech startups',
 '사업화 자금 1,000만원 + 서울핀테크랩/신한퓨처스랩 1년 입주', '10M fund + 1-year incubation at Seoul FinTech Lab or Shinhan Future''s Lab',
 '1,000만원 + 1년 입주',
 '연 1회', 'Annual',
 'https://seoulfintech.kr',
 false, false, false,
 null, null, null, '{fintech,ai,data,insurtech,proptech}'::text[], null,
 'upcoming', '2026', 'fresh', now(), now() + interval '90 days'),

-- ═══════════════════════════════════════════════════════════════════════════════
-- GLOBAL TECH (글로벌 기업 한국 프로그램)
-- ═══════════════════════════════════════════════════════════════════════════════

('google-startup-accelerator-kr', 'corporate',
 'Google for Startups Accelerator: Korea', 'Google for Startups Accelerator: Korea',
 '구글', 'Google',
 '시드~Series A 한국 AI/ML 스타트업', 'Seed to Series A Korean AI/ML startups',
 '10주 무지분 프로그램 + 최대 $350K 클라우드 크레딧 + 전담 전문가 + 기술 교육', '10-week equity-free + up to $350K cloud credits + dedicated expert + tech training',
 '클라우드 크레딧 최대 $350K',
 '2026.1.12~3.2 접수, 4~7월 프로그램', '2026 Jan 12-Mar 2 application, Apr-Jul program',
 'https://startup.google.com/programs/accelerator/korea/',
 false, false, false,
 null, null, null, '{ai,ml}'::text[], null,
 'closed', '2026', 'fresh', now(), now() + interval '90 days'),

('google-campus-seoul', 'corporate',
 '구글 스타트업 캠퍼스 서울', 'Google for Startups Campus Seoul',
 '구글', 'Google',
 '스타트업에 열정 있는 누구나', 'Anyone passionate about startups',
 '무료 코워킹 스페이스 + 크리에이터 스튜디오 + 이벤트 + 커뮤니티', 'Free coworking + Creator Studio + events + community',
 '무료',
 '상시 (월~금 9~21시, 토 9~17시)', 'Always open (Mon-Fri 9AM-9PM, Sat 9AM-5PM)',
 'https://startup.google.com/campus/seoul/',
 true, false, false,
 null, null, null, null, '{"서울"}'::text[],
 'open', '2026', 'fresh', now(), now() + interval '180 days'),

('microsoft-startups-kr', 'corporate',
 'Microsoft for Startups', 'Microsoft for Startups',
 '마이크로소프트 한국', 'Microsoft Korea',
 'Pre-seed~Series C 소프트웨어 기반 스타트업', 'Pre-seed to Series C software-based startups',
 '총 최대 5억원 혜택: Azure 크레딧 최대 2억원 + GitHub·VS·M365·Power Platform 1년 무료 + 공동 판매', 'Up to 500M total: Azure credits up to 200M + GitHub/VS/M365/Power Platform 1yr free + co-selling',
 '클라우드 크레딧 최대 2억원',
 '상시 신청', 'Year-round',
 'https://www.microsoft.com/ko-kr/startups',
 false, false, false,
 null, null, null, null, null,
 'open', '2026', 'fresh', now(), now() + interval '180 days'),

('aws-activate', 'corporate',
 'AWS Activate', 'AWS Activate',
 'Amazon Web Services', 'Amazon Web Services',
 '설립 10년 이내·Series A 이전 스타트업 (파트너 연계)', 'Startups under 10yr, pre-Series A (via partner accelerators)',
 'AWS 클라우드 크레딧 + 기술 교육 + 투자 네트워킹', 'AWS cloud credits + tech training + investment networking',
 '최대 $100K 클라우드 크레딧',
 '상시 (파트너 액셀러레이터 통해 신청)', 'Year-round (via partner accelerators)',
 'https://www.awsstartup.io',
 false, false, false,
 null, 0, 10, null, null,
 'open', '2026', 'fresh', now(), now() + interval '180 days'),

-- ═══════════════════════════════════════════════════════════════════════════════
-- LOCAL GOVERNMENT (지자체)
-- ═══════════════════════════════════════════════════════════════════════════════

('seoul-startup-hub', 'local',
 '서울창업허브', 'Seoul Startup Hub',
 '서울산업진흥원 (SBA)', 'Seoul Business Agency (SBA)',
 '서울 소재 (예비)창업자', 'Seoul-based (pre-)founders',
 '사무공간 6개월~1년 무상 + 창업 프로그램 + 네트워킹', 'Free office 6-12mo + programs + networking',
 '사무공간+프로그램',
 '연 1~2회 공고 (3월, 9월)', '1-2 notices/year (Mar, Sep)',
 'https://seoulstartuphub.com',
 true, false, false,
 null, null, null, null, '{"서울"}'::text[],
 'upcoming', '2026', 'fresh', now(), now() + interval '90 days'),

('campus-town', 'local',
 '캠퍼스타운', 'Campus Town',
 '서울시', 'Seoul Metropolitan Government',
 '만 39세 이하, 창업 7년 미만 (신산업 10년)', 'Under 39, less than 7yr (10yr for new industries)',
 '창업활동비 최대 2,500만원 + 대학 인근 사무공간 최대 4년 입주', 'Up to 25M activity fund + 4yr office near university',
 '최대 2,500만원',
 '매년 초 공고', 'Annual early-year notice',
 'https://youth.seoul.go.kr',
 true, false, false,
 39, 0, 7, null, '{"서울"}'::text[],
 'upcoming', '2026', 'fresh', now(), now() + interval '90 days'),

('seoul-youth-cook', 'local',
 '서울 청년쿡 비즈니스센터', 'Seoul Youth Cook Business Center',
 '서울시', 'Seoul Metropolitan Government',
 '외식업 청년 창업자', 'Young F&B entrepreneurs',
 '공유주방 + 외식 창업 교육 + 인큐베이팅', 'Shared kitchen + F&B startup education + incubation',
 '공유주방+교육',
 '수시 모집', 'Rolling recruitment',
 'https://youth.seoul.go.kr/content.do?key=2310100028',
 true, false, true,
 null, null, null, '{food}'::text[], '{"서울"}'::text[],
 'open', '2026', 'fresh', now(), now() + interval '90 days')

on conflict (program_key) do update set
  name_ko = excluded.name_ko,
  name_en = excluded.name_en,
  benefit_ko = excluded.benefit_ko,
  benefit_en = excluded.benefit_en,
  amount = excluded.amount,
  application_status = excluded.application_status,
  freshness_status = excluded.freshness_status,
  last_checked_at = excluded.last_checked_at,
  next_review_at = excluded.next_review_at,
  updated_at = now();
