insert into public.market_location_signals (
  region_key,
  region_name,
  district_name,
  category_id,
  search_keywords,
  market_style,
  rent_band,
  competition_level,
  demand_level,
  access_level,
  category_fit_level,
  base_score,
  summary,
  evidence,
  freshness_status,
  last_checked_at,
  next_review_at,
  notes
)
values
  (
    'seongsu-food',
    '성수동',
    '성동구',
    'food',
    array['성수', '성수동', '서울숲'],
    'destination',
    'high',
    'high',
    'high',
    'strong',
    'mid-high',
    79,
    '브랜드형 식사 업종은 가능하지만 임대료와 경쟁 강도를 더 보수적으로 봐야 하는 상권입니다.',
    '{"reasons":["유동성과 노출은 강함","목적 방문 수요가 꾸준함"],"warnings":["식사형 외식은 원가와 임대료 압박을 같이 받기 쉬움"]}'::jsonb,
    'fresh',
    '2026-03-19T09:00:00+09:00',
    '2026-03-26T09:00:00+09:00',
    null
  ),
  (
    'seongsu-retail',
    '성수동',
    '성동구',
    'retail',
    array['성수', '성수동', '서울숲'],
    'destination',
    'high',
    'high',
    'high',
    'strong',
    'strong',
    86,
    '브랜드형 소매와 쇼룸형 공간이 잘 맞는 상권입니다.',
    '{"reasons":["브랜드 발견형 소비가 활발함","쇼룸/체험형 매장에 유리"],"warnings":["임대료와 경쟁이 빠르게 높아질 수 있음"]}'::jsonb,
    'fresh',
    '2026-03-19T09:00:00+09:00',
    '2026-03-26T09:00:00+09:00',
    null
  ),
  (
    'pangyo-cafe',
    '판교',
    '성남시',
    'cafe-dessert',
    array['판교', '판교역'],
    'office',
    'mid-high',
    'mid-high',
    'high',
    'strong',
    'mid-high',
    78,
    '오피스 수요 기반의 테이크아웃형 카페에 더 잘 맞는 상권입니다.',
    '{"reasons":["출근·점심 시간대 유입이 분명함","테이크아웃과 빠른 회전에 유리"],"warnings":["주말 수요 편차가 크고 목적 방문형 카페에는 덜 유리함"]}'::jsonb,
    'fresh',
    '2026-03-19T09:00:00+09:00',
    '2026-03-26T09:00:00+09:00',
    null
  ),
  (
    'gangnam-fitness',
    '강남',
    '강남구',
    'fitness',
    array['강남', '강남역', '신논현'],
    'destination',
    'high',
    'high',
    'high',
    'strong',
    'mid-high',
    80,
    '프리미엄 피트니스와 PT형 스튜디오에는 강하지만 고정비 압박도 큰 상권입니다.',
    '{"reasons":["소비 여력과 브랜드 수요가 큼","프리미엄 포지셔닝 가능"],"warnings":["시설 투자와 임대료가 동시에 높음"]}'::jsonb,
    'review_soon',
    '2026-03-18T09:00:00+09:00',
    '2026-03-25T09:00:00+09:00',
    null
  ),
  (
    'yeouido-retail',
    '여의도',
    '영등포구',
    'retail',
    array['여의도', '여의도역'],
    'office',
    'high',
    'mid-high',
    'high',
    'strong',
    'mid',
    75,
    '실용형 소매는 가능하지만 목적 방문형 브랜드 소매에는 제한이 있는 오피스 상권입니다.',
    '{"reasons":["점심/퇴근 수요가 존재함","실용형 상품은 검토 가능"],"warnings":["발견형 소매나 체류형 쇼핑에는 불리할 수 있음"]}'::jsonb,
    'fresh',
    '2026-03-19T09:00:00+09:00',
    '2026-03-26T09:00:00+09:00',
    null
  ),
  (
    'dongtan-cafe',
    '동탄',
    '화성시',
    'cafe-dessert',
    array['동탄', '동탄신도시'],
    'residential',
    'mid-high',
    'mid',
    'mid',
    'balanced',
    'mid-high',
    77,
    '동네형 반복 수요를 만드는 카페에는 적합하지만 목적 방문형 브랜딩은 상대적으로 느릴 수 있습니다.',
    '{"reasons":["주거 기반 반복 방문 가능","가족 생활권 수요를 기대할 수 있음"],"warnings":["브랜드 확장 속도는 도심 목적 상권보다 느릴 수 있음"]}'::jsonb,
    'fresh',
    '2026-03-18T09:00:00+09:00',
    '2026-03-25T09:00:00+09:00',
    null
  )
on conflict (region_key) do update
set
  region_name = excluded.region_name,
  district_name = excluded.district_name,
  category_id = excluded.category_id,
  search_keywords = excluded.search_keywords,
  market_style = excluded.market_style,
  rent_band = excluded.rent_band,
  competition_level = excluded.competition_level,
  demand_level = excluded.demand_level,
  access_level = excluded.access_level,
  category_fit_level = excluded.category_fit_level,
  base_score = excluded.base_score,
  summary = excluded.summary,
  evidence = excluded.evidence,
  freshness_status = excluded.freshness_status,
  last_checked_at = excluded.last_checked_at,
  next_review_at = excluded.next_review_at,
  notes = excluded.notes,
  is_active = true,
  updated_at = now();
